package scripts

import services.MongoConnection
import services.titlerules.{MongoTitleRulesRepo, TitleRule, TitleRuleRecord}

import java.nio.file.{Files, Paths}

/**
 * Dumps the prod `titleRules` collection into [[GeneratedTitleRules]] — a
 * checked-in Scala mirror of EXACTLY the rules prod runs, so the test suite
 * exercises the live rule set (admin-UI edits included), not just the curated
 * [[ExtraTitleRules]]. This is the DB→code direction; [[ApplyExtraTitleRules]]
 * is the code→DB push for proposing new rules.
 *
 * Deterministic: rules are regrouped by record (`TitleRuleRecord.fromRules`
 * sorts by scope then cinemaId, preserving each record's in-array order) so the
 * output is stable run-to-run and a diff means the prod rules actually changed.
 *
 * Run against prod via the flyctl proxy (read-only):
 *   flyctl proxy 27017:27017 --app kinowo-mongo   # in one shell
 *   set -a; source .env.local; set +a              # MONGODB_URI → 127.0.0.1
 *   sbt 'worker/Test/runMain scripts.DumpTitleRules'
 *
 * The scheduled `.github/workflows/sync-title-rules.yml` runs this against prod
 * and opens a PR whenever the regenerated file differs from main.
 */
object DumpTitleRules {

  private val Out = Paths.get("worker/src/test/scala/scripts/GeneratedTitleRules.scala")

  /** Deterministic, record-grouped order — the canonical shape we emit. */
  def ordered(prodRules: Seq[TitleRule]): Seq[TitleRule] =
    TitleRuleRecord.fromRules(prodRules).flatMap(_.toRules)

  // ── emitter (pure + unit-tested) ───────────────────────────────────────────

  private def q(s: String): String =
    "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n") + "\""

  private def opt(o: Option[String]): String = o.fold("None")(s => s"Some(${q(s)})")

  private def rule(r: TitleRule): String =
    s"    TitleRule(${q(r.id)}, ${r.scope.name}, ${opt(r.cinemaId)}, ${q(r.pattern)}, ${q(r.replacement)}, " +
      s"applyAll = ${r.applyAll}, order = ${r.order}, last = ${r.last}, enabled = ${r.enabled}, tag = ${opt(r.tag)}, note = ${opt(r.note)})"

  /** Render the whole `GeneratedTitleRules.scala` source from already-ordered
   *  rules. Pure + deterministic so [[DumpTitleRulesSpec]] can pin the escaping
   *  and shape without a database. */
  def render(rules: Seq[TitleRule]): String = {
    val body = rules.map(rule).mkString(",\n")
    s"""|// GENERATED by scripts.DumpTitleRules from the prod `titleRules` collection.
        |// DO NOT EDIT BY HAND. Refresh by re-running the dump, or let the scheduled
        |// `.github/workflows/sync-title-rules.yml` open a PR when prod drifts.
        |package scripts
        |
        |import services.titlerules.RuleScope._
        |import services.titlerules.TitleRule
        |
        |/** A code mirror of EXACTLY the prod `titleRules` set, so tests run the
        | *  live rules (admin-UI additions + [[ApplyExtraTitleRules]] pushes), not
        | *  only the frozen [[services.titlerules.TitleRuleDefaults]] seed. Install
        | *  the whole set: `TitleRuleSet(GeneratedTitleRules.all)`. */
        |object GeneratedTitleRules {
        |  val all: Seq[TitleRule] = Seq(
        |$body
        |  )
        |}
        |""".stripMargin
  }

  def main(args: Array[String]): Unit = {
    val conn = MongoConnection.fromEnv(required = true)
    val repo = new MongoTitleRulesRepo(conn.database, fallbackToOwnInit = false)
    try {
      val rules = ordered(repo.findAll())
      Files.createDirectories(Out.getParent)
      Files.write(Out, render(rules).getBytes("UTF-8"))
      println(s"Wrote ${rules.size} prod title rules to $Out")
    } finally {
      repo.close()
      conn.close()
    }
  }
}
