package scripts

import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.should.Matchers
import services.titlerules.RuleScope._
import services.titlerules.TitleRule

/** Pins the [[DumpTitleRules]] emitter: a regex-laden, quote-bearing rule must
 *  round-trip into a source line that COMPILES (backslashes doubled, quotes
 *  escaped), the scope renders as the bare `RuleScope` identifier, and the order
 *  is deterministic — so the generated mirror is stable run-to-run and a diff in
 *  the scheduled PR means the prod rules genuinely changed. */
class DumpTitleRulesSpec extends AnyFlatSpec with Matchers {

  "DumpTitleRules.render" should "escape backslashes and quotes so the emitted source compiles" in {
    val r = TitleRule("xtra-x", Search, None, """(?i)^A\s+"B"\|\s*""", "",
      applyAll = false, order = 5, last = false, enabled = true, tag = None, note = Some("a note"))
    val out = DumpTitleRules.render(Seq(r))
    // `\` → `\\`, `"` → `\"`, scope as a bare identifier, options rendered.
    out should include ("""TitleRule("xtra-x", Search, None, "(?i)^A\\s+\"B\"\\|\\s*", "", """ +
      """applyAll = false, order = 5, last = false, enabled = true, tag = None, note = Some("a note"))""")
    out should include ("object GeneratedTitleRules")
    out should include ("import services.titlerules.RuleScope._")
    out should startWith ("// GENERATED by scripts.DumpTitleRules")
  }

  it should "render PerCinema scope with its cinemaId and a programmePrefix tag" in {
    val r = TitleRule("cc-x", PerCinema, Some("cinema-city"), "x", "",
      applyAll = true, order = 0, last = true, enabled = false, tag = Some("programmePrefix"), note = None)
    DumpTitleRules.render(Seq(r)) should include (
      """TitleRule("cc-x", PerCinema, Some("cinema-city"), "x", "", """ +
      """applyAll = true, order = 0, last = true, enabled = false, tag = Some("programmePrefix"), note = None)""")
  }

  "DumpTitleRules.ordered" should "be deterministic regardless of input order" in {
    val a = TitleRule("a", Search,    None, "a", "", applyAll = false, order = 0, last = false, enabled = true, tag = None, note = None)
    val b = TitleRule("b", Canonical, None, "b", "", applyAll = false, order = 0, last = false, enabled = true, tag = None, note = None)
    DumpTitleRules.ordered(Seq(a, b)).map(_.id) shouldBe DumpTitleRules.ordered(Seq(b, a)).map(_.id)
  }
}
