package pl.kinowo.model

import kotlin.math.atan2
import kotlin.math.cos
import kotlin.math.sin
import kotlin.math.sqrt

/**
 * A city the repertoire is served for. The [slug] is the URL prefix the server
 * mounts every page + API under (`/{slug}/api/repertoire`, …); [name] is the
 * display label; [lat]/[lon] place it for the nearest-city location gate.
 */
@kotlinx.serialization.Serializable
data class City(
    val slug: String,
    val name: String,
    val lat: Double,
    val lon: Double,
    /**
     * ISO country code (`"PL"`, `"GB"`) matching [Country.code]. The app is
     * multi-country: every city picker, the nearest-city gate, and the default
     * city are scoped to the SELECTED country's cities, so a UK user browses UK
     * regions and a Polish user browses Polish cities — never a mix.
     */
    val country: String,
    /**
     * The group this city is picked under, where its country groups them at all
     * — a US state ("California"), a UK nation ("Scotland") — and null in the
     * countries that group nothing. Neither 468 US places nor 79 UK counties in
     * one A-to-Z is a list anybody reads, so the picker asks for the group
     * first; a country without regions keeps the single flat list.
     *
     * Carried by `/api/catalog` (and the bundled seed). Defaulted so a catalog
     * from an older server, or one of the hand-written [Cities.all] rows, still
     * decodes.
     */
    val region: String? = null,
    /**
     * The SECOND-level group [region] sits under a further split, where that
     * split actually holds more than one city — the UK's West Midlands
     * (Birmingham/Dudley/Sandwell), Glamorgan (Cardiff/Glamorgan) and Antrim
     * (Antrim/Belfast). Null everywhere else: a county that collapsed onto its
     * one place reads correctly through [region] alone (Cheshire needs no
     * third tap to reach Cheshire), and Germany/the US never nest this deep.
     *
     * Carried by `/api/catalog` (and the bundled seed), same shape as [region].
     */
    val subregion: String? = null,
    /**
     * This city's own IANA zone, where it differs from its country's; null
     * otherwise — which is every city of the four countries that keep one zone
     * throughout, so the field costs nothing there.
     *
     * The US spans SIX zones and fifteen of its states straddle a boundary, so a
     * single country zone is wrong for most of it: pruning a Knoxville showtime
     * on the country's Pacific drops it three hours early. Resolve through
     * [zoneFor], never by reading this directly.
     *
     * Carried by `/api/catalog` (and the bundled seed), same shape as [region]:
     * defaulted so a catalog from an older server, or one of the hand-written
     * [Cities.all] rows, still decodes.
     */
    val timezone: String? = null,
)

/**
 * The zone to reason about [slug]'s showtimes in — that city's own where the
 * catalog gave it one, else [fallback] (its country's).
 *
 * Also the answer for a slug this catalog does not know, which is what a stale
 * saved selection or a deep link into another deployment looks like, and for an
 * identifier the platform cannot parse. Past-showtime pruning and the day
 * buckets both go through here, so they cannot disagree.
 */
fun List<City>.zoneFor(slug: String?, fallback: java.time.ZoneId): java.time.ZoneId {
    val city = slug?.let { s -> firstOrNull { it.slug == s } } ?: return fallback
    val id = city.timezone ?: return fallback
    return runCatching { java.time.ZoneId.of(id) }.getOrDefault(fallback)
}

/**
 * A one-shot offer to switch the repertoire to a [target] city the device is
 * now nearer than the chosen one. [key] is the `chosen→nearest` pair the prompt
 * is remembered against, so we only ask once per pair.
 */
data class CitySwitchSuggestion(val target: City, val key: String)

/**
 * The catalogue of supported cities across ALL countries, plus the location →
 * city resolution used by the first-launch gate. [all] mirrors the web
 * `City.all` ordering (Polish cities first, then the UK regions) so the pickers
 * read identically across platforms. The data-driven rosters — Germany's 158
 * regions and the US's 55 states/territories — are NOT mirrored here: they
 * arrive with the catalog (bundled seed, then the live `/api/catalog`), so there
 * is one copy of them rather than two that drift.
 * This is the GLOBAL union; the pickers and
 * the nearest-city gate scope it to the selected country via [citiesIn] /
 * [matching] / [nearestWithin100km]. A new city is added by extending [all]
 * (with its [City.country]).
 */
object Cities {
    val all: List<City> = listOf(
        // ── Poland: GENERATED by data/pl/scripts/generate_polish_pages.py — do not edit by hand.
        City("poznan", "Poznań", 52.4064, 16.9252, "pl", "Wielkopolskie"),
        City("wroclaw", "Wrocław", 51.1079, 17.0385, "pl", "Dolnośląskie"),
        City("warszawa", "Warszawa", 52.2297, 21.0122, "pl", "Mazowieckie"),
        City("krakow", "Kraków", 50.0647, 19.9450, "pl", "Małopolskie"),
        City("lodz", "Łódź", 51.7592, 19.4560, "pl", "Łódzkie"),
        City("katowice", "Katowice", 50.2649, 19.0238, "pl", "Śląskie"),
        City("szczecin", "Szczecin", 53.4285, 14.5528, "pl", "Zachodniopomorskie"),
        City("bialystok", "Białystok", 53.1325, 23.1688, "pl", "Podlaskie"),
        City("trojmiasto", "Trójmiasto", 54.4416, 18.5601, "pl", "Pomorskie"),
        City("bydgoszcz", "Bydgoszcz", 53.1235, 18.0084, "pl", "Kujawsko-pomorskie"),
        City("lublin", "Lublin", 51.2465, 22.5684, "pl", "Lubelskie"),
        City("czestochowa", "Częstochowa", 50.8118, 19.1203, "pl", "Śląskie"),
        City("radom", "Radom", 51.4027, 21.1471, "pl", "Mazowieckie"),
        City("sosnowiec", "Sosnowiec", 50.2863, 19.1041, "pl", "Śląskie"),
        City("torun", "Toruń", 53.0138, 18.5984, "pl", "Kujawsko-pomorskie"),
        City("kielce", "Kielce", 50.8661, 20.6286, "pl", "Świętokrzyskie"),
        City("rzeszow", "Rzeszów", 50.0413, 21.9990, "pl", "Podkarpackie"),
        City("gliwice", "Gliwice", 50.2945, 18.6714, "pl", "Śląskie"),
        City("zabrze", "Zabrze", 50.3249, 18.7857, "pl", "Śląskie"),
        City("olsztyn", "Olsztyn", 53.7784, 20.4801, "pl", "Warmińsko-mazurskie"),
        City("bielsko-biala", "Bielsko-Biała", 49.8224, 19.0584, "pl", "Śląskie"),
        City("opole", "Opole", 50.6751, 17.9213, "pl", "Opolskie"),
        City("rybnik", "Rybnik", 50.0971, 18.5416, "pl", "Śląskie"),
        City("gorzow-wielkopolski", "Gorzów Wielkopolski", 52.7368, 15.2288, "pl", "Lubuskie"),
        City("elblag", "Elbląg", 54.1522, 19.4088, "pl", "Warmińsko-mazurskie"),
        City("koszalin", "Koszalin", 54.1943, 16.1722, "pl", "Zachodniopomorskie"),
        City("kalisz", "Kalisz", 51.7611, 18.0911, "pl", "Wielkopolskie"),
        City("zielona-gora", "Zielona Góra", 51.9356, 15.5062, "pl", "Lubuskie"),
        City("tychy", "Tychy", 50.1357, 18.9985, "pl", "Śląskie"),
        City("walbrzych", "Wałbrzych", 50.7714, 16.2845, "pl", "Dolnośląskie"),
        City("tarnow", "Tarnów", 50.0121, 20.9858, "pl", "Małopolskie"),
        City("wloclawek", "Włocławek", 52.6483, 19.0677, "pl", "Kujawsko-pomorskie"),
        City("legnica", "Legnica", 51.2070, 16.1619, "pl", "Dolnośląskie"),
        City("plock", "Płock", 52.5468, 19.7064, "pl", "Mazowieckie"),
        City("bytom", "Bytom", 50.3483, 18.9157, "pl", "Śląskie"),
        City("dabrowa-gornicza", "Dąbrowa Górnicza", 50.3219, 19.1876, "pl", "Śląskie"),
        City("nowy-sacz", "Nowy Sącz", 49.6175, 20.7154, "pl", "Małopolskie"),
        City("slupsk", "Słupsk", 54.4641, 17.0287, "pl", "Pomorskie"),
        City("jelenia-gora", "Jelenia Góra", 50.9044, 15.7197, "pl", "Dolnośląskie"),
        City("przemysl", "Przemyśl", 49.7838, 22.7677, "pl", "Podkarpackie"),
        City("konin", "Konin", 52.2230, 18.2511, "pl", "Wielkopolskie"),
        City("augustow", "Augustów", 53.8432, 22.9798, "pl", "Podlaskie"),
        City("belchatow", "Bełchatów", 51.3688, 19.3567, "pl", "Łódzkie"),
        City("biala-podlaska", "Biała Podlaska", 52.0324, 23.1165, "pl", "Lubelskie"),
        City("bielsk-podlaski", "Bielsk Podlaski", 52.7651, 23.1865, "pl", "Podlaskie"),
        City("bilgoraj", "Biłgoraj", 50.5411, 22.7220, "pl", "Lubelskie"),
        City("bochnia", "Bochnia i okolice", 49.9691, 20.4303, "pl", "Małopolskie"),
        City("boleslawiec", "Bolesławiec i okolice", 51.2642, 15.5697, "pl", "Dolnośląskie"),
        City("braniewo", "Braniewo", 54.3797, 19.8196, "pl", "Warmińsko-mazurskie"),
        City("brzeg", "Brzeg", 50.8608, 17.4674, "pl", "Opolskie"),
        City("brzeg-dolny", "Brzeg Dolny i okolice", 51.2730, 16.7081, "pl", "Dolnośląskie"),
        City("busko-zdroj", "Busko-Zdrój i okolice", 50.4708, 20.7188, "pl", "Świętokrzyskie"),
        City("chelm", "Chełm", 51.1431, 23.4716, "pl", "Lubelskie"),
        City("chojnice", "Chojnice i okolice", 53.6955, 17.5570, "pl", "Pomorskie"),
        City("choszczno", "Choszczno i okolice", 53.1690, 15.4205, "pl", "Zachodniopomorskie"),
        City("ciechanow", "Ciechanów i okolice", 52.8814, 20.6200, "pl", "Mazowieckie"),
        City("czechowice-dziedzice", "Czechowice-Dziedzice i okolice", 49.9134, 19.0048, "pl", "Śląskie"),
        City("dabrowa-tarnowska", "Dąbrowa Tarnowska i okolice", 50.1746, 20.9863, "pl", "Małopolskie"),
        City("elk", "Ełk", 53.8282, 22.3647, "pl", "Warmińsko-mazurskie"),
        City("gizycko", "Giżycko i okolice", 54.0381, 21.7644, "pl", "Warmińsko-mazurskie"),
        City("glogow", "Głogów", 51.6636, 16.0845, "pl", "Dolnośląskie"),
        City("gniezno", "Gniezno i okolice", 52.5348, 17.5826, "pl", "Wielkopolskie"),
        City("goldap", "Gołdap", 54.3063, 22.3036, "pl", "Warmińsko-mazurskie"),
        City("grajewo", "Grajewo", 53.6473, 22.4554, "pl", "Podlaskie"),
        City("grudziadz", "Grudziądz i okolice", 53.4841, 18.7537, "pl", "Kujawsko-pomorskie"),
        City("hrubieszow", "Hrubieszów", 50.8050, 23.8925, "pl", "Lubelskie"),
        City("ilawa", "Iława i okolice", 53.5960, 19.5685, "pl", "Warmińsko-mazurskie"),
        City("inowroclaw", "Inowrocław i okolice", 52.7989, 18.2639, "pl", "Kujawsko-pomorskie"),
        City("jaroslaw", "Jarosław", 50.0162, 22.6778, "pl", "Podkarpackie"),
        City("jaslo", "Jasło i okolice", 49.7451, 21.4725, "pl", "Podkarpackie"),
        City("jastrzebie-zdroj", "Jastrzębie-Zdrój i okolice", 49.9554, 18.5748, "pl", "Śląskie"),
        City("jaworzno", "Jaworzno i okolice", 50.2053, 19.2750, "pl", "Śląskie"),
        City("kedzierzyn-kozle", "Kędzierzyn-Koźle", 50.3498, 18.2261, "pl", "Opolskie"),
        City("kepno", "Kępno i okolice", 51.2784, 17.9891, "pl", "Wielkopolskie"),
        City("klodzko", "Kłodzko i okolice", 50.4349, 16.6614, "pl", "Dolnośląskie"),
        City("kluczbork", "Kluczbork", 50.9728, 18.2182, "pl", "Opolskie"),
        City("kolobrzeg", "Kołobrzeg i okolice", 54.1756, 15.5834, "pl", "Zachodniopomorskie"),
        City("koscierzyna", "Kościerzyna i okolice", 54.1223, 17.9812, "pl", "Pomorskie"),
        City("krapkowice", "Krapkowice", 50.4751, 17.9654, "pl", "Opolskie"),
        City("krasnik", "Kraśnik i okolice", 50.9236, 22.2271, "pl", "Lubelskie"),
        City("krasnystaw", "Krasnystaw", 50.9846, 23.1742, "pl", "Lubelskie"),
        City("krosno", "Krosno", 49.6887, 21.7706, "pl", "Podkarpackie"),
        City("krotoszyn", "Krotoszyn i okolice", 51.6987, 17.4374, "pl", "Wielkopolskie"),
        City("krynica-zdroj", "Krynica-Zdrój i okolice", 49.4222, 20.9594, "pl", "Małopolskie"),
        City("kutno", "Kutno i okolice", 52.2306, 19.3641, "pl", "Łódzkie"),
        City("lapy", "Łapy", 52.9911, 22.8842, "pl", "Podlaskie"),
        City("leba", "Łeba", 54.7610, 17.5555, "pl", "Pomorskie"),
        City("legionowo", "Legionowo i okolice", 52.4015, 20.9266, "pl", "Mazowieckie"),
        City("leszno", "Leszno", 51.8403, 16.5749, "pl", "Wielkopolskie"),
        City("lidzbark-warminski", "Lidzbark Warmiński", 54.1259, 20.5795, "pl", "Warmińsko-mazurskie"),
        City("lipno", "Lipno i okolice", 52.8444, 19.1785, "pl", "Kujawsko-pomorskie"),
        City("lomza", "Łomża i okolice", 53.1781, 22.0593, "pl", "Podlaskie"),
        City("lubin", "Lubin", 51.4009, 16.2015, "pl", "Dolnośląskie"),
        City("lubliniec", "Lubliniec", 50.6690, 18.6844, "pl", "Śląskie"),
        City("lukow", "Łuków", 51.9290, 22.3796, "pl", "Lubelskie"),
        City("miechow", "Miechów i okolice", 50.3565, 20.0279, "pl", "Małopolskie"),
        City("miedzyrzec-podlaski", "Międzyrzec Podlaski", 51.9864, 22.7825, "pl", "Lubelskie"),
        City("miedzyrzecz", "Międzyrzecz", 52.4446, 15.5780, "pl", "Lubuskie"),
        City("miedzyzdroje", "Międzyzdroje", 53.9292, 14.4510, "pl", "Zachodniopomorskie"),
        City("mielec", "Mielec i okolice", 50.2871, 21.4239, "pl", "Podkarpackie"),
        City("mlawa", "Mława i okolice", 53.1128, 20.3841, "pl", "Mazowieckie"),
        City("morag", "Morąg", 53.9171, 19.9260, "pl", "Warmińsko-mazurskie"),
        City("myszkow", "Myszków", 50.5752, 19.3246, "pl", "Śląskie"),
        City("naklo-nad-notecia", "Nakło nad Notecią i okolice", 53.1421, 17.6018, "pl", "Kujawsko-pomorskie"),
        City("nowa-sol", "Nowa Sól", 51.8033, 15.7170, "pl", "Lubuskie"),
        City("nowy-targ", "Nowy Targ i okolice", 49.4778, 20.0323, "pl", "Małopolskie"),
        City("nowy-tomysl", "Nowy Tomyśl i okolice", 52.3195, 16.1284, "pl", "Wielkopolskie"),
        City("nysa", "Nysa i okolice", 50.4738, 17.3344, "pl", "Opolskie"),
        City("olawa", "Oława", 50.9466, 17.2926, "pl", "Dolnośląskie"),
        City("olecko", "Olecko", 54.0337, 22.5070, "pl", "Warmińsko-mazurskie"),
        City("olesnica", "Oleśnica", 51.2134, 17.3899, "pl", "Dolnośląskie"),
        City("olsztynek", "Olsztynek", 53.5837, 20.2847, "pl", "Warmińsko-mazurskie"),
        City("opoczno", "Opoczno i okolice", 51.3757, 20.2783, "pl", "Łódzkie"),
        City("ostrow-mazowiecka", "Ostrów Mazowiecka", 52.8025, 21.8951, "pl", "Mazowieckie"),
        City("ostrow-wielkopolski", "Ostrów Wielkopolski", 51.6550, 17.8069, "pl", "Wielkopolskie"),
        City("ostrowiec-swietokrzyski", "Ostrowiec Świętokrzyski i okolice", 50.9294, 21.3852, "pl", "Świętokrzyskie"),
        City("oswiecim", "Oświęcim i okolice", 50.0344, 19.2104, "pl", "Małopolskie"),
        City("otwock", "Otwock i okolice", 52.1058, 21.2613, "pl", "Mazowieckie"),
        City("pabianice", "Pabianice", 51.6645, 19.3547, "pl", "Łódzkie"),
        City("parczew", "Parczew", 51.6402, 22.9006, "pl", "Lubelskie"),
        City("pila", "Piła i okolice", 53.1514, 16.7378, "pl", "Wielkopolskie"),
        City("piotrkow-trybunalski", "Piotrków Trybunalski", 51.4055, 19.7032, "pl", "Łódzkie"),
        City("police", "Police i okolice", 53.5521, 14.5718, "pl", "Zachodniopomorskie"),
        City("polkowice", "Polkowice", 51.5039, 16.0726, "pl", "Dolnośląskie"),
        City("pruszkow", "Pruszków i okolice", 52.1707, 20.8121, "pl", "Mazowieckie"),
        City("przeworsk", "Przeworsk i okolice", 50.0591, 22.4941, "pl", "Podkarpackie"),
        City("pulawy", "Puławy i okolice", 51.4166, 21.9694, "pl", "Lubelskie"),
        City("pultusk", "Pułtusk i okolice", 52.7025, 21.0828, "pl", "Mazowieckie"),
        City("radomsko", "Radomsko", 51.0671, 19.4448, "pl", "Łódzkie"),
        City("rawicz", "Rawicz i okolice", 51.6095, 16.8585, "pl", "Wielkopolskie"),
        City("ruda-slaska", "Ruda Śląska i okolice", 50.2584, 18.8563, "pl", "Śląskie"),
        City("rypin", "Rypin", 53.0660, 19.4094, "pl", "Kujawsko-pomorskie"),
        City("sanok", "Sanok i okolice", 49.5557, 22.2056, "pl", "Podkarpackie"),
        City("siedlce", "Siedlce", 52.1677, 22.2901, "pl", "Mazowieckie"),
        City("sierpc", "Sierpc", 52.8568, 19.6691, "pl", "Mazowieckie"),
        City("skierniewice", "Skierniewice", 51.9549, 20.1584, "pl", "Łódzkie"),
        City("slawno", "Sławno i okolice", 54.3628, 16.6789, "pl", "Zachodniopomorskie"),
        City("slubice", "Słubice", 52.3509, 14.5607, "pl", "Lubuskie"),
        City("slupca", "Słupca i okolice", 52.2873, 17.8719, "pl", "Wielkopolskie"),
        City("sokolka", "Sokółka", 53.4072, 23.5023, "pl", "Podlaskie"),
        City("sokolow-podlaski", "Sokołów Podlaski i okolice", 52.4068, 22.2531, "pl", "Mazowieckie"),
        City("srem", "Śrem i okolice", 52.0887, 17.0151, "pl", "Wielkopolskie"),
        City("stalowa-wola", "Stalowa Wola i okolice", 50.5829, 22.0533, "pl", "Podkarpackie"),
        City("stara-blotnica", "Stara Błotnica", 51.5468, 20.9748, "pl", "Mazowieckie"),
        City("starachowice", "Starachowice i okolice", 51.0374, 21.0713, "pl", "Świętokrzyskie"),
        City("stargard", "Stargard i okolice", 53.3367, 15.0499, "pl", "Zachodniopomorskie"),
        City("strzelin", "Strzelin", 50.7816, 17.0648, "pl", "Dolnośląskie"),
        City("suwalki", "Suwałki", 54.1118, 22.9309, "pl", "Podlaskie"),
        City("swidnica", "Świdnica i okolice", 50.8438, 16.4886, "pl", "Dolnośląskie"),
        City("swidnik", "Świdnik i okolice", 51.2190, 22.6962, "pl", "Lubelskie"),
        City("swiebodzin", "Świebodzin", 52.2475, 15.5335, "pl", "Lubuskie"),
        City("szamotuly", "Szamotuły i okolice", 52.6120, 16.5779, "pl", "Wielkopolskie"),
        City("szczecinek", "Szczecinek", 53.7079, 16.6994, "pl", "Zachodniopomorskie"),
        City("szczytno", "Szczytno", 53.5626, 20.9875, "pl", "Warmińsko-mazurskie"),
        City("tczew", "Tczew i okolice", 54.0924, 18.7779, "pl", "Pomorskie"),
        City("tomaszow-lubelski", "Tomaszów Lubelski", 50.4477, 23.4162, "pl", "Lubelskie"),
        City("tomaszow-mazowiecki", "Tomaszów Mazowiecki", 51.5313, 20.0085, "pl", "Łódzkie"),
        City("turek", "Turek i okolice", 52.0155, 18.5006, "pl", "Wielkopolskie"),
        City("wadowice", "Wadowice i okolice", 49.8834, 19.4929, "pl", "Małopolskie"),
        City("wagrowiec", "Wągrowiec i okolice", 52.8084, 17.1996, "pl", "Wielkopolskie"),
        City("wejherowo", "Wejherowo i okolice", 54.6057, 18.2356, "pl", "Pomorskie"),
        City("wielen", "Wieleń", 52.8946, 16.1714, "pl", "Wielkopolskie"),
        City("wieliczka", "Wieliczka i okolice", 49.9874, 20.0647, "pl", "Małopolskie"),
        City("wielun", "Wieluń", 51.2210, 18.5696, "pl", "Łódzkie"),
        City("wlodawa", "Włodawa", 51.5500, 23.5500, "pl", "Lubelskie"),
        City("wloszczowa", "Włoszczowa", 50.8526, 19.9659, "pl", "Świętokrzyskie"),
        City("wolomin", "Wołomin i okolice", 52.3401, 21.2421, "pl", "Mazowieckie"),
        City("wysokie-mazowieckie", "Wysokie Mazowieckie", 52.9166, 22.5171, "pl", "Podlaskie"),
        City("wyszkow", "Wyszków i okolice", 52.5928, 21.4584, "pl", "Mazowieckie"),
        City("zakopane", "Zakopane", 49.2990, 19.9489, "pl", "Małopolskie"),
        City("zamosc", "Zamość", 50.7231, 23.2520, "pl", "Lubelskie"),
        City("zary", "Żary", 51.6420, 15.1373, "pl", "Lubuskie"),
        City("zawiercie", "Zawiercie", 50.4877, 19.4168, "pl", "Śląskie"),
        City("zdunska-wola", "Zduńska Wola i okolice", 51.5992, 18.9397, "pl", "Łódzkie"),
        City("zgierz", "Zgierz i okolice", 51.8556, 19.4062, "pl", "Łódzkie"),
        City("zgorzelec", "Zgorzelec i okolice", 51.1494, 15.0084, "pl", "Dolnośląskie"),
        City("zlocieniec", "Złocieniec i okolice", 53.5329, 16.0113, "pl", "Zachodniopomorskie"),
        City("zlotow", "Złotów i okolice", 53.3635, 17.0408, "pl", "Wielkopolskie"),
        City("zory", "Żory", 50.0452, 18.7006, "pl", "Śląskie"),
        City("zyrardow", "Żyrardów i okolice", 52.0488, 20.4460, "pl", "Mazowieckie"),
        City("zywiec", "Żywiec i okolice", 49.6853, 19.1924, "pl", "Śląskie"),
        // ── end Poland (generated)
        // ── United Kingdom (79 Flicks regions; English labels). Each carries the
        //    NATION it is picked under, matching what `/api/catalog` sends for it
        //    — this list is the fallback that renders before the catalog arrives,
        //    and a fallback that groups differently is a picker that rearranges
        //    itself under the reader. ─────────────────────────────────────────
        City("london", "London", 51.5074, -0.1278, "uk", "England"),
        City("manchester", "Manchester", 53.4808, -2.2426, "uk", "England"),
        City("norwich", "Norwich", 52.6309, 1.2974, "uk", "England"),
        City("aberdeenshire", "Aberdeenshire", 57.308, -2.3393, "uk", "Scotland"),
        City("antrim", "Antrim", 54.762, -6.0127, "uk", "Northern Ireland", "Antrim"),
        City("armagh", "Armagh", 54.4492, -6.398, "uk", "Northern Ireland"),
        City("ayrshire-and-arran", "Ayrshire and Arran", 55.5093, -4.581, "uk", "Scotland"),
        City("bedfordshire", "Bedfordshire", 52.0082, -0.4435, "uk", "England"),
        City("belfast", "Belfast", 54.5857, -5.9428, "uk", "Northern Ireland", "Antrim"),
        City("berkshire", "Berkshire", 51.4268, -0.9169, "uk", "England"),
        City("birmingham", "Birmingham", 52.4581, -1.9041, "uk", "England", "West Midlands"),
        City("bristol", "Bristol", 51.4659, -2.5805, "uk", "England"),
        City("buckinghamshire", "Buckinghamshire", 51.7582, -0.7609, "uk", "England"),
        City("cambridgeshire", "Cambridgeshire", 52.4301, -0.0137, "uk", "England"),
        City("cardiff", "Cardiff", 51.4892, -3.1939, "uk", "Wales", "Glamorgan"),
        City("central-scotland", "Central Scotland", 56.08, -3.8066, "uk", "Scotland"),
        City("cheshire", "Cheshire", 53.2917, -2.4966, "uk", "England"),
        City("clwyd", "Clwyd", 53.3083, -3.6072, "uk", "Wales"),
        City("cornwall", "Cornwall", 50.317, -4.9211, "uk", "England"),
        City("county-durham", "County Durham", 54.7289, -1.5139, "uk", "England"),
        City("cumbria", "Cumbria", 54.4593, -3.1119, "uk", "England"),
        City("derbyshire", "Derbyshire", 52.9886, -1.5219, "uk", "England"),
        City("devon", "Devon", 50.6651, -3.687, "uk", "England"),
        City("dorset", "Dorset", 50.7664, -2.1122, "uk", "England"),
        City("down", "Down", 54.4293, -5.9704, "uk", "Northern Ireland"),
        City("dudley", "Dudley", 52.497, -2.0918, "uk", "England", "West Midlands"),
        City("dumfries-and-galloway", "Dumfries and Galloway", 54.9881, -3.8232, "uk", "Scotland"),
        City("dunbartonshire-argyll-bute", "Dunbartonshire and Argyll & Bute", 55.7795, -4.9973, "uk", "Scotland"),
        City("dyfed", "Dyfed", 51.9892, -4.3329, "uk", "Wales"),
        City("east-sussex", "East Sussex", 50.8499, 0.2215, "uk", "England"),
        City("east-yorkshire", "East Yorkshire", 53.8685, -0.3985, "uk", "England"),
        City("edinburgh-and-lothians", "Edinburgh & Lothians", 55.9404, -3.2039, "uk", "Scotland"),
        City("essex", "Essex", 51.7621, 0.5901, "uk", "England"),
        City("fermanagh", "Fermanagh", 54.3499, -7.6316, "uk", "Northern Ireland"),
        City("fife", "Fife", 56.1287, -3.2424, "uk", "Scotland"),
        City("glamorgan", "Glamorgan", 51.6388, -3.7535, "uk", "Wales", "Glamorgan"),
        City("glasgow", "Glasgow", 55.8682, -4.2316, "uk", "Scotland"),
        City("gloucestershire", "Gloucestershire", 51.8387, -2.2712, "uk", "England"),
        City("guernsey", "Guernsey", 49.4446, -2.5695, "uk", "Crown Dependencies"),
        City("gwent", "Gwent", 51.6882, -3.0066, "uk", "Wales"),
        City("gwynedd", "Gwynedd", 53.0098, -4.153, "uk", "Wales"),
        City("hampshire", "Hampshire", 50.9234, -1.165, "uk", "England"),
        City("herefordshire", "Herefordshire", 52.031, -2.7825, "uk", "England"),
        City("hertfordshire", "Hertfordshire", 51.7791, -0.3102, "uk", "England"),
        City("highlands-and-islands", "Highlands and Islands", 58.086, -4.0855, "uk", "Scotland"),
        City("isle-of-man", "Isle of Man", 54.1578, -4.4775, "uk", "Crown Dependencies"),
        City("isle-of-wight", "Isle of Wight", 50.7118, -1.2248, "uk", "England"),
        City("jersey", "Jersey", 49.1839, -2.1144, "uk", "Crown Dependencies"),
        City("kent", "Kent", 51.2682, 0.8631, "uk", "England"),
        City("lanarkshire", "Lanarkshire", 55.7953, -4.0904, "uk", "Scotland"),
        City("lancashire", "Lancashire", 53.7367, -2.6625, "uk", "England"),
        City("leicestershire", "Leicestershire", 52.6656, -1.1514, "uk", "England"),
        City("lincolnshire", "Lincolnshire", 53.2194, -0.2916, "uk", "England"),
        City("londonderry", "Londonderry", 54.9949, -7.0636, "uk", "Northern Ireland"),
        City("liverpool", "Liverpool", 53.4084, -2.9916, "uk", "England"),
        City("north-yorkshire", "North Yorkshire", 54.2402, -1.156, "uk", "England"),
        City("northamptonshire", "Northamptonshire", 52.288, -0.8653, "uk", "England"),
        City("northumberland", "Northumberland", 55.2158, -1.7422, "uk", "England"),
        City("nottinghamshire", "Nottinghamshire", 53.0236, -1.15, "uk", "England"),
        City("oxfordshire", "Oxfordshire", 51.7572, -1.2545, "uk", "England"),
        City("powys", "Powys", 52.3806, -3.26, "uk", "Wales"),
        City("renfrewshire", "Renfrewshire", 55.9204, -4.5838, "uk", "Scotland"),
        City("roxburgh-ettrick-and-lauderdale", "Roxburgh, Ettrick and Lauderdale", 55.5183, -2.7969, "uk", "Scotland"),
        City("sandwell", "Sandwell", 52.5175, -1.9932, "uk", "England", "West Midlands"),
        City("shropshire", "Shropshire", 52.6813, -2.6215, "uk", "England"),
        City("somerset", "Somerset", 51.2159, -2.824, "uk", "England"),
        City("south-yorkshire", "South Yorkshire", 53.5141, -1.3109, "uk", "England"),
        City("staffordshire", "Staffordshire", 52.7942, -1.9887, "uk", "England"),
        City("suffolk", "Suffolk", 52.1492, 1.0262, "uk", "England"),
        City("surrey", "Surrey", 51.2269, -0.5354, "uk", "England"),
        City("tayside", "Tayside", 56.5061, -3.0128, "uk", "Scotland"),
        City("tyne-and-wear", "Tyne and Wear", 54.9749, -1.5397, "uk", "England"),
        City("tyrone", "Tyrone", 54.5255, -6.8664, "uk", "Northern Ireland"),
        City("warwickshire", "Warwickshire", 52.3602, -1.5034, "uk", "England"),
        City("west-sussex", "West Sussex", 50.9492, -0.3262, "uk", "England"),
        City("west-yorkshire", "West Yorkshire", 53.7878, -1.665, "uk", "England"),
        City("wiltshire", "Wiltshire", 51.2955, -1.8505, "uk", "England"),
        City("worcestershire", "Worcestershire", 52.1923, -2.2079, "uk", "England"),
        City("yorkshire", "Yorkshire", 53.4082, -1.4756, "uk", "England"),
    )

    /**
     * The subset of [all] belonging to [countryCode] (`"PL"`, `"GB"`), in [all]'s
     * hand-tuned order — the per-country roster the app scopes every picker and
     * the nearest-city pick to.
     */
    // The per-country queries below delegate to the [List]<[City]> extensions so
    // the app can run the SAME logic over the live catalog's cities (the fetched
    // or seeded list the ViewModel holds), with [all] as the fallback list here.
    fun citiesIn(countryCode: String): List<City> = all.inCountry(countryCode)

    fun sortedIn(countryCode: String): List<City> = all.sortedForPicker(countryCode)

    /** Ultimate fallback city — the first bundled city overall (Poznań). Only the
     *  compile-time default before the gate sets a real city; live flows pick a
     *  country-scoped default from the catalog. */
    val DEFAULT: City = all.first()

    fun defaultCityIn(countryCode: String): City = all.defaultCity(countryCode) ?: DEFAULT

    /**
     * Fold a Polish string to its diacritic-free, lower-case form for search
     * matching, so a query typed without Polish letters still finds the city
     * ("lodz" → "Łódź", "krakow" → "Kraków"). Unicode normalisation won't fold
     * ł/ą/ę/ń, so map the Polish letters explicitly.
     */
    fun searchFold(s: String): String {
        val out = StringBuilder(s.length)
        for (ch in s.lowercase()) {
            out.append(
                when (ch) {
                    'ą' -> 'a'; 'ć' -> 'c'; 'ę' -> 'e'; 'ł' -> 'l'; 'ń' -> 'n'
                    'ó' -> 'o'; 'ś' -> 's'; 'ź' -> 'z'; 'ż' -> 'z'; else -> ch
                }
            )
        }
        return out.toString()
    }

    /**
     * [sortedIn] narrowed to the cities whose folded name contains the folded
     * [query] — case- and diacritic-insensitive substring match. A blank query
     * yields that country's whole list (an empty search box shows everything).
     * Drives the search box on the manual city picker for [countryCode].
     */
    fun matching(query: String, countryCode: String): List<City> = all.matching(query, countryCode)

    /**
     * The city IN [countryCode] nearest to ([lat], [lon]), or null when the
     * nearest is still farther than 100 km — i.e. the user isn't near any city
     * that country serves, so the gate falls back to an explicit pick. Scoped to
     * the country so a Polish fix never resolves to a UK region, or vice versa.
     */
    fun nearestWithin100km(lat: Double, lon: Double, countryCode: String): City? =
        all.nearestWithin100km(lat, lon, countryCode)

    /**
     * Whether to offer switching from [chosenSlug] to a nearer supported city
     * for a device at ([lat], [lon]). Returns null — no offer — when the device
     * is out of range of every city, when the nearest is already the chosen one,
     * or when this exact `chosen→nearest` pair was the [lastPromptKey] last
     * offered (so we ask at most once per pair, but re-ask after the pair
     * changes — e.g. travelling back to a previously-declined city).
     */
    fun switchSuggestion(
        chosenSlug: String,
        lat: Double,
        lon: Double,
        lastPromptKey: String?,
        countryCode: String,
    ): CitySwitchSuggestion? = all.switchSuggestion(chosenSlug, lat, lon, lastPromptKey, countryCode)

    /** The stable de-dupe key for a `chosen→nearest` pair. One source of truth so
     *  the value [switchSuggestion] compares against is the same one the gate
     *  pre-records via [initialChoiceSuppressKey]. */
    fun switchPromptKey(chosenSlug: String, nearestSlug: String): String =
        "$chosenSlug→$nearestSlug"

    /**
     * The prompt key to pre-record when the user *deliberately* picks
     * [chosenSlug] at the first-launch gate while location placed them nearest
     * [nearestSlug]. Seeding it stops [switchSuggestion] from immediately
     * offering to switch back to the city they just chose against — the choice
     * was intentional. Returns null when there's nothing to suppress: no
     * location fix ([nearestSlug] is null), or the chosen city *is* the nearest.
     * Only this one pair is suppressed, so travelling elsewhere re-arms the prompt.
     */
    fun initialChoiceSuppressKey(chosenSlug: String, nearestSlug: String?): String? =
        nearestSlug?.takeIf { it != chosenSlug }?.let { switchPromptKey(chosenSlug, it) }
}

// ── Per-country queries over a catalog's city list ────────────────────────────
// `this` is the live catalog's cities — the fetched list, the bundled seed, or
// (as a fallback) [Cities.all]. Pure (no I/O) so they're unit-tested by passing a
// fixed list; the ViewModel calls them with the catalog's current cities.

/** The subset belonging to [countryCode] (`"pl"`, `"uk"`), in this list's order. */
fun List<City>.inCountry(countryCode: String): List<City> = filter { it.country == countryCode }

/** The country code of the city with [slug], or null when no such city. Lets a
 *  deep link that lands on another country's city (a showtimes-uk / showtimes-de
 *  link) switch the app to the right deployment before the repertoire loads. */
fun List<City>.countryOf(slug: String): String? = firstOrNull { it.slug == slug }?.country

/** [inCountry] ordered alphabetically under that country's collation (Polish for
 *  `pl`, so `Ł` sorts after `L`; English elsewhere) — what the pickers show. */
fun List<City>.sortedForPicker(countryCode: String): List<City> {
    val collator = java.text.Collator.getInstance(collationLocale(countryCode))
    return inCountry(countryCode).sortedWith(compareBy(collator) { it.name })
}

/** The regions [countryCode]'s cities are grouped under — US states, German
 *  Bundesländer, UK nations — in the catalog's own order, which is the order the
 *  web picker lists them in, so the two read alike. Empty for a country that does
 *  not group its cities (Poland, Spain), and that emptiness is what the picker
 *  reads as "show one flat list".
 *
 *  The TOP level, even where a region nests a `subregion` below it (see
 *  [secondLevelRows]): the UK's nation names every one of its cities' `region`,
 *  whether or not the county underneath went on to earn a third step of its
 *  own. */
fun List<City>.regionsIn(countryCode: String): List<String> =
    inCountry(countryCode).mapNotNull { it.region }.distinct()

/** An abstract group-level identifier — never the localized noun itself, so
 *  [searchLevelsFor] stays a pure JVM function the caller maps to its own
 *  `R.string` (`CitySearchLevel.labelRes` in `CityChoiceScreen.kt`). Mirrors
 *  `PICKER_GROUP_LABELS`' two entries per nesting country in landing.scala.html. */
enum class CitySearchLevel { UkRegion, UkSubregion, UsRegion, DeRegion }

/** [CitySearchLevel]s for a country that groups its cities, deepest first —
 *  the UK nests two ([UkRegion] then [UkSubregion]); the US and Germany nest
 *  one. A country absent here (Poland, Spain) is flat. */
private val countrySearchLevels: Map<String, Pair<CitySearchLevel, CitySearchLevel?>> = mapOf(
    "uk" to (CitySearchLevel.UkRegion to CitySearchLevel.UkSubregion),
    "us" to (CitySearchLevel.UsRegion to null),
    "de" to (CitySearchLevel.DeRegion to null),
)

/** The group level(s) a search from the CURRENT step can still reach, deepest
 *  first — mirrors `pickerSearchLevels()` in landing.scala.html exactly, so
 *  the web and the app phrase the search box's prompt identically: two at
 *  the root of a country that nests two deep (the UK), one once a region is
 *  picked or for a country with only one level (US/Germany), none once fully
 *  drilled into a subregion or for a flat country (Poland, Spain). */
fun searchLevelsFor(countryCode: String, region: String?, subregion: String?): List<CitySearchLevel> {
    val levels = countrySearchLevels[countryCode] ?: return emptyList()
    if (region == null) {
        return levels.second?.let { listOf(levels.first, it) } ?: listOf(levels.first)
    }
    if (subregion == null) {
        return levels.second?.let { listOf(it) } ?: emptyList()
    }
    return emptyList()
}

/** [matching] confined to one [region] — used by [matchingInSubregion] below.
 *  A null [region] leaves the country-wide list alone, so the same call serves
 *  both a grouped country's third screen and an ungrouped country's only one. */
fun List<City>.matchingInRegion(query: String, countryCode: String, region: String?): List<City> =
    matching(query, countryCode).let { cities ->
        if (region == null) cities else cities.filter { it.region == region }
    }

/** [matchingInRegion] narrowed to one [subregion] — the THIRD step, reached
 *  only where [secondLevelRows] holds a heading for it. */
fun List<City>.matchingInSubregion(query: String, countryCode: String, region: String, subregion: String): List<City> =
    matchingInRegion(query, countryCode, region).filter { it.subregion == subregion }

/** One row of a grouped picker level: a group heading (drills further) or a
 *  city that carries no group at this level, either because its top group
 *  collapsed onto it alone (Berlin, Hamburg; Delaware, Vermont) or because the
 *  country/region simply isn't split any further here. */
sealed class CityPickerRow {
    data class Heading(val label: String) : CityPickerRow()
    data class CityRow(val city: City) : CityPickerRow()
}

/** A stable `LazyColumn` item key — the heading's own label, or the city's
 *  slug, either way unique within one picker level. */
val CityPickerRow.rowKey: String
    get() = when (this) {
        is CityPickerRow.Heading -> "heading:$label"
        is CityPickerRow.CityRow -> "city:${city.slug}"
    }

/** One pass over [cities] — ALREADY in the catalog's own canonical picker
 *  order (`Catalog.scala` emits each country's cities in its picker tree's own
 *  traversal order; never re-sorted here) — interleaving each group's
 *  heading, emitted at its FIRST occurrence, with every city that carries no
 *  group at this level. Listing every heading before every direct city (the
 *  old shape) stranded a heading like "West Midlands" ahead of every direct
 *  city in its region, instead of beside "West Sussex" where it
 *  alphabetically belongs. */
private fun mergedPickerRows(cities: List<City>, groupField: (City) -> String?, query: String): List<CityPickerRow> {
    val q = Cities.searchFold(query.trim())
    val seen = mutableSetOf<String>()
    val rows = mutableListOf<CityPickerRow>()
    for (city in cities) {
        val group = groupField(city)
        if (group != null) {
            if (seen.add(group) && (q.isEmpty() || Cities.searchFold(group).contains(q))) {
                rows.add(CityPickerRow.Heading(group))
            }
        } else if (q.isEmpty() || Cities.searchFold(city.name).contains(q)) {
            rows.add(CityPickerRow.CityRow(city))
        }
    }
    return rows
}

/** The FIRST picker step for a grouped country: each region's heading,
 *  interleaved with any city whose top group collapsed onto it alone (Berlin,
 *  Hamburg; Delaware, Vermont) — narrowed to [query]. Empty for a country that
 *  does not group its cities (Poland, Spain). */
fun List<City>.topLevelRows(query: String, countryCode: String): List<CityPickerRow> =
    mergedPickerRows(inCountry(countryCode), groupField = { it.region }, query = query)

/** The SECOND picker step, within one [region]: each subregion's heading
 *  (reached only for the UK's West Midlands / Glamorgan / Antrim today)
 *  interleaved with that region's own directly-listed cities — narrowed to
 *  [query]. */
fun List<City>.secondLevelRows(query: String, countryCode: String, region: String): List<CityPickerRow> =
    mergedPickerRows(inCountry(countryCode).filter { it.region == region }, groupField = { it.subregion }, query = query)

/** One row of a FLATTENED, whole-country search result — see [searchRows].
 *  Unlike [CityPickerRow], a subregion here carries its parent [Subregion.region]:
 *  picking it from a flat list has to land two drill-steps deep at once, not
 *  just one, so the caller can't recover the region from its own current
 *  state the way [CityPickerRow]'s single-level callers can. */
sealed class CitySearchRow {
    abstract val label: String
    data class Region(override val label: String) : CitySearchRow()
    data class Subregion(override val label: String, val region: String) : CitySearchRow()
    data class CityRow(val city: City) : CitySearchRow() {
        override val label: String get() = city.name
    }
}

/** Every region, subregion and city in [countryCode] matching [query], merged
 *  into ONE alphabetical list — a query for "kent" must surface the Kent
 *  COUNTY heading even from the UK's top level, not only once England is
 *  already open. Empty for a blank [query]: [topLevelRows]/[secondLevelRows]
 *  above handle that case, and a country with no grouping (Poland, Spain) has
 *  nothing to flatten in the first place — its own [matching] already reaches
 *  every city. */
fun List<City>.searchRows(query: String, countryCode: String): List<CitySearchRow> {
    val q = Cities.searchFold(query.trim())
    if (q.isEmpty()) return emptyList()
    val seenRegion = mutableSetOf<String>()
    val seenSubregion = mutableSetOf<String>()
    val rows = mutableListOf<CitySearchRow>()
    for (city in inCountry(countryCode)) {
        val region = city.region
        if (region != null && seenRegion.add(region) && Cities.searchFold(region).contains(q)) {
            rows.add(CitySearchRow.Region(region))
        }
        val subregion = city.subregion
        if (region != null && subregion != null && seenSubregion.add("$region\u0000$subregion") &&
            Cities.searchFold(subregion).contains(q)
        ) {
            rows.add(CitySearchRow.Subregion(subregion, region))
        }
        if (Cities.searchFold(city.name).contains(q)) {
            rows.add(CitySearchRow.CityRow(city))
        }
    }
    val collator = java.text.Collator.getInstance(collationLocale(countryCode))
    return rows.sortedWith(compareBy(collator) { it.label })
}

/** A stable `LazyColumn` item key — unique within one flattened search result,
 *  same role as [rowKey] for [CityPickerRow]. A subregion's key includes its
 *  region since two different regions could in principle share a subregion
 *  name. */
val CitySearchRow.rowKey: String
    get() = when (this) {
        is CitySearchRow.Region -> "region:$label"
        is CitySearchRow.Subregion -> "subregion:$region:$label"
        is CitySearchRow.CityRow -> "city:${city.slug}"
    }

/** [sortedForPicker] narrowed to the cities matching [query] (case- and
 *  diacritic-insensitive substring). A blank query yields the whole country list. */
fun List<City>.matching(query: String, countryCode: String): List<City> {
    val q = Cities.searchFold(query.trim())
    val cities = sortedForPicker(countryCode)
    return if (q.isEmpty()) cities else cities.filter { Cities.searchFold(it.name).contains(q) }
}

/** The default city for [countryCode] — its first entry in this list, or null. */
fun List<City>.defaultCity(countryCode: String): City? = inCountry(countryCode).firstOrNull()

/** The city IN [countryCode] nearest ([lat], [lon]), or null beyond 100 km.
 *  Scoped so a Polish fix never resolves to a UK region, or vice versa. */
fun List<City>.nearestWithin100km(lat: Double, lon: Double, countryCode: String): City? =
    inCountry(countryCode).minByOrNull { haversineKm(lat, lon, it.lat, it.lon) }
        ?.takeIf { haversineKm(lat, lon, it.lat, it.lon) <= 100.0 }

/** The city nearest ([lat], [lon]) across EVERY country this list carries, or
 *  null beyond 100 km. Unlike [nearestWithin100km]'s country-scoped overload,
 *  this is deliberately unscoped — the manual picker's "use my location"
 *  button uses it to find the right city even when the country tab currently
 *  open isn't the one the device is actually in (a UK visitor who hasn't
 *  switched off the default Poland tab yet). */
fun List<City>.nearestWithin100km(lat: Double, lon: Double): City? =
    minByOrNull { haversineKm(lat, lon, it.lat, it.lon) }
        ?.takeIf { haversineKm(lat, lon, it.lat, it.lon) <= 100.0 }

/** The "you're nearer another city — switch?" suggestion, scoped to [countryCode];
 *  null when already nearest, out of range, or this pair was the [lastPromptKey]. */
fun List<City>.switchSuggestion(
    chosenSlug: String,
    lat: Double,
    lon: Double,
    lastPromptKey: String?,
    countryCode: String,
): CitySwitchSuggestion? {
    val nearest = nearestWithin100km(lat, lon, countryCode) ?: return null
    if (nearest.slug == chosenSlug) return null
    val key = Cities.switchPromptKey(chosenSlug, nearest.slug)
    if (key == lastPromptKey) return null
    return CitySwitchSuggestion(nearest, key)
}

/** Collation locale for a country's city names: Polish for `pl` (so the diacritic
 *  letters sort in their alphabet positions), English elsewhere. */
private fun collationLocale(countryCode: String): java.util.Locale =
    if (countryCode == "pl") java.util.Locale("pl", "PL") else java.util.Locale("en", "GB")

/** Great-circle distance in kilometres between two lat/lon points. */
private fun haversineKm(latitude1: Double, longitude1: Double, latitude2: Double, longitude2: Double): Double {
    val earthRadiusKm = 6371.0
    val deltaLatitude = Math.toRadians(latitude2 - latitude1)
    val deltaLongitude = Math.toRadians(longitude2 - longitude1)
    val squareHalfChord = sin(deltaLatitude / 2) * sin(deltaLatitude / 2) +
        cos(Math.toRadians(latitude1)) * cos(Math.toRadians(latitude2)) *
        sin(deltaLongitude / 2) * sin(deltaLongitude / 2)
    return earthRadiusKm * 2 * atan2(sqrt(squareHalfChord), sqrt(1 - squareHalfChord))
}
