#!/usr/bin/env python3
"""Generate common/src/main/scala/models/PolishPages.scala from data/pl/pages.json.

The Scala side of `build_pages.py`: every Polish venue's page, as code. The 41
major cities stay hand-declared `case object`s (their labels are hand-declined)
and read their venue lists from here; every other page is a generated row that
`City` turns into a `PolishPage`.

    python3 data/pl/scripts/generate_polish_pages.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
PAGES = ROOT / "data/pl/pages.json"
OUT = ROOT / "common/src/main/scala/models/PolishPages.scala"
# The apps' first-run city lists (before the live catalogue arrives) carry the
# same pages; their Polish block sits between these markers.
MOBILE = [
    (ROOT / "android/app/src/main/java/pl/kinowo/model/City.kt",
     lambda p: f'        City("{p["slug"]}", "{p["label"]}", {p["lat"]:.4f}, {p["lon"]:.4f}, "pl", "{p["voivodeship"]}"),'),
    (ROOT / "ios/Kinowo/Models/City.swift",
     lambda p: f'        City(slug: "{p["slug"]}", name: "{p["label"]}", lat: {p["lat"]:.4f}, lon: {p["lon"]:.4f}, '
               f'country: "pl", region: "{p["voivodeship"]}"),'),
]
MOBILE_START = "        // ── Poland: GENERATED by data/pl/scripts/generate_polish_pages.py — do not edit by hand.\n"
MOBILE_END = "        // ── end Poland (generated)\n"
CHUNK = 40


def q(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def seq(names):
    return "Seq(" + ", ".join(names) + ")"


def main():
    data = json.loads(PAGES.read_text(encoding="utf-8"))
    pages, retired = data["pages"], data["retired"]
    majors = [p for p in pages if p["kind"] == "major"]
    others = [p for p in pages if p["kind"] != "major"]

    rows = [f"    Row({q(p['slug'])}, {q(p['name'])}, {q(p['locative'])}, {p['lat']}, {p['lon']}, "
            f"{q(p['voivodeship'])}, multiTown = {'true' if p['kind'] == 'cluster' else 'false'}, "
            f"{seq(p['cinemas'])})" for p in others]
    chunks = [rows[i:i + CHUNK] for i in range(0, len(rows), CHUNK)]

    out = [
        "// GENERATED from data/pl/pages.json by data/pl/scripts/generate_polish_pages.py",
        "// — do NOT edit by hand. Re-cluster with data/pl/scripts/build_pages.py.",
        "package models",
        "",
        "/** Which Polish listing page every venue is on.",
        " *",
        " *  A major city lists only the venues inside it; every venue outside one is on",
        " *  a page of its own town (3+ venues) or of a cluster of small towns within a",
        " *  short drive, named after its biggest (see `data/pl/scripts/build_pages.py`).",
        " *  The 41 major cities are hand-declared in `City` and read [[majorCinemas]];",
        " *  every other page is a [[Row]] that `City.polishPages` builds. */",
        "private[models] object PolishPages {",
        "",
        "  /** A page that is not a major city. `multiTown` pages are named \"X i okolice\". */",
        "  final case class Row(slug: String, name: String, locative: String, lat: Double, lon: Double,",
        "                       voivodeship: String, multiTown: Boolean, cinemas: Seq[Cinema]) {",
        "    /** The page's name: the town, or \"<town> i okolice\" for a cluster of towns. */",
        "    def nominative: String = if (multiTown) s\"$name i okolice\" else name",
        "  }",
        "",
    ]
    for i, c in enumerate(chunks):
        out.append(f"  private def chunk{i}: Seq[Row] = Seq(")
        out.extend(r + "," for r in c)
        out.append("  )")
        out.append("")
    out.append("  val rows: Seq[Row] = " + " ++ ".join(f"chunk{i}" for i in range(len(chunks))))
    out.append("")
    out.append("  /** Each major city's own venues — the ones inside the city itself. */")
    out.append("  val majorCinemas: Map[String, Seq[Cinema]] = Map(")
    out.extend(f"    {q(p['slug'])} -> {seq(p['cinemas'])}," for p in majors)
    out.append("  )")
    out.append("")
    out.append("  /** The voivodeship each major city's page is grouped under in the picker. */")
    out.append("  val majorVoivodeship: Map[String, String] = Map(")
    out.extend(f"    {q(p['slug'])} -> {q(p['voivodeship'])}," for p in majors)
    out.append("  )")
    out.append("")
    out.append("  /** Pages that no longer exist → the page now holding their town. */")
    out.append("  val retired: Map[String, String] = Map(")
    out.extend(f"    {q(k)} -> {q(v)}," for k, v in sorted(retired.items()))
    out.append("  )")
    out.append("}")
    OUT.write_text("\n".join(out) + "\n", encoding="utf-8")

    for p in pages:
        p["label"] = f"{p['name']} i okolice" if p["kind"] == "cluster" else p["name"]
    for path, line in MOBILE:
        text = path.read_text(encoding="utf-8")
        head, rest = text.split(MOBILE_START, 1)
        _, tail = rest.split(MOBILE_END, 1)
        path.write_text(head + MOBILE_START + "".join(line(p) + "\n" for p in pages) + MOBILE_END + tail,
                        encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)}: {len(majors)} major cities, {len(others)} generated pages, "
          f"{len(retired)} retired slugs")


if __name__ == "__main__":
    main()
