package services.sharecards

import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.should.Matchers
import ShareCardTestKit.*

import java.io.ByteArrayInputStream
import java.nio.file.Files
import javax.imageio.ImageIO

class ShareCardPostersSpec extends AnyFlatSpec with Matchers {

  private val url = "https://cdn.example/poster-a.jpg"

  "The poster cache" should "fetch a new poster URL once, cache it slot-sized, and serve the next render from disk" in {
    val rig = new Rig
    rig.posters.load(Seq(url)).map { case (chosen, i) => (chosen, i.getWidth, i.getHeight) } shouldBe Some((url, 420, 630))
    rig.download.total shouldBe 1
    val cached = rig.store.posterPath(ShareCardPosters.key(url))
    Files.isRegularFile(cached) shouldBe true
    val slot = ImageIO.read(cached.toFile)
    (slot.getWidth, slot.getHeight) shouldBe ((420, 630))

    rig.posters.load(Seq(url)) shouldBe defined
    rig.download.total shouldBe 1                                  // no fetch for a cached poster
  }

  it should "render a card from a cached poster without any fetch" in {
    val rig = new Rig
    rig.posters.load(Seq(url))
    val other = rig.service.inputs(film(id = "fother"))           // same poster URL, a different film
    rig.service.render(other, Seq(ShareCardReason.NewFilm)) shouldBe ShareCardMetrics.Outcome.Rendered
    rig.download.total shouldBe 1
  }

  it should "use a cached fallback rather than refetch a primary that keeps failing" in {
    val primary = "https://multikino.example/403.jpg"
    val rig = new Rig(download = new CountingDownload(failing = Set(primary)))
    rig.posters.load(Seq(primary, url)).map(_._1) shouldBe Some(url)
    rig.posters.load(Seq(primary, url)).map(_._1) shouldBe Some(url)
    rig.download.calls.get(primary).get shouldBe 1
    rig.download.calls.get(url).get shouldBe 1
  }

  "A poster download" should "be abandoned at the byte cap instead of written out" in {
    val body = new Array[Byte](10 * 1024)
    PosterPipeline.copyCapped(new ByteArrayInputStream(body), maxBytes = 4096) shouldBe None
    val kept = PosterPipeline.copyCapped(new ByteArrayInputStream(body), maxBytes = 64 * 1024)
    kept.map(Files.size) shouldBe Some(10L * 1024)
    kept.foreach(Files.delete)
  }

  "The shrinker" should "decode with the bounded JDK reader when vips is not installed" in {
    val file = Files.write(Files.createTempFile("poster-", ".jpg"), posterJpeg)
    try new VipsPosterShrinker(binary = None).coverSlot(file).map(i => (i.getWidth, i.getHeight)) shouldBe Some((420, 630))
    finally Files.delete(file)
  }

  it should "refuse a real 8000×12000 progressive JPEG before decoding it, with the worker's memory untouched" in {
    val vips = VipsPosterShrinker.locate()
    assume(vips.isDefined, "vips is not installed")
    val dir  = Files.createTempDirectory("giant-poster-")
    val big  = dir.resolve("big.jpg")
    // Generated by vips itself: a 96-megapixel raster built in the JVM would be the very allocation
    // this path exists to avoid.
    def run(args: String*): Unit = new ProcessBuilder((vips.get +: args)*).inheritIO().start().waitFor() shouldBe 0
    run("gaussnoise", dir.resolve("n.v").toString, "8000", "12000")
    run("cast", dir.resolve("n.v").toString, dir.resolve("u.v").toString, "uchar")
    run("jpegsave", dir.resolve("u.v").toString, big.toString, "--interlace", "--Q", "80")
    val threads   = java.lang.management.ManagementFactory.getThreadMXBean.asInstanceOf[com.sun.management.ThreadMXBean]
    val thread    = Thread.currentThread().threadId()
    val before    = threads.getThreadAllocatedBytes(thread)
    new VipsPosterShrinker(binary = vips).coverSlot(big) shouldBe None
    val allocated = threads.getThreadAllocatedBytes(thread) - before
    info(f"JVM allocation for refusing the 8000×12000 progressive: ${allocated / 1e6}%.2f MB")
    allocated should be < (4L * 1024 * 1024)
    Files.list(dir).forEach(Files.delete(_)); Files.delete(dir)
  }
}
