// GENERATED from data/pl/pages.json by data/pl/scripts/generate_polish_pages.py
// — do NOT edit by hand. Re-cluster with data/pl/scripts/build_pages.py.
package models

/** Which Polish listing page every venue is on.
 *
 *  A major city lists only the venues inside it; every venue outside one is on
 *  a page of its own town (3+ venues) or of a cluster of small towns within a
 *  short drive, named after its biggest (see `data/pl/scripts/build_pages.py`).
 *  The 41 major cities are hand-declared in `City` and read [[majorCinemas]];
 *  every other page is a [[Row]] that `City.polishPages` builds. */
private[models] object PolishPages {

  /** A page that is not a major city. `multiTown` pages are named "X i okolice". */
  final case class Row(slug: String, name: String, locative: String, lat: Double, lon: Double,
                       voivodeship: String, multiTown: Boolean, cinemas: Seq[Cinema]) {
    /** The page's name: the town, or "<town> i okolice" for a cluster of towns. */
    def nominative: String = if (multiTown) s"$name i okolice" else name
  }

  private def chunk0: Seq[Row] = Seq(
    Row("augustow", "Augustów", "Augustowie", 53.8432, 22.9798, "Podlaskie", multiTown = false, Seq(KinoIskra)),
    Row("belchatow", "Bełchatów", "Bełchatowie", 51.3688, 19.3567, "Łódzkie", multiTown = false, Seq(HeliosBelchatow, KinoKulturaBelchatow)),
    Row("biala-podlaska", "Biała Podlaska", "Białej Podlaskiej", 52.0324, 23.1165, "Lubelskie", multiTown = false, Seq(CinemaCityBialaPodlaska)),
    Row("bielsk-podlaski", "Bielsk Podlaski", "Bielsku Podlaskim", 52.7651, 23.1865, "Podlaskie", multiTown = false, Seq(KinoBielsk)),
    Row("bilgoraj", "Biłgoraj", "Biłgoraju", 50.5411, 22.722, "Lubelskie", multiTown = false, Seq(KinoBCK)),
    Row("bochnia", "Bochnia", "Bochni", 49.9691, 20.4303, "Małopolskie", multiTown = true, Seq(KinoWazka, KinoPlaneta, KinoRegis, KinoKlaps)),
    Row("boleslawiec", "Bolesławiec", "Bolesławcu", 51.2642, 15.5697, "Dolnośląskie", multiTown = true, Seq(KinoAurum, KinoForumBoleslawiec, KinoKulturaChojnow)),
    Row("braniewo", "Braniewo", "Braniewie", 54.3797, 19.8196, "Warmińsko-mazurskie", multiTown = false, Seq(KinoBaszta)),
    Row("brzeg", "Brzeg", "Brzegu", 50.8608, 17.4674, "Opolskie", multiTown = false, Seq(KinoCentrumBrzeg)),
    Row("brzeg-dolny", "Brzeg Dolny", "Brzegu Dolnym", 51.273, 16.7081, "Dolnośląskie", multiTown = true, Seq(KinoAstra, KinoOdraBrzegDolny, KinoPoloniaTrzebnica, KinoCyfroweKino)),
    Row("busko-zdroj", "Busko-Zdrój", "Busku-Zdroju", 50.4708, 20.7188, "Świętokrzyskie", multiTown = true, Seq(KinoCK, KinoZdrojBusko, KinoGCK, KinoKadrStaszow)),
    Row("chelm", "Chełm", "Chełmie", 51.1431, 23.4716, "Lubelskie", multiTown = false, Seq(KinoZorzaChelm)),
    Row("chojnice", "Chojnice", "Chojnicach", 53.6955, 17.557, "Pomorskie", multiTown = true, Seq(KinoChDK, KinoUciechaCzluchow, KinoZaRogiemBrusy, KinoCKiSSepolno, KinoTucholskiOsrodekKultury)),
    Row("choszczno", "Choszczno", "Choszcznie", 53.169, 15.4205, "Zachodniopomorskie", multiTown = true, Seq(KinoPanorama, KinoChDKChoszczno, KinoDOKDrawno, KinoMGOKRecz)),
    Row("ciechanow", "Ciechanów", "Ciechanowie", 52.8814, 20.62, "Mazowieckie", multiTown = true, Seq(KinoKalejdoskop, KinoLydynia, KinoSwiatowidPrzasnysz)),
    Row("czechowice-dziedzice", "Czechowice-Dziedzice", "Czechowicach-Dziedzicach", 49.9134, 19.0048, "Śląskie", multiTown = true, Seq(KinoPckulKino, KinoSwitCzechowiceDziedzice, MultikinoCzechowiceDziedzice)),
    Row("dabrowa-tarnowska", "Dąbrowa Tarnowska", "Dąbrowie Tarnowskiej", 50.1746, 20.9863, "Małopolskie", multiTown = true, Seq(KinoSokolDabrowaTarnowska, KinoMCKRadlow, KinoCentrumLisiaGora)),
    Row("elk", "Ełk", "Ełku", 53.8282, 22.3647, "Warmińsko-mazurskie", multiTown = false, Seq(KinoECK, KinoPlanetCinemaElk)),
    Row("gizycko", "Giżycko", "Giżycku", 54.0381, 21.7644, "Warmińsko-mazurskie", multiTown = true, Seq(KinoGwiazdaKetrzyn, KinoZodiak, KinoNowaFalaGizycko)),
    Row("glogow", "Głogów", "Głogowie", 51.6636, 16.0845, "Dolnośląskie", multiTown = false, Seq(MultikinoGlogow, KinoMOKGlogow, TeatrGryphius)),
    Row("gniezno", "Gniezno", "Gnieźnie", 52.5348, 17.5826, "Wielkopolskie", multiTown = true, Seq(KinoTrojka, HeliosGniezno)),
    Row("goldap", "Gołdap", "Gołdapi", 54.3063, 22.3036, "Warmińsko-mazurskie", multiTown = false, Seq(KinoKulturaGoldap)),
    Row("grajewo", "Grajewo", "Grajewie", 53.6473, 22.4554, "Podlaskie", multiTown = false, Seq(KinoDomKulturyGrajewo)),
    Row("grudziadz", "Grudziądz", "Grudziądzu", 53.4841, 18.7537, "Kujawsko-pomorskie", multiTown = true, Seq(KinoRondo, KinoCKSwiecie, HeliosGrudziadz)),
    Row("hrubieszow", "Hrubieszów", "Hrubieszowie", 50.805, 23.8925, "Lubelskie", multiTown = false, Seq(KinoPlon)),
    Row("ilawa", "Iława", "Iławie", 53.596, 19.5685, "Warmińsko-mazurskie", multiTown = true, Seq(KinoteatrPasja, KinoPokoj, KinoteatrHarmonia)),
    Row("inowroclaw", "Inowrocław", "Inowrocławiu", 52.7989, 18.2639, "Kujawsko-pomorskie", multiTown = true, Seq(KinoKinomax, KinoManhattanJanikowo, KinoWawrzyn)),
    Row("jaroslaw", "Jarosław", "Jarosławiu", 50.0162, 22.6778, "Podkarpackie", multiTown = false, Seq(KinoIkar, KinoNaBiegunach)),
    Row("jaslo", "Jasło", "Jaśle", 49.7451, 21.4725, "Podkarpackie", multiTown = true, Seq(KinoSokolStrzyzow, KinoFarys, KinoKolory, KinoJDK)),
    Row("jastrzebie-zdroj", "Jastrzębie-Zdrój", "Jastrzębiu-Zdroju", 49.9554, 18.5748, "Śląskie", multiTown = true, Seq(KinoTeatrElektryczny, CinemaCityCieszyn, KinoBaltyk, KinoCentrum, KinoPegaz, KinoFeniks)),
    Row("jaworzno", "Jaworzno", "Jaworznie", 50.2053, 19.275, "Śląskie", multiTown = true, Seq(KinoAleKinoLibiaz, KinoZbyszekOlkusz, MultikinoJaworzno, KinoSztuka)),
    Row("kedzierzyn-kozle", "Kędzierzyn-Koźle", "Kędzierzynie-Koźlu", 50.3498, 18.2261, "Opolskie", multiTown = false, Seq(HeliosKedzierzynKozle, KinoChemik, KinoTwierdza)),
    Row("kepno", "Kępno", "Kępnie", 51.2784, 17.9891, "Wielkopolskie", multiTown = true, Seq(KinoPiastOstrzeszow, KinoSlonce, KinoSokolniaKepno)),
    Row("klodzko", "Kłodzko", "Kłodzku", 50.4349, 16.6614, "Dolnośląskie", multiTown = true, Seq(KinoMOKNowaRuda, MultikinoKlodzko)),
    Row("kluczbork", "Kluczbork", "Kluczborku", 50.9728, 18.2182, "Opolskie", multiTown = false, Seq(KinoBajkaKluczbork)),
    Row("kolobrzeg", "Kołobrzeg", "Kołobrzegu", 54.1756, 15.5834, "Zachodniopomorskie", multiTown = true, Seq(KinoCentrumBialogard, KinoGOK, KinoWybrzeze)),
    Row("koscierzyna", "Kościerzyna", "Kościerzynie", 54.1223, 17.9812, "Pomorskie", multiTown = true, Seq(KinoZaRogiemChmielno, KinoKCK, KinoRemus)),
    Row("krapkowice", "Krapkowice", "Krapkowicach", 50.4751, 17.9654, "Opolskie", multiTown = false, Seq(KinoKrapkowice)),
    Row("krasnik", "Kraśnik", "Kraśniku", 50.9236, 22.2271, "Lubelskie", multiTown = true, Seq(KinoMetalowiec, KinoCzyn, KinoOpolanka)),
    Row("krasnystaw", "Krasnystaw", "Krasnymstawie", 50.9846, 23.1742, "Lubelskie", multiTown = false, Seq(KinoMorskieOko)),
  )

  private def chunk1: Seq[Row] = Seq(
    Row("krosno", "Krosno", "Krośnie", 49.6887, 21.7706, "Podkarpackie", multiTown = false, Seq(HeliosKrosno, KinoArtKino)),
    Row("krotoszyn", "Krotoszyn", "Krotoszynie", 51.6987, 17.4374, "Wielkopolskie", multiTown = true, Seq(KinoEcho, KinoPrzedwiosnieKrotoszyn, KinoHel)),
    Row("krynica-zdroj", "Krynica-Zdrój", "Krynicy-Zdroju", 49.4222, 20.9594, "Małopolskie", multiTown = true, Seq(KinoJaworzyna, KinoMCKGrybow)),
    Row("kutno", "Kutno", "Kutnie", 52.2306, 19.3641, "Łódzkie", multiTown = true, Seq(KinoGornikLeczyca, KinoNoweKinoWarszawa, KinoKDK)),
    Row("lapy", "Łapy", "Łapach", 52.9911, 22.8842, "Podlaskie", multiTown = false, Seq(DomKulturyLapy)),
    Row("leba", "Łeba", "Łebie", 54.761, 17.5555, "Pomorskie", multiTown = false, Seq(KinoLeba)),
    Row("legionowo", "Legionowo", "Legionowie", 52.4015, 20.9266, "Mazowieckie", multiTown = true, Seq(HeliosLegionowo, KinoKasynoOficerskie, KinoNOKNasielsk)),
    Row("leszno", "Leszno", "Lesznie", 51.8403, 16.5749, "Wielkopolskie", multiTown = false, Seq(MultikinoLeszno, KinoTeatrMiejskiLeszno)),
    Row("lidzbark-warminski", "Lidzbark Warmiński", "Lidzbarku Warmińskim", 54.1259, 20.5795, "Warmińsko-mazurskie", multiTown = false, Seq(KinoIgnacy)),
    Row("lipno", "Lipno", "Lipnie", 52.8444, 19.1785, "Kujawsko-pomorskie", multiTown = true, Seq(KinoMiejskieCentrumKultury, KinoZdroj, KinoNawojka)),
    Row("lomza", "Łomża", "Łomży", 53.1781, 22.0593, "Podlaskie", multiTown = true, Seq(HeliosLomza, KinoJantar, KinoCKZambrow)),
    Row("lubin", "Lubin", "Lubinie", 51.4009, 16.2015, "Dolnośląskie", multiTown = false, Seq(HeliosLubin, KinoMuzaLubin)),
    Row("lubliniec", "Lubliniec", "Lublińcu", 50.669, 18.6844, "Śląskie", multiTown = false, Seq(KinoKarolinka)),
    Row("lukow", "Łuków", "Łukowie", 51.929, 22.3796, "Lubelskie", multiTown = false, Seq(KinoLukow)),
    Row("miechow", "Miechów", "Miechowie", 50.3565, 20.0279, "Małopolskie", multiTown = true, Seq(KinoRadosc, KinoGryf)),
    Row("miedzyrzec-podlaski", "Międzyrzec Podlaski", "Międzyrzecu Podlaskim", 51.9864, 22.7825, "Lubelskie", multiTown = false, Seq(KinoSlawa, KinoZaRogiemMiedzyrzec)),
    Row("miedzyrzecz", "Międzyrzecz", "Międzyrzeczu", 52.4446, 15.578, "Lubuskie", multiTown = false, Seq(KinoMOKMiedzyrzecz)),
    Row("miedzyzdroje", "Międzyzdroje", "Międzyzdrojach", 53.9292, 14.451, "Zachodniopomorskie", multiTown = false, Seq(KinoEva)),
    Row("mielec", "Mielec", "Mielcu", 50.2871, 21.4239, "Podkarpackie", multiTown = true, Seq(KinoJednosc, KinoSniezka, KinoPromien, MultikinoMielec)),
    Row("mlawa", "Mława", "Mławie", 53.1128, 20.3841, "Mazowieckie", multiTown = true, Seq(KinoKosmosMlawa, KinoApolloDzialdowo, KinoTon)),
    Row("morag", "Morąg", "Morągu", 53.9171, 19.926, "Warmińsko-mazurskie", multiTown = false, Seq(KinoNarie)),
    Row("myszkow", "Myszków", "Myszkowie", 50.5752, 19.3246, "Śląskie", multiTown = false, Seq(KinoMDKMyszkow)),
    Row("naklo-nad-notecia", "Nakło nad Notecią", "Nakle nad Notecią", 53.1421, 17.6018, "Kujawsko-pomorskie", multiTown = true, Seq(KinoRelaks, KinoPromienWiecbork)),
    Row("nowa-sol", "Nowa Sól", "Nowej Soli", 51.8033, 15.717, "Lubuskie", multiTown = false, Seq(KinoEuropa)),
    Row("nowy-targ", "Nowy Targ", "Nowym Targu", 49.4778, 20.0323, "Małopolskie", multiTown = true, Seq(KinoLubon, KinoSniezkaRabka, KinoStopiak)),
    Row("nowy-tomysl", "Nowy Tomyśl", "Nowym Tomyślu", 52.3195, 16.1284, "Wielkopolskie", multiTown = true, Seq(KinoWielkopolanin, KinoOpalenica, KinoNOKNowyTomysl, KinoMewaMiedzychod, KinoZaRogiemSiedlec)),
    Row("nysa", "Nysa", "Nysie", 50.4738, 17.3344, "Opolskie", multiTown = true, Seq(KinoDiana, KinoCinemaN)),
    Row("olawa", "Oława", "Oławie", 50.9466, 17.2926, "Dolnośląskie", multiTown = false, Seq(KinoOdraOlawa, GoKinoOlawa)),
    Row("olecko", "Olecko", "Olecku", 54.0337, 22.507, "Warmińsko-mazurskie", multiTown = false, Seq(KinoMazur)),
    Row("olesnica", "Oleśnica", "Oleśnicy", 51.2134, 17.3899, "Dolnośląskie", multiTown = false, Seq(KinoMOKiSOlesnica)),
    Row("olsztynek", "Olsztynek", "Olsztynku", 53.5837, 20.2847, "Warmińsko-mazurskie", multiTown = false, Seq(KinoGrunwald)),
    Row("opoczno", "Opoczno", "Opocznie", 51.3757, 20.2783, "Łódzkie", multiTown = true, Seq(KinoRCKDrzewica, KinoKoneckieCentrumKultury, KinoMDKOpoczno)),
    Row("ostrow-mazowiecka", "Ostrów Mazowiecka", "Ostrowi Mazowieckiej", 52.8025, 21.8951, "Mazowieckie", multiTown = false, Seq(KinoOstrovia)),
    Row("ostrow-wielkopolski", "Ostrów Wielkopolski", "Ostrowie Wielkopolskim", 51.655, 17.8069, "Wielkopolskie", multiTown = false, Seq(HeliosOstrowWlkp)),
    Row("ostrowiec-swietokrzyski", "Ostrowiec Świętokrzyski", "Ostrowcu Świętokrzyskim", 50.9294, 21.3852, "Świętokrzyskie", multiTown = true, Seq(KinoEtiuda, KinoOOK)),
    Row("oswiecim", "Oświęcim", "Oświęcimiu", 50.0344, 19.2104, "Małopolskie", multiTown = true, Seq(KinoWislaBrzeszcze, KinoNaszeKino, KinoPlanetCinema)),
    Row("otwock", "Otwock", "Otwocku", 52.1058, 21.2613, "Mazowieckie", multiTown = true, Seq(KinoUciecha, KinoOaza, KinoWilga)),
    Row("pabianice", "Pabianice", "Pabianicach", 51.6645, 19.3547, "Łódzkie", multiTown = false, Seq(KinoTomi, HeliosPabianice)),
    Row("parczew", "Parczew", "Parczewie", 51.6402, 22.9006, "Lubelskie", multiTown = false, Seq(KinoParczew)),
    Row("pila", "Piła", "Pile", 53.1514, 16.7378, "Wielkopolskie", multiTown = true, Seq(HeliosPila, KinoWCKWalcz, KinoOsiedlowe, KinoNotec, KinoSwiatowidCzarnkow)),
  )

  private def chunk2: Seq[Row] = Seq(
    Row("piotrkow-trybunalski", "Piotrków Trybunalski", "Piotrkowie Trybunalskim", 51.4055, 19.7032, "Łódzkie", multiTown = false, Seq(HeliosPiotrkow)),
    Row("police", "Police", "Policach", 53.5521, 14.5718, "Zachodniopomorskie", multiTown = true, Seq(KinoKawiarnia, KinoMOKPolice, KinoGryfinskiDomKultury)),
    Row("polkowice", "Polkowice", "Polkowicach", 51.5039, 16.0726, "Dolnośląskie", multiTown = false, Seq(KinoPCA)),
    Row("pruszkow", "Pruszków", "Pruszkowie", 52.1707, 20.8121, "Mazowieckie", multiTown = true, Seq(CinemaCityJanki, KinoGrojeckiOsrodekKultury, MultikinoPruszkow, KinoCKiSPruszkow, KinoBasn)),
    Row("przeworsk", "Przeworsk", "Przeworsku", 50.0591, 22.4941, "Podkarpackie", multiTown = true, Seq(KinoMCK, KinoWarszawa, KinoCKiBNowaSarzyna)),
    Row("pulawy", "Puławy", "Puławach", 51.4166, 21.9694, "Lubelskie", multiTown = true, Seq(KinoKozienickiDomKultury, KinoSwitZwolen, KinoSybilla, KinoRenesans)),
    Row("pultusk", "Pułtusk", "Pułtusku", 52.7025, 21.0828, "Mazowieckie", multiTown = true, Seq(KinoMDKMakow, KinoNarew)),
    Row("radomsko", "Radomsko", "Radomsku", 51.0671, 19.4448, "Łódzkie", multiTown = false, Seq(KinoMDK)),
    Row("rawicz", "Rawicz", "Rawiczu", 51.6095, 16.8585, "Wielkopolskie", multiTown = true, Seq(KinoPromienRawicz, KinoKrobia, KinoDKGora, KinoZaciszeWasosz)),
    Row("ruda-slaska", "Ruda Śląska", "Rudzie Śląskiej", 50.2584, 18.8563, "Śląskie", multiTown = true, Seq(CinemaCity, KinoPatria, KinoGrajfka, KinoFrajda, KinoZacisze, KinoScenaKultura)),
    Row("rypin", "Rypin", "Rypinie", 53.066, 19.4094, "Kujawsko-pomorskie", multiTown = false, Seq(KinoBaltykRypin)),
    Row("sanok", "Sanok", "Sanoku", 49.5557, 22.2056, "Podkarpackie", multiTown = true, Seq(KinoSokolBrzozow, KinoSDK, KinoOrzelUstrzyki, KinoBieszczadzkiDK)),
    Row("siedlce", "Siedlce", "Siedlcach", 52.1677, 22.2901, "Mazowieckie", multiTown = false, Seq(HeliosSiedlce, NoveKinoSiedlce)),
    Row("sierpc", "Sierpc", "Sierpcu", 52.8568, 19.6691, "Mazowieckie", multiTown = false, Seq(KinoJutrzenka)),
    Row("skierniewice", "Skierniewice", "Skierniewicach", 51.9549, 20.1584, "Łódzkie", multiTown = false, Seq(KinoPolonez, KinoCKiSSkierniewice)),
    Row("slawno", "Sławno", "Sławnie", 54.3628, 16.6789, "Zachodniopomorskie", multiTown = true, Seq(KinoBajkaDarlowo, KinoDK)),
    Row("slubice", "Słubice", "Słubicach", 52.3509, 14.5607, "Lubuskie", multiTown = false, Seq(KinoSmok)),
    Row("slupca", "Słupca", "Słupcy", 52.2873, 17.8719, "Wielkopolskie", multiTown = true, Seq(KinoZacheta, KinoSokolnia, KinoMok)),
    Row("sokolka", "Sokółka", "Sokółce", 53.4072, 23.5023, "Podlaskie", multiTown = false, Seq(KinoSokolSokolka)),
    Row("sokolow-podlaski", "Sokołów Podlaski", "Sokołowie Podlaskim", 52.4068, 22.2531, "Mazowieckie", multiTown = true, Seq(KinoSokolSokolowPodlaski, KinoKongres)),
    Row("srem", "Śrem", "Śremie", 52.0887, 17.0151, "Wielkopolskie", multiTown = true, Seq(KinoBasztaSroda, KinoteatrSlonko, KinoPodKopula)),
    Row("stalowa-wola", "Stalowa Wola", "Stalowej Woli", 50.5829, 22.0533, "Podkarpackie", multiTown = true, Seq(KinoStarowka, HeliosStalowaWola, KinoWrzos, KinoSokolNisko, KinoMetalowiecNowaDeba, KinoJOK)),
    Row("stara-blotnica", "Stara Błotnica", "Starej Błotnicy", 51.5468, 20.9748, "Mazowieckie", multiTown = false, Seq(KinoKsiazka)),
    Row("starachowice", "Starachowice", "Starachowicach", 51.0374, 21.0713, "Świętokrzyskie", multiTown = true, Seq(HeliosStarachowice, KinoCentrumSkarzyskoKamienna, KinoGornik, KinoKuznica, KinoCKiTIlza)),
    Row("stargard", "Stargard", "Stargardzie", 53.3367, 15.0499, "Zachodniopomorskie", multiTown = true, Seq(KinoPDK, KinoSCK)),
    Row("strzelin", "Strzelin", "Strzelinie", 50.7816, 17.0648, "Dolnośląskie", multiTown = false, Seq(KinoGrazyna)),
    Row("suwalki", "Suwałki", "Suwałkach", 54.1118, 22.9309, "Podlaskie", multiTown = false, Seq(KinoCinemaLumiereSuwalki)),
    Row("swidnica", "Świdnica", "Świdnicy", 50.8438, 16.4886, "Dolnośląskie", multiTown = true, Seq(KinoMOKiS, KinoSleza, KinoZbyszek, MultikinoSwidnica, KinoSCKStrzegom)),
    Row("swidnik", "Świdnik", "Świdniku", 51.219, 22.6962, "Lubelskie", multiTown = true, Seq(KinoLewart, KinoMilenium, KinoLotSwidnik)),
    Row("swiebodzin", "Świebodzin", "Świebodzinie", 52.2475, 15.5335, "Lubuskie", multiTown = false, Seq(KinoMaxKino, KinoSDKSwiebodzin)),
    Row("szamotuly", "Szamotuły", "Szamotułach", 52.612, 16.5779, "Wielkopolskie", multiTown = true, Seq(KinoHalszka, KinoteatrGwiazda, KinoCKPrzezmierowo)),
    Row("szczecinek", "Szczecinek", "Szczecinku", 53.7079, 16.6994, "Zachodniopomorskie", multiTown = false, Seq(KinoWolnoscSzczecinek)),
    Row("szczytno", "Szczytno", "Szczytnie", 53.5626, 20.9875, "Warmińsko-mazurskie", multiTown = false, Seq(KinoCinemaLumiere)),
    Row("tczew", "Tczew", "Tczewie", 54.0924, 18.7779, "Pomorskie", multiTown = true, Seq(KinoCKiSPruszczGdanski, HeliosTczew, KinoPowisle, KinoZulawskiOsrodekKultury, CinemaCityStarogard)),
    Row("tomaszow-lubelski", "Tomaszów Lubelski", "Tomaszowie Lubelskim", 50.4477, 23.4162, "Lubelskie", multiTown = false, Seq(KinoKadrTomaszowLubelski)),
    Row("tomaszow-mazowiecki", "Tomaszów Mazowiecki", "Tomaszowie Mazowieckim", 51.5313, 20.0085, "Łódzkie", multiTown = false, Seq(HeliosTomaszow, KinoMCKTkacz)),
    Row("turek", "Turek", "Turku", 52.0155, 18.5006, "Wielkopolskie", multiTown = true, Seq(KinoNadWarta, KinoTur)),
    Row("wadowice", "Wadowice", "Wadowicach", 49.8834, 19.4929, "Małopolskie", multiTown = true, Seq(KinoCentrumWadowice, KinoCKiF)),
    Row("wagrowiec", "Wągrowiec", "Wągrowcu", 52.8084, 17.1996, "Wielkopolskie", multiTown = true, Seq(KinoMewaBudzyn, KinoMDKWagrowiec, KinoMiescisko)),
    Row("wejherowo", "Wejherowo", "Wejherowie", 54.6057, 18.2356, "Pomorskie", multiTown = true, Seq(MultikinoRumia, KinoWCK, KinoZeglarz, KinoCKGniewino, KinoFregata)),
  )

  private def chunk3: Seq[Row] = Seq(
    Row("wielen", "Wieleń", "Wieleniu", 52.8946, 16.1714, "Wielkopolskie", multiTown = false, Seq(KinoZaRogiemWielen)),
    Row("wieliczka", "Wieliczka", "Wieliczce", 49.9874, 20.0647, "Małopolskie", multiTown = true, Seq(KinoMuzaMyslenice, KinoWielickaMediateka)),
    Row("wielun", "Wieluń", "Wieluniu", 51.221, 18.5696, "Łódzkie", multiTown = false, Seq(KinoSyrena)),
    Row("wlodawa", "Włodawa", "Włodawie", 51.55, 23.55, "Lubelskie", multiTown = false, Seq(KinoWDK)),
    Row("wloszczowa", "Włoszczowa", "Włoszczowie", 50.8526, 19.9659, "Świętokrzyskie", multiTown = false, Seq(KinoMuzaWloszczowa)),
    Row("wolomin", "Wołomin", "Wołominie", 52.3401, 21.2421, "Mazowieckie", multiTown = true, Seq(HeliosWolomin, KinoKulturaWolomin, KinoTeatrKurtyna)),
    Row("wysokie-mazowieckie", "Wysokie Mazowieckie", "Wysokiem Mazowieckiem", 52.9166, 22.5171, "Podlaskie", multiTown = false, Seq(KinoWars)),
    Row("wyszkow", "Wyszków", "Wyszkowie", 52.5928, 21.4584, "Mazowieckie", multiTown = true, Seq(KinoDobrychFilmow, KinoMiGOK)),
    Row("zakopane", "Zakopane", "Zakopanem", 49.299, 19.9489, "Małopolskie", multiTown = false, Seq(KinoSokolZakopane, KinoGiewont, KinoMiejsce)),
    Row("zamosc", "Zamość", "Zamościu", 50.7231, 23.252, "Lubelskie", multiTown = false, Seq(KinoStylowy)),
    Row("zary", "Żary", "Żarach", 51.642, 15.1373, "Lubuskie", multiTown = false, Seq(KinoPionierZary)),
    Row("zawiercie", "Zawiercie", "Zawierciu", 50.4877, 19.4168, "Śląskie", multiTown = false, Seq(KinoMOKCentrum, KinoPlanetCinemaZawiercie)),
    Row("zdunska-wola", "Zduńska Wola", "Zduńskiej Woli", 51.5992, 18.9397, "Łódzkie", multiTown = true, Seq(KinoTeatrSieradz, KinoWRatuszu)),
    Row("zgierz", "Zgierz", "Zgierzu", 51.8556, 19.4062, "Łódzkie", multiTown = true, Seq(KinoSpojnia, KinoStaryMlyn, KinoMOKGlowno)),
    Row("zgorzelec", "Zgorzelec", "Zgorzelcu", 51.1494, 15.0084, "Dolnośląskie", multiTown = true, Seq(KinoWawel, MultikinoZgorzelec, KinoKadrBogatynia)),
    Row("zlocieniec", "Złocieniec", "Złocieńcu", 53.5329, 16.0113, "Zachodniopomorskie", multiTown = true, Seq(KinoGoplana, KinoMewaZlocieniec, KinoOKDrawsko)),
    Row("zlotow", "Złotów", "Złotowie", 53.3635, 17.0408, "Wielkopolskie", multiTown = true, Seq(KinoRodlo, KinoOKJastrowie, KinoGOKLipka)),
    Row("zory", "Żory", "Żorach", 50.0452, 18.7006, "Śląskie", multiTown = false, Seq(HeliosZory, KinoNaStarowce)),
    Row("zyrardow", "Żyrardów", "Żyrardowie", 52.0488, 20.446, "Mazowieckie", multiTown = true, Seq(KinoGrodziskieCentrumKultury, KinoCentrumKulturyBlonie, KinoODEON, KinoLen, KinoRomaRawa, KinoFenix)),
    Row("zywiec", "Żywiec", "Żywcu", 49.6853, 19.1924, "Śląskie", multiTown = true, Seq(KinoJanosik, KinoPromyk)),
  )

  val rows: Seq[Row] = chunk0 ++ chunk1 ++ chunk2 ++ chunk3

  /** Each major city's own venues — the ones inside the city itself. */
  val majorCinemas: Map[String, Seq[Cinema]] = Map(
    "poznan" -> Seq(KinoApollo, KinoBulgarska, CharlieMonroe, Helios, CinemaCityKinepolis, KinoMuza, Multikino, KinoPalacowe, CinemaCityPoznanPlaza, Rialto),
    "wroclaw" -> Seq(CinemaCityWroclavia, CinemaCityKorona, MultikinoPasazGrunwaldzki, HeliosMagnolia, HeliosAlejaBielany, KinoNoweHoryzonty, DolnoslaskieCentrumFilmowe, KinoDyskusyjnyKlubFilmowyPolitechnika, KinoNowyPafawag),
    "warszawa" -> Seq(CinemaCityArkadia, CinemaCityBemowo, CinemaCityGaleriaPolnocna, CinemaCityMokotow, CinemaCityPromenada, CinemaCitySadyba, MultikinoZloteTarasy, MultikinoMlociny, MultikinoReduta, MultikinoTargowek, MultikinoWolaPark, HeliosBlueCity, KinoMuranow, KinoLuna, KinoElektronik, KinoIluzjon, KinoGram, KinoKultura, KinoAmondo, KinoNaBoku, KinoGlebocka66, Kinomuzeum, KinoSwit, KinoKepa, StacjaFalenica, SluzewskiDomKultury, KinoAtlantic, Kinoteka, Ujazdowski, KinoCytadela, KinoWisla, AdaKinoStudyjne, KinoMazowieckiTeatrMuzycznyImJanaKiepuryKinoPraha, KinoAlternatywy, KinoWKadrze, KinoDomSztukiUrsynow, KinoTerminalKultury, KinoBielanskiOsrodekKultury, KinoWawerskaStrefaKultury),
    "krakow" -> Seq(CinemaCityBonarka, CinemaCityKazimierz, CinemaCityZakopianka, MultikinoKrakow, KinoMikro, MikroBronowice, KinoSfinks, KinoPodBaranami, KinoKijow, KinoKika, KinoAgrafka, KinoParadox),
    "lodz" -> Seq(CinemaCityManufaktura, MultikinoLodz, HeliosLodz, KinoCharlie, KinematografLodz, Nckf, KinoTatry),
    "katowice" -> Seq(CinemaCityPunkt44, CinemaCitySilesia, MultikinoKatowice, HeliosKatowice, KinoKosmos, KinoSwiatowid, KinoteatrRialto),
    "szczecin" -> Seq(HeliosSzczecin, MultikinoSzczecin, KinoPionier, HeliosOutletPark, KinoZamekSzczecin),
    "bialystok" -> Seq(HeliosAlfa, HeliosBiala, HeliosJurowiecka, KinoForum),
    "trojmiasto" -> Seq(MultikinoGdansk, HeliosMetropolia, HeliosForum, HeliosRiviera, KinoSpektrum, KinoKameralne, KinoIkm, KinoMuzeumGdansk, KinoZak, KinoPort, Cinema1Gdansk, GdynskieCentrumFilmowe, KinoNaSzekspirowskim, TeatrBoto, TeatrAtelier),
    "bydgoszcz" -> Seq(CinemaCityBydgoszcz, MultikinoBydgoszcz, HeliosBydgoszcz, KinoOrzel),
    "lublin" -> Seq(CinemaCityLublinFelicity, CinemaCityLublinPlaza, MultikinoLublin, KinoBajka, KinoCkLublin, KinoChatkaZaka),
    "czestochowa" -> Seq(CinemaCityCzestochowaJurajska, CinemaCityCzestochowaWolnosc, OkfIluzja, KinoDKFRumcajs),
    "radom" -> Seq(HeliosRadom, MultikinoRadom, McswElektrowniaCinema),
    "sosnowiec" -> Seq(HeliosSosnowiec, CinemaCitySosnowiec),
    "torun" -> Seq(CinemaCityTorunCzerwonaDroga, CinemaCityTorunPlaza, KinoCentrumCsw, Kino1410),
    "kielce" -> Seq(HeliosKielce, MultikinoKielce, KinoFenomen, KinoMoskwa),
    "rzeszow" -> Seq(HeliosRzeszow, MultikinoRzeszow, KinoZorza, KinoZaRogiemCafe),
    "gliwice" -> Seq(CinemaCityGliwice, KinoAmok),
    "zabrze" -> Seq(MultikinoZabrze, KinoRoma, KinoPlanetCinemaZabrze),
    "olsztyn" -> Seq(HeliosOlsztyn, MultikinoOlsztyn, KinoAwangarda2),
    "bielsko-biala" -> Seq(HeliosBielskoBiala, CinemaCityBielskoBiala, KinoKreska),
    "opole" -> Seq(HeliosOpoleKarolinka, HeliosOpoleSolaris, KinoMeduza, KinoStudio),
    "rybnik" -> Seq(MultikinoRybnik, CinemaCityRybnik, KinoTeatrZiemiRybnickiej),
    "gorzow-wielkopolski" -> Seq(HeliosGorzow, MultikinoGorzow, Kino60Krzesel),
    "elblag" -> Seq(MultikinoElblag, CinemaCityElblag, KinoSwiatowidElblag),
    "koszalin" -> Seq(HeliosKoszalin, MultikinoKoszalin, KinoKryterium),
    "kalisz" -> Seq(HeliosKalisz, MultikinoKalisz, KinoCentrum3D),
    "zielona-gora" -> Seq(CinemaCityZielonaGora),
    "tychy" -> Seq(MultikinoTychy),
    "walbrzych" -> Seq(CinemaCityWalbrzych, KinoApolloWalbrzych),
    "tarnow" -> Seq(MultikinoTarnow, KinoMillenium, KinoMarzenie),
    "wloclawek" -> Seq(MultikinoWloclawek),
    "legnica" -> Seq(HeliosLegnica, KinoPiast),
    "plock" -> Seq(HeliosPlock, KinoPrzedwiosnie, KinoZaRogiem),
    "bytom" -> Seq(CinemaCityBytom, KinoBCKBytom),
    "dabrowa-gornicza" -> Seq(HeliosDabrowaGornicza, KinoKadr),
    "nowy-sacz" -> Seq(HeliosNowySacz, KinoSokol),
    "slupsk" -> Seq(MultikinoSlupsk, KinoRejs),
    "jelenia-gora" -> Seq(HeliosJeleniaGora, KinoLot),
    "przemysl" -> Seq(HeliosPrzemysl, KinoCentrum3DPrzemysl),
    "konin" -> Seq(HeliosKonin, KinoOskard, KinoStudyjneCentrum),
  )

  /** The voivodeship each major city's page is grouped under in the picker. */
  val majorVoivodeship: Map[String, String] = Map(
    "poznan" -> "Wielkopolskie",
    "wroclaw" -> "Dolnośląskie",
    "warszawa" -> "Mazowieckie",
    "krakow" -> "Małopolskie",
    "lodz" -> "Łódzkie",
    "katowice" -> "Śląskie",
    "szczecin" -> "Zachodniopomorskie",
    "bialystok" -> "Podlaskie",
    "trojmiasto" -> "Pomorskie",
    "bydgoszcz" -> "Kujawsko-pomorskie",
    "lublin" -> "Lubelskie",
    "czestochowa" -> "Śląskie",
    "radom" -> "Mazowieckie",
    "sosnowiec" -> "Śląskie",
    "torun" -> "Kujawsko-pomorskie",
    "kielce" -> "Świętokrzyskie",
    "rzeszow" -> "Podkarpackie",
    "gliwice" -> "Śląskie",
    "zabrze" -> "Śląskie",
    "olsztyn" -> "Warmińsko-mazurskie",
    "bielsko-biala" -> "Śląskie",
    "opole" -> "Opolskie",
    "rybnik" -> "Śląskie",
    "gorzow-wielkopolski" -> "Lubuskie",
    "elblag" -> "Warmińsko-mazurskie",
    "koszalin" -> "Zachodniopomorskie",
    "kalisz" -> "Wielkopolskie",
    "zielona-gora" -> "Lubuskie",
    "tychy" -> "Śląskie",
    "walbrzych" -> "Dolnośląskie",
    "tarnow" -> "Małopolskie",
    "wloclawek" -> "Kujawsko-pomorskie",
    "legnica" -> "Dolnośląskie",
    "plock" -> "Mazowieckie",
    "bytom" -> "Śląskie",
    "dabrowa-gornicza" -> "Śląskie",
    "nowy-sacz" -> "Małopolskie",
    "slupsk" -> "Pomorskie",
    "jelenia-gora" -> "Dolnośląskie",
    "przemysl" -> "Podkarpackie",
    "konin" -> "Wielkopolskie",
  )

  /** Pages that no longer exist → the page now holding their town. */
  val retired: Map[String, String] = Map(
    "ketrzyn" -> "gizycko",
    "starogard-gdanski" -> "tczew",
  )
}
