// GENERATED from data/uk/venues.json by data/uk/scripts/generate_towns.py
// — do NOT edit by hand. The town each of 842 UK venues sits in, harvested
// from Flicks. Regenerate with `python3 data/uk/scripts/harvest_towns.py` followed by
// `python3 data/uk/scripts/generate_towns.py`; see data/uk/README.md.
package models

/** The town each UK venue sits in — the roster fact every other country
 *  carries in its generated roster and the UK, whose venues are hand-written,
 *  has to keep beside it. Read by [[UkCity.extraPlaces]], so that
 *  `/aberdeenshire/` names Peterhead and Banchory rather than only itself. */
private[models] object UkVenueTowns {

  private def chunk0: Seq[(String, String)] = Seq(
    ("ARC Stockton-on-Tees", "Stockton-on-Tees"),
    ("Abbey Cinema Abingdon", "Abingdon"),
    ("Abbeygate Bury St Edmunds", "Bury St Edmunds"),
    ("Aberystwyth Arts Centre", "Aberystwyth"),
    ("Act One Cinema Acton", "London"),
    ("Adam Smith Theatre Kirkcaldy", "Kirkcaldy"),
    ("Aldeburgh Cinema", "Aldeburgh"),
    ("Alexandra Newton Abbot", "Newton Abbot"),
    ("An Lanntair Arts Centre Stornoway, Isle of Lewis", "Stornoway"),
    ("Arc Cinema Beeston", "Beeston"),
    ("Arc Cinema Blackpool", "Blackpool"),
    ("Arc Cinema Daventry", "Daventry"),
    ("Arc Cinema Great Yarmouth", "Great Yarmouth"),
    ("Arc Cinema Peterhead", "Peterhead"),
    ("Arc Cinema Preston", "Preston"),
    ("Arc Cinema Rotherham", "Rotherham"),
    ("Arc Cinema at The Byron, Hucknall", "Hucknall"),
    ("ArtHouse Crouch End", "London"),
    ("Artrix Bromsgrove", "Bromsgrove"),
    ("Arts Centre Stamford", "Stamford"),
    ("Arts Cinema (John Clare Theatre) Peterborough", "Peterborough"),
    ("Arts Picturehouse Cambridge", "Cambridge"),
    ("Assembly Rooms Ludlow", "Ludlow"),
    ("Astoria Cinema Ayr", "Ayr"),
    ("Atrium East Grinstead", "East Grinstead"),
    ("BEAM (Hertford Theatre)", "Hertford"),
    ("BFI London IMAX", "London"),
    ("BFI London Southbank", "London"),
    ("Baker Street Cinema Abergavenny", "Abergavenny"),
    ("Baldock Arts & Heritage Centre", "Baldock"),
    ("Barbican London", "London"),
    ("Barn Cinema, Dartington Art Centre", "Totnes"),
    ("Beau Séjour Leisure Centre, ​Guernsey", "Guernsey"),
    ("Belmont Filmhouse", "Aberdeen"),
    ("Birks Aberfeldy", "Aberfeldy"),
    ("Brewery Arts Centre Kendal", "Kendal"),
    ("Broadway Cinema Nottingham", "Nottingham"),
    ("Broadway Cinema Villa Marina", "Douglas"),
    ("Broadway Letchworth", "Letchworth"),
    ("Brunswick Moviebowl Londonderry", "Londonderry"),
    ("Buxton Cinema, Pavilion Arts Centre", "Buxton"),
    ("Campbeltown Picture House", "Campbeltown"),
    ("Cannock Cinema", "Cannock"),
    ("Capitol Horsham", "Horsham"),
    ("Carlton Cinema Westgate-on-Sea", "Westgate-on-Sea"),
    ("Castle Cinema Hackney", "London"),
    ("Castle Sidcup", "Sidcup"),
    ("Castlemorton Cinema (Morton Majestic)", "Malvern"),
    ("Cell B Blaenau Ffestiniog", "Blaenau Ffestiniog"),
    ("Central Cinema Barnstaple", "Barnstaple"),
    ("Central Cinema Fakenham", "Fakenham"),
    ("Century Cinema Clacton", "Clacton-on-Sea"),
    ("Chalmers Alloa Cinema", "CLACKMANNANSHIRE"),
    ("Chalmers Filmhouse Arbroath", "Arbroath"),
    ("Chapter Cardiff", "Cardiff"),
    ("Chichester Cinema at New Park", "Chichester"),
    ("Chiddingfold Village Hall Cinema", "Godalming"),
    ("Chiswick Cinema", "London"),
    ("Cinebowl Uttoxeter", "Uttoxeter"),
    ("Cinema Saltcoats (Premier Leisure)", "Saltcoats"),
    ("Cinemac Macclesfield", "Macclesfield"),
    ("Cinemarsh, The Marsh Academy", "New Romney"),
    ("Cineworld (Queens Link) Aberdeen", "Aberdeen"),
    ("Cineworld (Shaw Ridge) Swindon", "Swindon"),
    ("Cineworld (Silverburn) Glasgow", "Glasgow"),
    ("Cineworld (Spytty Park) Newport", "Newport"),
    ("Cineworld (Union Square) Aberdeen", "Aberdeen"),
    ("Cineworld Aldershot", "Aldershot"),
    ("Cineworld Ashford", "Ashford"),
    ("Cineworld Ashton-under-Lyne", "Ashton-under-Lyne"),
    ("Cineworld Barnsley", "Barnsley"),
    ("Cineworld Basildon", "Basildon"),
    ("Cineworld Belfast", "Belfast"),
    ("Cineworld Bexleyheath", "Bexleyheath"),
    ("Cineworld Boldon Tyne & Wear", "Boldon Tyne & Wear"),
    ("Cineworld Bolton", "Bolton"),
    ("Cineworld Bracknell", "Bracknell"),
    ("Cineworld Bradford", "Bradford"),
    ("Cineworld Braintree", "Braintree"),
    ("Cineworld Brighton", "Brighton"),
    ("Cineworld Broad Street, Birmingham", "Birmingham"),
    ("Cineworld Broughton", "Broughton"),
    ("Cineworld Burton-on-Trent", "Burton-on-Trent"),
    ("Cineworld Bury St Edmunds", "Bury St Edmunds"),
    ("Cineworld Cardiff", "Cardiff"),
    ("Cineworld Cheltenham", "Cheltenham"),
    ("Cineworld Chesterfield", "Chesterfield"),
    ("Cineworld Chichester", "Chichester"),
    ("Cineworld Crawley", "Crawley"),
    ("Cineworld Dalton Park (Murton County)", "Murton"),
    ("Cineworld Didcot", "Didcot"),
    ("Cineworld Didsbury", "Manchester"),
    ("Cineworld Dover", "Dover"),
    ("Cineworld Dundee", "Dundee"),
    ("Cineworld Eastbourne", "Eastbourne"),
    ("Cineworld Edinburgh", "Edinburgh"),
    ("Cineworld Ely", "Ely"),
    ("Cineworld Enfield", "London"),
    ("Cineworld Falkirk", "Falkirk"),
    ("Cineworld Feltham", "London"),
    ("Cineworld Gloucester Quays", "Gloucester"),
    ("Cineworld Harlow (Harvey Centre)", "Harlow"),
    ("Cineworld Harlow (Queensgate)", "Harlow"),
    ("Cineworld Haverhill", "Haverhill"),
    ("Cineworld Hemel Hempstead", "Hemel Hempstead"),
    ("Cineworld High Wycombe", "High Wycombe"),
    ("Cineworld Hinckley", "Hinckley"),
    ("Cineworld Hull", "Hull"),
    ("Cineworld Huntingdon", "Huntingdon"),
    ("Cineworld Ilford", "London"),
    ("Cineworld Ipswich", "Ipswich"),
    ("Cineworld Leeds", "Leeds"),
    ("Cineworld Leicester Square", "London"),
    ("Cineworld Llandudno", "Llandudno"),
    ("Cineworld London Hounslow", "London"),
    ("Cineworld Luton", "Luton"),
    ("Cineworld Milton Keynes", "Milton Keynes"),
    ("Cineworld NEC Birmingham", "Birmingham"),
    ("Cineworld Newcastle", "Newcastle"),
    ("Cineworld Newport, Isle of Wight", "Newport Isle of Wight"),
    ("Cineworld Plymouth", "Plymouth"),
    ("Cineworld Rochester", "Rochester"),
    ("Cineworld Rugby", "Rugby"),
    ("Cineworld Rushden Lakes", "Rushden"),
    ("Cineworld Sheffield", "Sheffield"),
    ("Cineworld Shrewsbury", "Shrewsbury"),
    ("Cineworld Solihull", "Solihull"),
    ("Cineworld South Ruislip", "London"),
    ("Cineworld Speke", "Speke"),
    ("Cineworld St Helens", "St Helens"),
    ("Cineworld St Helier, Jersey", "Jersey"),
    ("Cineworld St Neots", "St Neots"),
    ("Cineworld Stevenage", "Stevenage"),
    ("Cineworld Stoke-on-Trent", "Stoke-on-Trent"),
    ("Cineworld Telford", "Telford"),
    ("Cineworld Wakefield", "Wakefield"),
    ("Cineworld Wandsworth", "London"),
    ("Cineworld Warrington", "Warrington"),
    ("Cineworld Watford", "Watford"),
    ("Cineworld Wembley", "Wembley"),
    ("Cineworld West India Quay", "London"),
    ("Cineworld Weston-super-Mare", "Weston-super-Mare"),
    ("Cineworld Whiteley", "Fareham"),
    ("Cineworld Witney", "Witney"),
    ("Cineworld Wolverhampton", "Wolverhampton"),
    ("Cineworld Wood Green", "London"),
    ("Cineworld Yeovil", "Yeovil"),
    ("Cineworld York", "York"),
    ("Cineworld at The O2 Greenwich", "London"),
    ("Ciné Lumière London", "London")
  )

  private def chunk1: Seq[(String, String)] = Seq(
    ("City Screen Picturehouse York", "York"),
    ("Close-Up Film Centre Shoreditch", "London"),
    ("Coliseum Cinema Brecon", "Brecon"),
    ("Coliseum Theatre Aberdare", "Aberdare"),
    ("Colosseum Bournemouth", "Bournemouth"),
    ("Commodore Cinema Aberystwyth", "Aberystwyth"),
    ("Commodore Ryde, Isle of Wight", "Ryde"),
    ("Connaught Theatre & Studio Worthing", "Worthing"),
    ("Corn Exchange Cinema King's Lynn", "King's Lynn"),
    ("Corn Exchange Cinema Wallingford", "Wallingford"),
    ("Corn Exchange Newbury (Screen One)", "Newbury"),
    ("Cottage Road Cinema Leeds", "Leeds"),
    ("Courtyard Hereford", "Hereford"),
    ("Cromarty Cinema", "Cromarty"),
    ("Cross Hands Hall & Cinema", "Cross Hands"),
    ("Crouch End Picturehouse", "London"),
    ("Cube Cinema Bristol", "Bristol"),
    ("Cultplex Manchester", "Manchester."),
    ("Curzon Canterbury Riverside", "Canterbury"),
    ("Curzon Cinema Aldgate", "London"),
    ("Curzon Cinema Bloomsbury", "London"),
    ("Curzon Cinema Camden", "London"),
    ("Curzon Cinema Clevedon", "Clevedon"),
    ("Curzon Cinema Colchester", "Colchester"),
    ("Curzon Cinema Hoxton", "London"),
    ("Curzon Cinema Kingston", "London"),
    ("Curzon Cinema Knutsford", "Knutsford"),
    ("Curzon Cinema Mayfair", "London"),
    ("Curzon Cinema Oxford", "Oxford"),
    ("Curzon Cinema Richmond", "London"),
    ("Curzon Cinema Sea Containers (Mondrian)", "London"),
    ("Curzon Cinema Victoria", "London"),
    ("Curzon Soho", "London"),
    ("Curzon Wimbledon", "London"),
    ("Customs House Cinema, South Shields", "South Shields"),
    ("David Lean Cinema Croydon", "London"),
    ("Depot Lewes", "Lewes"),
    ("Discovery Centre Cinema Rothesay", "Isle of Bute"),
    ("Dome Worthing", "Worthing"),
    ("Dominion Cinema Edinburgh", "Edinburgh"),
    ("Duke of York's Picturehouse Brighton", "Brighton"),
    ("Duke's at Komedia Picturehouse", "Brighton"),
    ("Dundee Contemporary Arts (DCA)", "Dundee"),
    ("East Coast Cinema Lowestoft", "Lowestoft"),
    ("Eden Court Theatre Inverness", "Inverness"),
    ("Electric Cinema Portobello", "London"),
    ("Electric Cinema White City", "London"),
    ("Electric Palace Bridport", "Bridport"),
    ("Electric Palace Harwich", "Harwich"),
    ("Electric Palace Hastings", "Hastings"),
    ("Electric Picture House Wotton-Under-Edge", "Wotton-Under-Edge"),
    ("Electric Picture Palace Southwold", "Southwold"),
    ("Elite Cinema and Theatre Ashbourne", "Ashbourne"),
    ("Ely Community Cinema", "Ely"),
    ("Embassy Cinema Ilfracombe", "Ilfracombe"),
    ("Empire Cinema Holyhead", "Holyhead"),
    ("Empire Cinema Sandwich", "Sandwich"),
    ("Empire Theatre Consett", "Consett"),
    ("Empire Theatre Halstead", "Halstead"),
    ("Everyman Bath", "Bath"),
    ("Everyman Brentford", "Brentford"),
    ("Everyman Bury St Edmunds", "Bury St Edmunds"),
    ("Everyman Cheltenham", "Cheltenham"),
    ("Everyman Cinema Altrincham", "Altrincham"),
    ("Everyman Cinema Baker Street", "London"),
    ("Everyman Cinema Barnet", "London"),
    ("Everyman Cinema Belsize Park Hampstead", "London"),
    ("Everyman Cinema Birmingham", "Birmingham"),
    ("Everyman Cinema Borough Yards", "London"),
    ("Everyman Cinema Bristol", "Bristol"),
    ("Everyman Cinema Broadgate", "London"),
    ("Everyman Cinema Cambridge", "Cambridge"),
    ("Everyman Cinema Canary Wharf", "London"),
    ("Everyman Cinema Cardiff", "Cardiff"),
    ("Everyman Cinema Chelmsford", "Chelmsford"),
    ("Everyman Cinema Chelsea", "London"),
    ("Everyman Cinema Clitheroe", "Clitheroe"),
    ("Everyman Cinema Crystal Palace", "Crystal Palace"),
    ("Everyman Cinema Durham", "Durham"),
    ("Everyman Cinema Edinburgh", "Edinburgh"),
    ("Everyman Cinema Egham", "Egham"),
    ("Everyman Cinema Esher", "Esher"),
    ("Everyman Cinema Gerrards Cross", "Gerrards Cross"),
    ("Everyman Cinema Glasgow", "Glasgow"),
    ("Everyman Cinema Hampstead", "Hampstead"),
    ("Everyman Cinema Harrogate", "Harrogate"),
    ("Everyman Cinema Horsham", "Horsham"),
    ("Everyman Cinema King's Cross", "London"),
    ("Everyman Cinema Leeds", "Albion Street"),
    ("Everyman Cinema Lincoln", "Lincoln"),
    ("Everyman Cinema Liverpool", "Liverpool"),
    ("Everyman Cinema Maida Vale", "Maida Vale"),
    ("Everyman Cinema Manchester St John's", "Manchester"),
    ("Everyman Cinema Marlow", "Marlow"),
    ("Everyman Cinema Muswell Hill", "London"),
    ("Everyman Cinema Newcastle", "Newcastle-Upon-Tyne"),
    ("Everyman Cinema Northallerton", "Northallerton"),
    ("Everyman Cinema Oxted", "Oxted"),
    ("Everyman Cinema Plymouth", "Plymouth"),
    ("Everyman Cinema Reigate", "Reigate"),
    ("Everyman Cinema Salisbury", "Salisbury"),
    ("Everyman Cinema Stratford International", "London"),
    ("Everyman Cinema Stratford-upon-Avon", "Stratford-upon-Avon"),
    ("Everyman Cinema Walton", "Walton on Thames"),
    ("Everyman Cinema Winchester", "Winchester"),
    ("Everyman Cinema Wokingham", "Wokingham"),
    ("Everyman Cinema York", "York"),
    ("Everyman Screen on the Green Islington", "London"),
    ("Everyman at The Whiteley London", "London"),
    ("Festival Drayton Centre", "Market Drayton"),
    ("Film Theatre Leiston", "Leiston"),
    ("Film Theatre Stoke-on-Trent", "Stoke-on-Trent"),
    ("Filmhouse Edinburgh", "Edinburgh"),
    ("Filmhouse Newlyn", "Newlyn"),
    ("Finsbury Park Picturehouse", "London"),
    ("Flix Student-Run Cinema Loughborough", "Loughborough"),
    ("Flix Treehouse Manchester", "Manchester"),
    ("Flora Cinema Helston", "Helston"),
    ("Flower Bowl Entertainment Centre Preston", "Preston"),
    ("Forest Cinemas Walthamstow", "London"),
    ("Forum Bridlington", "Bridlington"),
    ("Forum Cinema Hexham", "Hexham"),
    ("Forum Cinema Northampton", "Northampton"),
    ("Fuse Community Cinema Prudhoe", "Prudhoe"),
    ("Futurist Cinema", "Kidderminster"),
    ("Gaiety Cinema Whitehaven", "Whitehaven"),
    ("Gala Cinema Durham", "Durham"),
    ("Galeri Caenarfon", "Caenarfon"),
    ("Gateway Cinema Ross-on-Wye", "Ross-on-Wye"),
    ("Genesis Cinema Whitechapel", "London"),
    ("Glasgow Film Theatre", "Glasgow"),
    ("Grosvenor Cinema Glasgow", "Glasgow"),
    ("Guildhall Cinema Gloucester", "Gloucester"),
    ("Gulbenkian Theatre", "Canterbury"),
    ("Gwyn Hall Neath", "Neath"),
    ("HOME Manchester", "Manchester"),
    ("Harbour Lights Picturehouse", "Southampton"),
    ("Haslemere Hall Cinema", "Haslemere"),
    ("Haverhill Arts Centre", "Haverhill"),
    ("Heart Centre Headingley", "Leeds"),
    ("Hebden Bridge Picturehouse", "Hebden Bridge"),
    ("Highland Cinema Fort William", "Fort William"),
    ("Hilltop Cinema, Shaftesbury Arts Centre", "Shaftesbury"),
    ("Hippodrome Bo'ness", "Bo'ness"),
    ("Hollywood Plaza Scarborough", "Scarborough"),
    ("Hyde Park Picture House", "Leeds"),
    ("Hythe Moviola Cinema", "Southampton"),
    ("IMAX at Glasgow Science Centre", "Glasgow"),
    ("IMC Cinema Ballymena", "Ballymena"),
    ("IMC Cinema Enniskillen", "Enniskillen")
  )

  private def chunk2: Seq[(String, String)] = Seq(
    ("IMC Newtownards (Movieland)", "Newtownards"),
    ("Ilkley Cinema", "Ilkley"),
    ("Institute of Contemporary Arts", "London"),
    ("Iveagh Movie Studio (IMC Banbridge)", "Banbridge"),
    ("JW3 Hampstead", "London"),
    ("Jam Jar Cinema", "Whitley Bay Tyne & Wear"),
    ("Junction Goole", "East Riding of Yorkshire"),
    ("Kavanagh Cinema Herne Bay", "Herne Bay"),
    ("Keswick Alhambra", "Keswick"),
    ("Key Theatre Peterborough", "Peterborough"),
    ("Kiln Cinema Kilburn", "London"),
    ("Kinema in the Woods", "Woodhall Spa"),
    ("King Street Cinema", "Ipswich"),
    ("Kings Cinema Kingsbridge", "Kingsbridge"),
    ("Kings Cinema Newmarket", "Newmarket"),
    ("Kino Glenrothes", "Glenrothes"),
    ("Kino Hawkhurst", "Hawkhurst"),
    ("Kino Rye", "Rye"),
    ("Kino-Teatr", "Saint Leonards-on-sea"),
    ("LAS Port Righ (Aros Cinema Portree)", "Portree"),
    ("Lanternhouse Cinema", "Glasgow"),
    ("Leatherhead Cinema", "Leatherhead"),
    ("Leigh Film Factory", "Leigh"),
    ("Lexi Cinema Kensal Rise", "London"),
    ("Libanus 1877", "Borth"),
    ("Lichfield Garrick Theatre & Studio", "Lichfield"),
    ("Lighthouse Poole", "Poole"),
    ("Little Theatre Picturehouse", "Bath"),
    ("Little Theatre Sheringham", "Sheringham"),
    ("Lockworks Cinema Wolverhampton", "Wolverhampton"),
    ("Loewen Cinema", "Mablethorpe"),
    ("Lonsdale Alhambra Penrith", "Penrith"),
    ("Lonsdale City Cinema Annan", "Annan"),
    ("Lowther Pavilion Lytham", "Lytham St Annes"),
    ("Lumiere Romford", "Romford"),
    ("Luxe Wisbech", "Wisbech"),
    ("Lynton Cinema", "Lynton & Lynmouth"),
    ("Macrobert Art Centre Stirling", "Stirling"),
    ("Magic Lantern Tywyn", "Tywyn"),
    ("Majestic King's Lynn", "King's Lynn"),
    ("Malvern Theatres", "Malvern"),
    ("Maona Cinema Oswestry", "Oswestry"),
    ("Mareel Lerwick, Shetland Islands", "Lerwick"),
    ("Marina Theatre Lowestoft", "Lowestoft"),
    ("Market Hall Cinema Brynmawr", "Ebbw Vale"),
    ("Market Pavilion Cinema Blyth", "Blyth"),
    ("Maxime Cinema Blackwood", "Blackwood"),
    ("Merlin Capitol Bodmin", "Bodmin"),
    ("Merlin Cinema Thurso", "Thurso"),
    ("Merlin Regal Cinema Redruth", "Redruth"),
    ("Merlin Savoy Penzance", "Penzance"),
    ("Merlin Scala Prestatyn", "Prestatyn"),
    ("Merlin Studio Coleford", "Coleford"),
    ("Merlin Wellesley Wellington", "Wellington"),
    ("Midlands Arts Centre Birmingham", "Birmingham"),
    ("Miners Welfare and Community Hall Ystradgynlais", "Ystradgynlais"),
    ("Mockingbird Cinema & Kitchen Birmingham", "Birmingham"),
    ("Moray Playhouse", "Elgin"),
    ("Movie House (City Side) Belfast", "Belfast"),
    ("Movie House Coleraine", "Coleraine"),
    ("Movie House Glengormley", "Glengormley"),
    ("Movie House Maghera", "Maghera"),
    ("Movie Starr Canvey Island", "Canvey Island"),
    ("Mowlem Theatre", "Swanage"),
    ("Nerve Centre Londonderry", "Londonderry"),
    ("Neuadd Dwyfor Pwllheli", "Pwllheli"),
    ("New Carlton Okehampton", "Okehampton"),
    ("New Central Cinema Torquay", "Torquay"),
    ("New Picture House St Andrews", "St Andrews"),
    ("No.6 Cinema Portsmouth", "Portsmouth"),
    ("Northampton Filmhouse", "Northampton"),
    ("Northern Light Sale", "Sale"),
    ("Northern Light Wirksworth", "Wirksworth"),
    ("Nova Cinema Woking", "Woking"),
    ("Number 30 Huntly", "Aberdeenshire"),
    ("Number 8 Pershore", "Pershore"),
    ("Odeon Birmingham New Street", "Birmingham"),
    ("Odeon Cabot Circus", "Bristol"),
    ("Odeon Cinema Acton", "London"),
    ("Odeon Cinema Andover", "Andover"),
    ("Odeon Cinema Aylesbury", "Aylesbury"),
    ("Odeon Cinema Basingstoke", "Basingstoke"),
    ("Odeon Cinema Bath", "Bath"),
    ("Odeon Cinema Beckenham", "London"),
    ("Odeon Cinema Belfast", "Belfast"),
    ("Odeon Cinema Bournemouth BH2", "Bournemouth"),
    ("Odeon Cinema Braehead", "Braehead"),
    ("Odeon Cinema Bridgend", "Bridgend"),
    ("Odeon Cinema Brighton", "Brighton"),
    ("Odeon Cinema Cardiff", "Cardiff"),
    ("Odeon Cinema Chatham", "Chatham"),
    ("Odeon Cinema Chelmsford", "Chelmsford"),
    ("Odeon Cinema Colchester", "Colchester"),
    ("Odeon Cinema Coventry", "Coventry CV1 38AZ"),
    ("Odeon Cinema Crewe", "Crewe"),
    ("Odeon Cinema Dorchester", "Dorchester"),
    ("Odeon Cinema Dudley", "Dudley"),
    ("Odeon Cinema Dunfermline", "Dunfermline"),
    ("Odeon Cinema Epsom", "Epsom"),
    ("Odeon Cinema Exeter", "Exeter"),
    ("Odeon Cinema Greenwich", "London"),
    ("Odeon Cinema Guildford", "Guildford"),
    ("Odeon Cinema Harrogate", "Harrogate"),
    ("Odeon Cinema Hastings", "Hastings"),
    ("Odeon Cinema Hatfield", "Hatfield"),
    ("Odeon Cinema Hereford", "Hereford"),
    ("Odeon Cinema Holloway", "London"),
    ("Odeon Cinema Huddersfield", "Huddersfield"),
    ("Odeon Cinema Kilmarnock", "Kilmarnock"),
    ("Odeon Cinema Kingston", "London"),
    ("Odeon Cinema Lincoln", "Lincoln"),
    ("Odeon Cinema Llanelli", "Llanelli"),
    ("Odeon Cinema Loughborough", "Loughborough"),
    ("Odeon Cinema Maidstone", "Maidstone"),
    ("Odeon Cinema Manchester Great Northern", "Manchester"),
    ("Odeon Cinema Manchester Trafford Centre", "Manchester"),
    ("Odeon Cinema Mansfield", "Mansfield"),
    ("Odeon Cinema Metrocentre", "Gateshead Tyne & Wear"),
    ("Odeon Cinema Milton Keynes", "Milton Keynes"),
    ("Odeon Cinema Newark", "Newark"),
    ("Odeon Cinema Northwich Barons Quay", "Northwich"),
    ("Odeon Cinema Norwich", "Norwich"),
    ("Odeon Cinema Oldham", "Oldham"),
    ("Odeon Cinema Orpington", "London"),
    ("Odeon Cinema Port Solent", "Portsmouth"),
    ("Odeon Cinema Preston", "Preston"),
    ("Odeon Cinema Richmond", "London"),
    ("Odeon Cinema Rochdale", "Rochdale"),
    ("Odeon Cinema Salisbury", "Salisbury"),
    ("Odeon Cinema Silverlink", "Wallsend Tyne & Wear"),
    ("Odeon Cinema South Woodford", "London"),
    ("Odeon Cinema Southend-on-Sea", "Southend-on-Sea"),
    ("Odeon Cinema Stoke-on-Trent", "Stoke-on-Trent"),
    ("Odeon Cinema Streatham", "London"),
    ("Odeon Cinema Swadlincote", "Swadlincote"),
    ("Odeon Cinema Swansea", "Swansea"),
    ("Odeon Cinema Tamworth", "Tamworth"),
    ("Odeon Cinema Taunton", "Taunton"),
    ("Odeon Cinema Tottenham Court Road", "London"),
    ("Odeon Cinema Trowbridge", "Trowbridge"),
    ("Odeon Cinema Tunbridge Wells", "Tunbridge Wells"),
    ("Odeon Cinema Uxbridge", "London"),
    ("Odeon Cinema West Bromwich", "West Bromwich"),
    ("Odeon Cinema Wimbledon", "London"),
    ("Odeon Cinema Worcester", "Worcester"),
    ("Odeon Cinema Wrexham", "Wrexham"),
    ("Odeon Edinburgh (Fort Kinnaird)", "Edinburgh"),
    ("Odeon Edinburgh (Lothian Road)", "Edinburgh"),
    ("Odeon Liverpool ONE", "Liverpool"),
    ("Odeon Liverpool Switch Island", "Liverpool")
  )

  private def chunk3: Seq[(String, String)] = Seq(
    ("Odeon Luxe Birmingham Broadway Plaza", "Birmingham"),
    ("Odeon Luxe Bromborough", "Bromborough"),
    ("Odeon Luxe Derby", "Derby"),
    ("Odeon Luxe Dundee", "Dundee"),
    ("Odeon Luxe Durham", "Durham"),
    ("Odeon Luxe East Kilbride", "East Kilbride"),
    ("Odeon Luxe Edinburgh (Edinburgh West)", "Edinburgh"),
    ("Odeon Luxe Glasgow", "Glasgow"),
    ("Odeon Luxe Haymarket", "London"),
    ("Odeon Luxe Hull", "Hull"),
    ("Odeon Luxe Islington", "London"),
    ("Odeon Luxe Lee Valley", "London"),
    ("Odeon Luxe Leeds (Thorpe Park)", "Leeds"),
    ("Odeon Luxe Leeds-Bradford", "Bradford"),
    ("Odeon Luxe Leicester", "Leicester"),
    ("Odeon Luxe Leicester Square", "London"),
    ("Odeon Luxe Maidenhead", "Maidenhead"),
    ("Odeon Luxe Nuneaton", "Nuneaton"),
    ("Odeon Luxe Peterborough", "Peterborough"),
    ("Odeon Luxe Putney", "London"),
    ("Odeon Luxe Sheffield", "Sheffield"),
    ("Odeon Luxe Stafford", "Stafford"),
    ("Odeon Luxe Swiss Cottage", "London"),
    ("Odeon Luxe Telford", "Telford"),
    ("Odeon Luxe Warrington", "Warrington"),
    ("Odeon Luxe West End", "London"),
    ("Odeon Middlesbrough", "Middlesbrough"),
    ("Odeon Northampton", "Northampton"),
    ("Old Market Hall Shrewsbury", "Shrewsbury"),
    ("Olympic Cinema Barnes", "London"),
    ("Omniplex Antrim", "Antrim"),
    ("Omniplex Banbridge", "Banbridge"),
    ("Omniplex Bangor", "Bangor"),
    ("Omniplex Belfast", "Belfast"),
    ("Omniplex Birmingham", "Birmingham"),
    ("Omniplex Carrickfergus", "Carrickfergus"),
    ("Omniplex Clydebank (formerly Empire)", "Clydebank"),
    ("Omniplex Craigavon", "Craigavon"),
    ("Omniplex Downpatrick", "Downpatrick"),
    ("Omniplex Dundonald", "Belfast"),
    ("Omniplex Dungannon", "Dungannon"),
    ("Omniplex High Wycombe (formerly Empire)", "High Wycombe"),
    ("Omniplex Ipswich (formerly Empire)", "Ipswich"),
    ("Omniplex Larne", "Larne"),
    ("Omniplex Lisburn", "Lisburn"),
    ("Omniplex Londonderry", "Londonderry"),
    ("Omniplex Newry", "Newry"),
    ("Omniplex Omagh", "Omagh"),
    ("Omniplex Sunderland (formerly Empire)", "Sunderland"),
    ("Omniplex Sutton (formerly Empire)", "London"),
    ("Omniplex Wigan (formerly Empire)", "Wigan"),
    ("Orion Burgess Hill", "Burgess Hill"),
    ("Orion Dereham", "Dereham"),
    ("Palace Cinema Cinderford", "Cinderford"),
    ("Palace Cinema Devizes", "Devizes"),
    ("Palace Cinema Felixstowe", "Felixstowe"),
    ("Palace Cinema Gorleston-on-Sea", "Gorleston-on-Sea"),
    ("Palace Cinema Haverfordwest", "Haverfordwest"),
    ("Palace Cinema Kent", "Broadstairs"),
    ("Palace Cinema Malton", "Malton"),
    ("Palace Cinemas Isle of Man", "Douglas"),
    ("Paramount Penistone", "Penistone"),
    ("Parkway Barnsley", "Barnsley"),
    ("Parkway Beverley", "Beverley"),
    ("Parkway Cinema Louth", "Louth"),
    ("Parkway Cleethorpes", "Cleethorpes"),
    ("Parkway Workington", "Workington"),
    ("Pavilion Cinema Galashiels", "Galashiels"),
    ("Pavilion Cinema Whitby", "Whitby"),
    ("Pavilion Hailsham", "Hailsham"),
    ("Pavilions Teignmouth", "Teignmouth"),
    ("Peckhamplex", "London"),
    ("Phoenix Cinema Blyth", "Blyth"),
    ("Phoenix Cinema East Finchley", "London"),
    ("Phoenix Cinema Falmouth", "Falmouth"),
    ("Phoenix Cinema and Art Centre Leicester", "Leicester"),
    ("Phoenix Kirkwall, Okney Islands", "Kirkwall"),
    ("Phoenix Picturehouse Oxford", "Oxford"),
    ("Piccadilly Cinema Leicester", "Leicester"),
    ("Picture House Keighley", "Keighley"),
    ("Picture House Uckfield", "Uckfield"),
    ("Picturedrome Bognor Regis", "Bognor Regis"),
    ("Picturehouse Central London", "London"),
    ("Picturehouse Chester", "Chester"),
    ("Picturehouse Cinema City Norwich", "Norwich"),
    ("Picturehouse Clapham", "London"),
    ("Picturehouse Ealing Filmworks", "London"),
    ("Picturehouse East Dulwich", "London"),
    ("Picturehouse Epsom", "Epsom"),
    ("Picturehouse Exeter", "Exeter"),
    ("Picturehouse Greenwich", "London"),
    ("Picturehouse Hackney", "London"),
    ("Picturehouse West Norwood", "London"),
    ("Picturehouse at FACT Liverpool", "Liverpool"),
    ("Pictureville (Science and Media Museum Bradford)", "Bradford"),
    ("Playhouse Cinema Perth", "Perth"),
    ("Plaza Cinema Dorchester", "Dorchester"),
    ("Plaza Cinema Weston-super-Mare", "Weston-super-Mare"),
    ("Plaza Community Cinema Liverpool", "Crosby"),
    ("Plaza Skipton", "Skipton"),
    ("Plaza Stockport", "Stockport"),
    ("Plough Arts Centre Torrington", "Torrington"),
    ("Plymouth Arts Cinema", "Plymouth"),
    ("Pocklington Arts Centre", "York"),
    ("Pontardawe Arts Centre", "Pontardawe"),
    ("Pontio Arts & Innovation Centre Bangor", "Bangor"),
    ("Prince Charles London", "London"),
    ("Public Hall Brynamman", "Brynamman"),
    ("Quad Derby", "Derby"),
    ("Queen's Film Theatre Belfast", "Belfast"),
    ("Radway Sidmouth", "Sidmouth"),
    ("Reading Biscuit Factory", "Reading"),
    ("Rebel Cinema", "Bude"),
    ("Red Carpet Barton Marina", "Barton-under-Needwood"),
    ("Reel Cinema Blackburn", "Blackburn"),
    ("Reel Cinema Borehamwood", "Borehamwood"),
    ("Reel Cinema Bridgnorth (Majestic)", "Bridgnorth"),
    ("Reel Cinema Chippenham (Astoria)", "Chippenham"),
    ("Reel Cinema Chorley", "Chorley"),
    ("Reel Cinema Fareham", "Fareham"),
    ("Reel Cinema Hull", "Hull"),
    ("Reel Cinema Morecambe", "Morecambe"),
    ("Reel Cinema Port Talbot", "Port Talbot"),
    ("Reel Cinema Quinton", "Quinton"),
    ("Reel Cinema Rochdale", "Rochdale"),
    ("Reel Cinema Scala Ilkeston", "Ilkeston"),
    ("Reel Cinema Wakefield", "Wakefield"),
    ("Reel Cinema Widnes", "Widnes"),
    ("Reel Cinemas Burnley", "Burnley"),
    ("Reel Cinemas Farnham", "Farnham"),
    ("Regal Cinema Evesham", "Evesham"),
    ("Regal Cinema Fordingbridge", "Fordingbridge"),
    ("Regal Cinema Tenbury Wells", "Tenbury Wells"),
    ("Regal Melton Mowbray", "Melton Mowbray"),
    ("Regal Movieplex Cromer", "Cromer"),
    ("Regal Picturehouse Henley", "Henley-on-Thames"),
    ("Regal Stowmarket", "Stowmarket"),
    ("Regent Blackpool", "Blackpool"),
    ("Regent Christchurch", "Christchurch"),
    ("Regent Cinema Marple", "Marple"),
    ("Regent Redcar", "Redcar"),
    ("Regent Street Cinema London", "London"),
    ("Rex Elland", "Elland"),
    ("Rex Wilmslow", "Wilmslow"),
    ("Rich Mix Shoreditch", "London"),
    ("Richard Booth's Bookshop Hay-on-Wye", "Hereford"),
    ("Rio Burnham-on-Crouch", "Burnham-on-Crouch"),
    ("Rio Cinema Dalston", "London"),
    ("Ritz Belper", "Belper"),
    ("Ritz Burnham-on-Sea", "Burnham-on-Sea")
  )

  private def chunk4: Seq[(String, String)] = Seq(
    ("Ritz Cinema Thirsk", "Thirsk"),
    ("Ritz Multiplex Cookstown", "Cookstown"),
    ("Riverfront Newport", "Newport"),
    ("Riverside Studios Hammersmith", "London"),
    ("Riverside Theatre Woodbridge", "Woodbridge"),
    ("Robert Burns Centre Film Theatre", "Dumfries"),
    ("Rooftop Film Club Peckham (Bussey Building)", "London"),
    ("Rooftop Film Club Stratford (Roof East)", "London"),
    ("Roses Theatre Tewkesbury", "Tewkesbury"),
    ("Roxy Movies Bishop’s Stortford", "Bishops"),
    ("Roxy Movies Middlesbrough", "Middlesbrough"),
    ("Roxy Ulverston", "Ulverston"),
    ("Royal Cinema Faversham", "Faversham"),
    ("Royal Cinemas Sutton Coldfield", "Sutton Coldfield B72 1Q"),
    ("Royal Spa Centre", "Leamington Spa"),
    ("Royal St Ives Cinema", "St Ives"),
    ("Royalty Bowness-on-Windemere", "Bowness-on-Windemere"),
    ("Saffron Screen", "Saffron Walden"),
    ("Savoy (Scott Cinemas) Exmouth", "Exmouth"),
    ("Savoy Boston", "Boston"),
    ("Savoy Cinema Catterick Garrison", "Catterick Garrison"),
    ("Savoy Cinema Corby", "Corby"),
    ("Savoy Cinema Heaton Moor", "Heaton Moor"),
    ("Savoy Cinema Nottingham", "Nottingham"),
    ("Savoy Doncaster", "Doncaster"),
    ("Savoy Grantham", "Grantham"),
    ("Savoy Theatre Monmouth", "Monmouth"),
    ("Savoy Worksop", "Worksop"),
    ("Science Museum London IMAX", "London"),
    ("Scotsman Picturehouse Edinburgh", "Edinburgh"),
    ("Scott Cinemas Bridgwater", "Bridgwater"),
    ("Scott Cinemas Bristol (Westbury Park)", "Bristol"),
    ("Sherborne Cinema Gloucester", "Gloucester"),
    ("Showcase Bristol Avonmeads", "Bristol"),
    ("Showcase Cinema Cardiff", "Trefforest Industrial Estate"),
    ("Showcase Cinema Dudley", "Dudley"),
    ("Showcase Cinema de Lux Derby", "Derby"),
    ("Showcase Cinema de Lux Teesside", "Stockton-on-Tees"),
    ("Showcase Glasgow Coatbridge", "Glasgow"),
    ("Showcase de Lux Bluewater", "Dartford"),
    ("Showcase de Lux Coventry", "Coventry"),
    ("Showcase de Lux Leeds", "Leeds"),
    ("Showcase de Lux Leicester", "Leicester"),
    ("Showcase de Lux Liverpool", "Liverpool"),
    ("Showcase de Lux Nottingham", "Nottingham"),
    ("Showcase de Lux Paisley", "Paisley"),
    ("Showcase de Lux Peterborough", "Peterborough"),
    ("Showcase de Lux Reading", "Reading"),
    ("Showcase de Lux Southampton", "Southampton"),
    ("Showroom Sheffield", "Sheffield"),
    ("Silver Screen Folkestone", "Folkestone"),
    ("Sleaford Playhouse", "Sleaford"),
    ("South Hill Park Arts Centre Bracknell", "Bracknell"),
    ("Southport Bijou Cinema", "Southport"),
    ("Southsea Cinema & Arts Centre", "Portsmouth"),
    ("Spey Valley Cinema Aviemore", "Aviemore"),
    ("Stag Sevenoaks", "Sevenoaks"),
    ("Star and Shadow Cinema Newcastle", "Newcastle upon Tyne"),
    ("Station Cinema Richmond", "Richmond"),
    ("Stephen Joseph Theatre Scarborough", "Scarborough"),
    ("Storyhouse Chester", "Chester"),
    ("Strand Arts Centre Belfast", "Belfast"),
    ("Strand Cinema Rhyl", "Rhyl"),
    ("Studio Cinema Dunoon", "Dunoon"),
    ("Taliesin Arts Centre Swansea", "Swansea"),
    ("Taunton Brewhouse", "Taunton"),
    ("The Arches (The Cinema in the Power Station)", "London"),
    ("The Arzner", "London"),
    ("The Ashford Cinema (formerly Picturehouse)", "Ashford"),
    ("The Assembly at Heckfield Place", "Heckfield Place"),
    ("The Astra Cinema St. Mawgan", "Newquay"),
    ("The Avenue Cinema Belfast", "Belfast"),
    ("The Avenue Cinema Minehead", "Minehead"),
    ("The Barn Banchory", "Banchory"),
    ("The Beehive Honiton", "Honiton"),
    ("The Cameo, Picturehouse", "Edinburgh"),
    ("The Cinema Newton Stewart", "Newton Stewart"),
    ("The Cinema at Selfridges", "London"),
    ("The Cinema in the Power Station", "London"),
    ("The Cinema, Campus West", "Welwyn Garden City"),
    ("The Dukes Lancaster", "Lancaster"),
    ("The Flavel", "Dartmouth"),
    ("The Forum Northallerton", "Northallerton"),
    ("The Fraser Centre Tranent", "Tranent"),
    ("The Fullarton Castle Douglas", "Castle Douglas"),
    ("The Garden Cinema", "London"),
    ("The Gate, Picturehouse London", "London"),
    ("The Island, Lytham St. Annes", "Lytham Saint Annes"),
    ("The Light Addlestone", "Addlestone"),
    ("The Light Banbury", "Banbury"),
    ("The Light Bolton", "Bolton"),
    ("The Light Bradford", "Bradford"),
    ("The Light Cambridge", "Cambridge"),
    ("The Light New Brighton", "Wallasey"),
    ("The Light Redhill", "Redhill"),
    ("The Light Sheffield", "Sheffield"),
    ("The Light Sittingbourne", "Sittingbourne"),
    ("The Light Stockport", "Stockport"),
    ("The Light Thetford", "Thetford"),
    ("The Light Walsall", "Walsall"),
    ("The Light Wisbech", "Wisbech"),
    ("The Living Room Cinema Chipping Norton", "Chipping Norton"),
    ("The Living Room Cinema Liphook", "Liphook"),
    ("The Mallard Cinema, Guernsey", "Guernsey"),
    ("The Malt Lymington", "Lymington"),
    ("The Maltings Berwick-Upon-Tweed", "Berwick-Upon-Tweed"),
    ("The Montrose Playhouse", "Montrose"),
    ("The New Vic, Tisbury Village Hall", "5A High Street Tisbury"),
    ("The Nickel London", "London"),
    ("The Odyssey St Albans", "St Albans"),
    ("The Oxford Cinema & Cafe", "Oxford"),
    ("The Parade Cinema Marlborough", "Marlborough"),
    ("The Poly Falmouth", "Falmouth"),
    ("The Rex Cinema Berkhamsted", "Berkhamsted"),
    ("The Rex Cinema Wareham", "Wareham"),
    ("The Ritz Cinema Workington", "Workington"),
    ("The Ritzy Picturehouse Brixton", "London"),
    ("The Tower Digital Arts Center Helensburgh", "Helensburgh"),
    ("The Watermark Ivybridge", "Ivybridge"),
    ("The Wells Film Centre", "Wells"),
    ("The Woodville Gravesend", "Gravesend"),
    ("Theatr Colwyn", "Colwyn Bay"),
    ("Theatr Derek Williams", "Bala"),
    ("Theatr Gwaun Fishguard", "Fishguard"),
    ("Theatr Mwldan Cardigan", "Cardigan"),
    ("Tivoli Theatre Wimborne", "Wimborne Minster"),
    ("Tivoli Tiverton", "Tiverton"),
    ("Torch Theatre Milford Haven", "Milford Haven"),
    ("Totnes Cinema", "Totnes"),
    ("Tower Cinema Skegness", "Skegness"),
    ("Tower Mill (Heart of Hawick)", "Hawick"),
    ("Towner Eastbourne Cinema", "Eastbourne"),
    ("Tyneside Newcastle", "Newcastle"),
    ("Ultimate Picture Palace Oxford", "Oxford"),
    ("Victoria Hall Ellon", "Ellon"),
    ("Village Picture House Cuddington", "Aylesbury"),
    ("Vue Cinemas Accrington", "Accrington"),
    ("Vue Cinemas Altrincham", "Altrincham"),
    ("Vue Cinemas Barrow", "Barrow-in-Furness"),
    ("Vue Cinemas Basildon", "Basildon"),
    ("Vue Cinemas Basingstoke", "Basingstoke"),
    ("Vue Cinemas Bedford", "Bedford"),
    ("Vue Cinemas Bicester", "Bicester"),
    ("Vue Cinemas Birkenhead", "Birkenhead"),
    ("Vue Cinemas Birmingham", "Birmingham"),
    ("Vue Cinemas Blackburn", "Blackburn"),
    ("Vue Cinemas Bolton", "Bolton"),
    ("Vue Cinemas Bristol Cribbs Causeway", "Bristol"),
    ("Vue Cinemas Bristol Longwell Green", "Bristol"),
    ("Vue Cinemas Bromley", "London")
  )

  private def chunk5: Seq[(String, String)] = Seq(
    ("Vue Cinemas Bury", "Bury"),
    ("Vue Cinemas Camberley", "Camberley"),
    ("Vue Cinemas Carlisle", "Carlisle"),
    ("Vue Cinemas Carmarthen", "Carmarthen"),
    ("Vue Cinemas Castleford", "Castleford"),
    ("Vue Cinemas Cheshire Oaks", "Ellesmere Port"),
    ("Vue Cinemas Cleveleys", "Cleveleys"),
    ("Vue Cinemas Colchester", "Colchester"),
    ("Vue Cinemas Cramlington", "Cramlington"),
    ("Vue Cinemas Cwmbran", "Cwmbran"),
    ("Vue Cinemas Dagenham", "London"),
    ("Vue Cinemas Darlington", "Darlington"),
    ("Vue Cinemas Doncaster", "Doncaster"),
    ("Vue Cinemas Eastleigh", "Eastleigh"),
    ("Vue Cinemas Eltham", "London"),
    ("Vue Cinemas Exeter", "Exeter"),
    ("Vue Cinemas Farnborough", "Farnborough"),
    ("Vue Cinemas Finchley Road", "London"),
    ("Vue Cinemas Fulham", "London"),
    ("Vue Cinemas Gateshead", "Tyne & Wear"),
    ("Vue Cinemas Glasgow Fort", "Glasgow"),
    ("Vue Cinemas Glasgow St. Enoch", "Glasgow"),
    ("Vue Cinemas Halifax", "Halifax"),
    ("Vue Cinemas Hamilton", "Hamilton"),
    ("Vue Cinemas Harrow", "London"),
    ("Vue Cinemas Hartlepool", "Hartlepool"),
    ("Vue Cinemas Hull", "Hull"),
    ("Vue Cinemas Inverness", "Inverness"),
    ("Vue Cinemas Islington", "London"),
    ("Vue Cinemas Lancaster", "Lancaster"),
    ("Vue Cinemas Leamington Spa", "Leamington Spa"),
    ("Vue Cinemas Leeds (Kirkstall Road)", "Leeds"),
    ("Vue Cinemas Leeds (The Light)", "Leeds"),
    ("Vue Cinemas Leicester", "Leicester"),
    ("Vue Cinemas Livingston", "Livingston"),
    ("Vue Cinemas Manchester Printworks", "Manchester"),
    ("Vue Cinemas Manchester Quayside", "Salford"),
    ("Vue Cinemas Merthyr Tydfil", "Merthyr Tydfil"),
    ("Vue Cinemas Newbury", "Newbury"),
    ("Vue Cinemas Newcastle-under-Lyme", "Newcastle-under-Lyme"),
    ("Vue Cinemas North Finchley", "London"),
    ("Vue Cinemas Northampton", "Northampton"),
    ("Vue Cinemas Norwich", "Norwich"),
    ("Vue Cinemas Nottingham", "Nottingham"),
    ("Vue Cinemas Oxford", "Oxford"),
    ("Vue Cinemas Piccadilly", "London"),
    ("Vue Cinemas Plymouth", "Plymouth"),
    ("Vue Cinemas Poole", "Poole"),
    ("Vue Cinemas Portsmouth", "Portsmouth"),
    ("Vue Cinemas Preston", "Preston"),
    ("Vue Cinemas Purley Way Croydon", "London"),
    ("Vue Cinemas Reading", "Reading"),
    ("Vue Cinemas Redditch", "Redditch"),
    ("Vue Cinemas Romford", "Romford"),
    ("Vue Cinemas Scunthorpe", "Scunthorpe"),
    ("Vue Cinemas Sheffield", "Sheffield"),
    ("Vue Cinemas Southport", "Southport"),
    ("Vue Cinemas Staines", "Staines-upon-Thames"),
    ("Vue Cinemas Stirling", "Stirling"),
    ("Vue Cinemas Stratford", "London"),
    ("Vue Cinemas Stroud", "Stroud"),
    ("Vue Cinemas Swansea", "Swansea"),
    ("Vue Cinemas Swindon", "Swindon"),
    ("Vue Cinemas Thanet Westwood Cross", "Thanet"),
    ("Vue Cinemas Torbay (Paignton)", "Paignton"),
    ("Vue Cinemas Watford", "Watford"),
    ("Vue Cinemas West End (Leicester Square)", "London"),
    ("Vue Cinemas West Thurrock", "West Thurrock"),
    ("Vue Cinemas Westfield Shepherd's Bush", "London"),
    ("Vue Cinemas Wood Green", "London"),
    ("Vue Cinemas Worcester", "Worcester"),
    ("Vue Cinemas York", "York"),
    ("Vue Edinburgh Ocean Terminal", "Edinburgh"),
    ("Vue Edinburgh Omni Centre", "Edinburgh"),
    ("WTW Lighthouse Newquay", "Newquay"),
    ("WTW Plaza Truro", "Truro"),
    ("WTW Regal Wadebridge", "Wadebridge"),
    ("WTW White River Cinema", "St Austell"),
    ("Warwick Arts Centre Coventry", "Coventry"),
    ("Waterfront Greenock", "Greenock"),
    ("Watermans Art Centre Brentford", "London"),
    ("Watershed Bristol", "Bristol"),
    ("Watersmeet", "Rickmansworth"),
    ("Wellington Orbit", "Wellington"),
    ("West Side Cinema Stromness", "Stromness"),
    ("Westway Cinema Frome", "Frome"),
    ("Wetherby Film Theatre", "Wetherby"),
    ("Windmill Littlehampton", "Littlehampton"),
    ("Woolton Picture House", "Liverpool"),
    ("Wyeside Arts Centre Builth Wells", "Builth Wells"),
    ("Wyllyotts Theatre Potters Bar", "Potters Bar"),
    ("Zeffirellis Cinema Ambleside", "Ambleside")
  )

  /** Venue display name -> its town. Display name because that is the key a
   *  venue is identified by everywhere else — `Source.byDisplayName`, the
   *  stored slots, the scrape catalog. */
  val byDisplayName: Map[String, String] = (chunk0 ++ chunk1 ++ chunk2 ++ chunk3 ++ chunk4 ++ chunk5).toMap

  /** The towns a group of venues sits in, most venues first — the order
   *  [[City.coveredPlaces]] promises. A venue the table does not know is
   *  simply not counted, so a fresh cinema names no town until the next
   *  sweep rather than blanking the ones around it. */
  def of(cinemas: Seq[Cinema]): Seq[String] =
    TownRanking.ranked(cinemas.flatMap(c => byDisplayName.get(c.displayName)))
}
