package services.cinemas

import models._
import org.jsoup.Jsoup
import tools.{HttpFetch, TextNormalization}

import java.time.{LocalDate, YearMonth, ZoneId}
import scala.jdk.CollectionConverters._
import scala.util.Try

/**
 * Kino Zamek — the cinema screen of the Zamek Książąt Pomorskich (Castle of
 * the Pomeranian Dukes) in Szczecin.  The castle's programme page at
 * `https://zamek.szczecin.pl/wydarzenia/kino/` is the canonical list of
 * films currently on the programme; it contains only films, unlike the MSI
 * ticketing portal which mixes films with concerts, workshops and other
 * cultural events.
 *
 * === Strategy ===
 * 1. Fetch the kino listing page to extract the set of film slugs
 *    (`/wydarzenie/kino/<slug>/`).  This is the film allow-list.
 * 2. Fetch the MSI month page(s) for showtime data.
 * 3. For each MSI film-block, derive a slug from the title and check if it
 *    (or any prefix of it) appears in the allow-list.  Blocks that don't match
 *    — concerts, workshops, other non-film events — are silently dropped.
 * 4. Merge matching blocks across months, decode HTML entities, and apply
 *    sentence-case to the Polish title part.
 *
 * === Slug matching ===
 * The listing slug is generated by the WordPress site from the Polish title via
 * the standard NFD-deburr + lowercase + non-alphanumeric → `-` chain.  We
 * approximate the same transformation and look for a slug prefix match: e.g.
 * MSI title `CASABLANCA – AMERYKAŃSKA KLASYKA` → slug `casablanca` matches
 * listing slug `casablanca`.
 *
 * @param http   HTTP client (swap for `FakeHttpFetch` in tests).
 * @param cinema The [[Cinema]] source tag attached to every [[CinemaMovie]]
 *               produced by this client.
 * @param today  Calendar anchor for computing the months to fetch; defaults to
 *               the current Warsaw clock date.
 */
class KinoZamekClient(
  http:             HttpFetch,
  override val cinema: Cinema,
  today:            LocalDate = LocalDate.now(ZoneId.of("Europe/Warsaw"))
) extends CinemaScraper {

  import KinoZamekClient._

  def scrapeHosts: Set[String] = CinemaScraper.hostsOf(ListingBaseUrl, MsiBaseUrl)

  def fetch(): Seq[CinemaMovie] = {
    val filmSlugs = fetchFilmSlugs()

    val thisMonth = YearMonth.from(today)
    val nextMonth = thisMonth.plusMonths(1)

    val slots = Seq(thisMonth, nextMonth).flatMap { ym =>
      val url  = monthUrl(ym)
      val html = Try(http.get(url)).getOrElse("")
      if (html.isEmpty) Seq.empty
      else {
        val allSlots = MsiScraper.parseMonthWithYear(html, ym, MsiBaseUrl, cleanTitle)
        allSlots.filter(s => isFilm(s.title, filmSlugs))
      }
    }

    MsiScraper.toMovies(slots, cinema)
  }

  /** Fetch the kino listing page and return the set of film slugs. */
  private def fetchFilmSlugs(): Set[String] = {
    val html = Try(http.get(ListingUrl)).getOrElse("")
    if (html.isEmpty) return Set.empty
    val doc = Jsoup.parse(html)
    doc.select("a[href*='/wydarzenie/kino/']").asScala.toSeq
      .flatMap(a => SlugPat.findFirstMatchIn(a.attr("href")).map(_.group(1)))
      .toSet
  }
}

object KinoZamekClient {

  val ListingBaseUrl = "https://zamek.szczecin.pl"
  val ListingUrl     = s"$ListingBaseUrl/wydarzenia/kino/"
  val MsiBaseUrl     = "https://bilety.zamek.szczecin.pl"

  def monthUrl(ym: YearMonth): String =
    s"$MsiBaseUrl/MSI?sort=Name&date=${ym.getYear}-${"%02d".format(ym.getMonthValue)}"

  private val SlugPat = """/wydarzenie/kino/([^/]+)/""".r

  /**
   * Decode HTML entities and apply sentence case to the title.  For Zamek we
   * keep the full title (including original-language subtitle in parens) because
   * those subtitles are part of the film identity, not format codes.
   */
  private[cinemas] def cleanTitle(raw: String): String = {
    // Jsoup already decodes HTML entities in attribute values.
    ScraperParse.sentenceCase(raw.trim)
  }

  /**
   * Derive the WordPress slug that the listing site would generate for `title`
   * and check whether it appears (as a prefix match) in `filmSlugs`.
   *
   * The slug is generated by:
   *   1. Keep only the part before the first em-dash `–`, en-dash `—`, or colon
   *      (those are programme-series suffixes, not slug components).
   *   2. Apply NFD deburr (diacritics + `ł`→`l`).
   *   3. Lowercase; replace non-alphanumeric runs with `-`; strip leading/trailing `-`.
   *
   * Matching uses a prefix: listing slug `casablanca` matches derived slug
   * `casablanca-amerykanska-klasyka`.  If no film slug from the listing is a
   * prefix of (or equal to) the derived slug, the event is considered non-film.
   *
   * Edge cases:
   *   - When `filmSlugs` is empty (fetch failed), ALL MSI events pass through
   *     rather than returning nothing.
   */
  private[cinemas] def isFilm(title: String, filmSlugs: Set[String]): Boolean = {
    if (filmSlugs.isEmpty) return true
    val derived = toSlug(title)
    filmSlugs.exists(s => derived == s || derived.startsWith(s + "-") || s.startsWith(derived + "-"))
  }

  /** Best-effort approximation of the WordPress slug derivation. */
  private[cinemas] def toSlug(title: String): String = {
    // Strip original-language subtitle in parens at the end
    val withoutSubtitle = title.replaceFirst("""\s*\([^)]+\)\s*$""", "").trim
    // Take only the part before an em-dash, en-dash, colon, or slash (series suffix)
    val base = withoutSubtitle.split("""[–—:/]""").head.trim
    // Deburr (NFD + strip combining + ł→l)
    val deburred = TextNormalization.deburr(base)
    // Lowercase, replace non-alphanumeric sequences with -
    deburred.toLowerCase
      .replaceAll("[^a-z0-9]+", "-")
      .stripPrefix("-").stripSuffix("-")
  }
}
