k3s:
    cluster-token: ENC[AES256_GCM,data:vtDmh99XhDCiJmJhRqnCF93VWlGK6F5G4CaqDUrL461Qv/y9hQnSFMas9yfTfGbBdAbsB83hNa/1hNA+0usALA==,iv:GoeY+qEljLX1FCageqiid7K7So0xeLLGzRhjFYJR++A=,tag:ys9XgiEL8n3/iuKrr7S/VA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSjBoeWhRVXF5REVreWZt
            K1BUNklHUmtRY21ZZ0w4OUZBNmJrd0VjZVZ3Ci8xRXk1NUxxaXNXcTQwMEh6RGs5
            THNvajB6ZzdTUDdoNjdjN284djF6ZEEKLS0tIE83WnZBTGVnaGZHYmd6OU1HYXZT
            b1ZaSEJ5Rk8xdWtlaG53YUhmY0Z5MWMK4cMclzfhd9IAYFRrk4uablUi2sBvCg/A
            qO9eaYSDnjfE7wLhJKfDyLMU6MhkO4Jze/dmzoAfMbKCldiLMU0WuQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xk5y9cqtyphr3deefnnfkfpd47yh7se90waj0hwzgefgmqzqsq7q8dy8ca
    lastmodified: "2026-08-29T07:03:21Z"
    mac: ENC[AES256_GCM,data:depigrRd+xIrfH966g7pDCg7GL87T800za3FB5IBy1p+my68NANAWeCIbtLR+HEo9xnL+GSItYC/oXcfmtmdzj7816thI3L/GodcFZsDHaBCE5PT9Af6h9I8TKwS2U8EvT6UMH8QII1wnN0R+SERx12z2h4Gqv6KP7ALsU6l/8I=,iv:2FtCpBTkfVEUcQ2aQDDWLXnifD2vh3dDXS/L0Hiv/WA=,tag:+a5mih6T3rbws6IRQH6+Jg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
