k3s:
    cluster-token: ENC[AES256_GCM,data:vtDmh99XhDCiJmJhRqnCF93VWlGK6F5G4CaqDUrL461Qv/y9hQnSFMas9yfTfGbBdAbsB83hNa/1hNA+0usALA==,iv:GoeY+qEljLX1FCageqiid7K7So0xeLLGzRhjFYJR++A=,tag:ys9XgiEL8n3/iuKrr7S/VA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSUZzdWdYalRpWlN4UmZl
            Mk5tL083b3NLazZKVkJXQUpoZkY4N0NDNmlVClJhWTBqQVNGV3hLeFhGTEVTWGl2
            UHhaMXN5bVdPOHFhdThnbXJDcE5PL0EKLS0tIE1EQmhzMFlXUllZVEN5aTlpOU1i
            QUc3UFZqR1UvaU44UjhIRVZKVUMvZEEKOGOwFxOSLt1Oeo2XDIbe00snMYBSnFQR
            oP7bvTl+ztQr5asPLTveQzl7RtmNcUvW5cZlNqSkgyimXgtvZkgu4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xk5y9cqtyphr3deefnnfkfpd47yh7se90waj0hwzgefgmqzqsq7q8dy8ca
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAya01RS2owem4yTWdKUnZE
            NkFwbkIxRWh0Qk5Ob2xTVldzb3BhTlZLUEg0ClJzalNBYVcvKzMxVjBPYUY3eklT
            WDVBcXo5SGhxbHNHOWNVeXFxeDlSMTAKLS0tIEVDSWpKU0x4S096SnVieG1UV1Bm
            cTVseGhlQ1VYQ0NuVDRLZldWVFVwMGMKM6IBbOmJOhMy7CXy1tMVd/IQfRhtLibF
            rzwLpi8aKET3Vail5z2I+l4L85sGbGPQ5hWFGuhh4uS75IssQ+8hsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17t47vs4zkcgylgtkdeuem04yc4dwxhsaytp8g3cs3phr8ld2e45q9h03v8
    lastmodified: "2026-08-29T07:03:21Z"
    mac: ENC[AES256_GCM,data:depigrRd+xIrfH966g7pDCg7GL87T800za3FB5IBy1p+my68NANAWeCIbtLR+HEo9xnL+GSItYC/oXcfmtmdzj7816thI3L/GodcFZsDHaBCE5PT9Af6h9I8TKwS2U8EvT6UMH8QII1wnN0R+SERx12z2h4Gqv6KP7ALsU6l/8I=,iv:2FtCpBTkfVEUcQ2aQDDWLXnifD2vh3dDXS/L0Hiv/WA=,tag:+a5mih6T3rbws6IRQH6+Jg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
