mongodb:
    exporter-password: ENC[AES256_GCM,data:ZOzWPPy2f3wMT1nA/9uC3HQEVcFod/S619Of4s79XbW4PFQadbRwgYdsfhLO5RdAd6fVgKBWuctXptppV0wOrw==,iv:kQon6AMoGXuIxf/AmXkMXPSeLqQFCUFxJe8KFq9XEf4=,tag:/xJxrxTgtNs1t3OraAAJ+g==,type:str]
    ci-corpus-password: ENC[AES256_GCM,data:YXZ6+UAYg5sNaaVGHZonw29zFn4KMjWYYXVowgRMEQGmW8QN2wflnw==,iv:+4mn5k0tNmbbA32Mvu2yykOlsTMyoF0i6e94D5fSHrA=,tag:Youp2QClspofOP7DtJzt9g==,type:str]
    keyfile: ENC[AES256_GCM,data:nfZNQWUPosuAblsZ9eKckraQBM3GXkGBbgB2Yb3M8PAmlI8Vlv44vhMEf4oYiGwZ2CwN5w0t/JUs2Mdi4xlCcgPoffbHXQ7Kbn77ZwA3C6108HWKWrVQfCuClOKOpvZ5AfnzpGfXkb/IFXHDffZjHWmB6sGbZ8dkWIIqNbv3PhKg/T35TESAt6Cae6vlxIHmqds7aVA1Eh/ZgNX19IVxha3uuzBDyoeb+pu+OuPO2r40VpSVm2D45/2gHqxm3GuJdSM/PjkcOhbp8MvDmSRR63OtNWaLIpHp9dnvq9NeWkDFVbuugaPsn+YJbpRIpSRpulsxyybXksjIXyNxXqpCLwY9tS6iswcdsHZ2jKin9+m3g8pLQu/5uDzKzFJtOMa5YTFw/RQek8OYE+CtpOBSqU/YNKkWK4kYKatPUnE86+agpcVp2P7DMUH9Lf+rUE5xFZQstnwRLe73lWrBvyGO9OxOv7qusxnGY3QaFdWNr3R/5yQwMHK1ntcBrjvfjZf43KSlXEZs+SuUy2Ti1ZXpMRplkGvzPrd+vq5G6Bk564otTS63sBM4boYlEZtlyqyjgIDLUXjfVXJ/BxaMWIgZnUnge1Wapsz2jkqQcvgHbbUl7zCw9OyShSSCZUCVCoFCLndmFKkKclnPh0R85dRhJeuoZFy7hD4dkjLE2ACQFXs5ZTrp18JTO0bG8WpQKsyFzAHg+rTZYjoYZh+0Lc/gqaGsi3LsD2k7zp/ESpgEcpKkIOAQLqP2Gx81E5GSh271d7R2UOhKtwantV/FSP8DWdiWIFel3k+H4hbEVS4XzrNKiXjlGWelhiIZlO2KgXff/3EUVDl085SReyJKPHmUu34N0D1dqmyXqA7qk4Qi1tiQ4jBylMqrU+TAgxMdpEf9sC2eCwkXcIeyeqS4I8f3jPTkBNadc2EMsn5o4l6HDRlqMsSMOr3zXewSbrbIdbw2zxneNfhJDe/YQiushyXk68vXm4TPQZyQQSXd0YTT9KnBzzOdtbymctnVTQWboHa5UaklOSs7sY8D4LHvB5/VIcP5XlHe6isa3tOiOEXlz7Aq2DyyMn35im9S0c7ie3MvGMPi4brnB6KG2lEemz3r8gj0n6LqFXvJ3+76ez4nLHsg3bxLrbBpIQ+65jS0gZZbqnNRVj5dMeGgEVi9+1HVvTnHqRU5jqlWJuiDc/NvFxwk9k7BBFnAbDOxGM4Stbyyeb6lzxBqID1wDkqO8waaIySiYzHlsGV5vfqOjIvmke3lHhDd6gSWiOh5/4nALOL02+hd6XPoQzJ+HQ1SR2mwvdnoYUm4+y6peQ/VeCDKg66XlUetJMd5+ViPyBlWzhgx,iv:sQJRBy6vX4isCWB+RNo9fszF1P9bjeifFWXd2WSq3xc=,tag:+PSLxzSwfKmtHF0Xabqx8Q==,type:str]
    backup-password: ENC[AES256_GCM,data:u7oacMyXO9sGyl0gDQciEmN/lmXUWpMWFh3T1/K6vDzX5Vab6RgSRUrGLkI=,iv:4HyRW79Xwni99H965k3Wlr4xaddLQwx+Y/RJHelQUu0=,tag:hQGf094HG/KlS2vuTdcjzQ==,type:str]
wireguard-fly:
    private-key: ENC[AES256_GCM,data:2w1/mFp7kifB4eB+d867Gs4a4kWvz8BWfhOcCMsT6/g8qnKdf/472Ko+DLo=,iv:+BhVc9GHY7pCU7gGJWYec9127mDbOpd4H1cDwysuCfw=,tag:IpeIQa0zvsSlvhWA2q8qqA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvU3Q2ejVuVktEd1hMeHdu
            VXJtQ29GVENCNmd1bEwweTlqdW1qWjNtajB3CkRhZGVEaFlXVXZSSi9yTTlsTit5
            MWhPcGsyajh5WmZXZTFWZ0d6UFBSa28KLS0tIFMrcXhSNkE1bkVqS2xxRkVKTmVh
            enhHRzVRb2IrK2pOT25CNjhuekZSa1UK0KuOqSRGAIrBxbR4hgCH2NLZ0rWWFhFn
            yFl2FQdWlGf1dH3sdsSNVK+2XHH11Y40cJJ5KsE9vBAV+wT+9f9FGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xk5y9cqtyphr3deefnnfkfpd47yh7se90waj0hwzgefgmqzqsq7q8dy8ca
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQitjZ3VhNlNBcVZ0dGk5
            eXpwUVVKd2M2WUFSSC9mN3pGekZEeC9WNG5rClVlN1BkM3RYeVVMbnVJcGFabkdW
            dC9ZZTBNS3FCWTZiS09ZT2pmZTM0c0kKLS0tIEhTdlNzWkRaOERpU3h0TjJ5NFlR
            ZitzVWZlWFhGM0hXUERLaklPb20wNzAKM9c7dv/jJHFgJM9LXXcGHUaQX+QU+L2u
            KrYL+sfCkw50kBsBcenk701Ls14uNHp06LSRGSRrrjbzu4Ou7yuQhg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10axwfl5cxr86rkx0ev033cx3he8lxf5stvwujpyw7gj7ydj8qd7srqr206
    lastmodified: "2026-08-29T11:37:58Z"
    mac: ENC[AES256_GCM,data:qHt4NkWmA7vR9xMPWBUBBGCgOy2el4Zpokwy6Dn6JDmaU6Q5aDX6zg4UNel3FOuJ5GpppWjPL6YRmb1SdCC95aXJxK0GLw4B2H/vkYiwWrY7jQBh6ntI3+mh+DsgJLVx4SMOuMm4SwWqZeYNdEzIv6DMU6jKZgFUu17VbsEcx+s=,iv:jhcayODyDNZObU76LyjPr5mU0Ncr2VNjpsjj6/yQeOM=,tag:GNIuRoSPwfFIRxiy3uYgWQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
