alertmanager:
    telegram-bot-token: ENC[AES256_GCM,data:0+XbfEA/4QYbLsi9aMJ1+AHScvV6DK/n6CTxX2oi8bwY7t7ghvKTtDpj+8sLSg==,iv:D0JD+q2av4kvVS5QTZh6BcmpCvS8mMruab3T7Ns+/MI=,tag:Ak65KBkmSxodkVXLp8otoQ==,type:str]
    smtp-password: ENC[AES256_GCM,data:8OyY2ZQ4Ld6AKsPvS/1fXglJgLxtHL5SE5ERuW3SIGuaGEkr,iv:fEsxEKJ2Oq4NszqyD6URYPCsNUvnfYNBtNOqOStVAFA=,tag:pPPvYl3X0kYMknKHjNQ6rQ==,type:str]
grafana:
    secret-key: ENC[AES256_GCM,data:YWNIpxlWSe59jX722iQsqf67B4jE73lATtecgQm93hwzB9dO+FILAtZFy6k=,iv:DTw2wYwTF9qg2zi0Wy9AzwqdTSI7yZRA/LGy+nOv5m8=,tag:taiYaFcFtuMZKtd91sZE3A==,type:str]
    admin-password: ENC[AES256_GCM,data:9p3bZr8dj1p8lW4mb1Oraw0Z58f585YHhMoB/dBVPpM=,iv:59J+YDuDbNCN8Te4DggUK40pfBQyijLGt6y4KcFrBDc=,tag:nv20/owC/LuKT44tEYL4Ug==,type:str]
    telegram-bot-token: ENC[AES256_GCM,data:svWhxrOTsgGuMKBd0IFojTXyK7k2aL0eei3ozeYAwTF28ZHbBSqKyheD/LAtCQ==,iv:jTsZZASYC3JWvn5lGQtL3dWbSMTk1kSfTdKaPX2GOQQ=,tag:8fi9LDEd5ZJUdM4rFvNz3g==,type:str]
k3s:
    cluster-token: ENC[AES256_GCM,data:uZP4w/l+CZwXxZfJ0YaKh1nJFuPjiy00NdmEnvVYxODEwAQPFZZEe1cQz9ec+aNGFYg7OSnZ594DzVlDlkLLDw==,iv:HuuQr7KC1jdqQ6Z/5FOJNW82egMKhQNEoNKapIsLw8Y=,tag:pCUYKwZgAdFsSCLZBCs07w==,type:str]
victoria-logs:
    basic-auth-hash: ENC[AES256_GCM,data:Dx12TMyVJxMb3Ppdpx71BRLIijchQ56IDUwRy8nLZgpUQ+mUefzgFtDnjwA/n0yzPgQUQdsf1s8/yo4b,iv:Rx2f+092TaeWGDilvm3jvI7qdMMaTVkCLUn5QeCpZIM=,tag:FlxzhwlP3/D09GSR5IAWaQ==,type:str]
google-sso:
    client-secret: ENC[AES256_GCM,data:4CLIRXvvBBaddIyi4JCt3MFvN++FhgU1cZ8EdFpN66jD3bQ=,iv:qP1t3SrO6b9y21v5jRaStdK7Pn0p+N+FCn93/ONVGIU=,tag:6zPMSJSRUjscOCeiq4AfTw==,type:str]
    cookie-secret: ENC[AES256_GCM,data:l3s92pSSrFSMCOMtQFZvKz7k8C6429DOM29iqBnCeWEWWqcMnGJLrduS7Wk=,iv:VEE5ZRXtFl07DZ8SnusPe1toQPRnnHxZIUFhQajYH2s=,tag:k8H0GI1rjOm3/No6OZPvLA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMQ0tBQzRKMURzZEhTdktL
            a2JIcUlnR293OGlBMkYyS0hJa1hTbkNuNkZzCi9YMzlmR0Iwak5jSVh3d1Q1aWhm
            dy9qeVA1NFRXYzZYbGxON1Z3WXdBWDgKLS0tIE0wdVh4Z3dIcmo2V1YvbXNNR2l0
            V3NuUnJPQWZnRlBRVEhiSDdSY01iMFUK4pGaEWMxcygT0wG474QTfoqHED+9uozR
            cWlwcTEiok/m4eFqMuVDR/S1+0JqMUJAvPiSksb2j8irS1fmk4dpug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xk5y9cqtyphr3deefnnfkfpd47yh7se90waj0hwzgefgmqzqsq7q8dy8ca
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJaEtveVMvZTlZbW1kT3No
            dzJvaW5BZVNDOWRaSGNzT2xsVUZ4cEE1dlFjClVsalQyNjFmRzFYMktnaEZSczdK
            Tyt3Rkh0TkJXVXo4SjJ3QnNtSmtUd0EKLS0tIG5paWNpZGlhVkkyQURONTFBRWRS
            b3F6aCtvbWVwbFUxNWI5bjFrclBpeVUK5bkEDk6lTFpBQZetMDfkNGR2wpf+8uVd
            3wpVWbxFLOD7tTGmecBCoIYDmLt06n6rVUy3qFY9LSX/WIBXR/XWtA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gzk07n7anpg2nxdlfm5waledsu6xvhmg0s93tcr3474mlcx5jufsuxjpg8
    lastmodified: "2026-09-07T02:57:41Z"
    mac: ENC[AES256_GCM,data:r7H14OA9kvJxPU2DZFBqq+J2kCNd/Bh9tMNxYbBnwZ2z5ckOErGv9rKsO3+MLmhQDZ88jz1yHfHqcGYaacaSPI9XvznsLPMX5TDrJHUX5qByddEpSSjc8cDSd89ZRxA+uTQdmuMGaB7R9pigpXNfRa8ZDrUTKjIjHVYKvET/vTE=,iv:L4cM1ap9brBqK4eXfeg/uozE5zwQhBe4E0ItEVxrdSI=,tag:UHZWCVXGrfp3JN5s+wJUAA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
