package services.identity

import java.nio.charset.StandardCharsets

/** The code the resolver is built from, as a version: the build's digest of the sources the compiler records the
 *  resolver and its store as reaching, and the data they read (`identity-rules-version.txt`, generated by `build.sbt`
 *  through `project/IdentityRulesSources.scala`; the digested paths in `identity-rules-sources.txt`). A constant of
 *  the build: a deploy that changes none of them keeps every stored family. */
object IdentityRules {
  val Resource = "/identity-rules-version.txt"

  lazy val codeVersion: String =
    Option(getClass.getResourceAsStream(Resource)).fold("unknown") { stream =>
      try new String(stream.readAllBytes(), StandardCharsets.UTF_8).trim finally stream.close()
    }
}
