package services.identity

import java.nio.charset.StandardCharsets

/** The code the resolver is built from, as a version: the build's digest of common's sources and
 *  resources (`identity-rules-version.txt`, generated by `build.sbt`). A constant of the build. */
object IdentityRules {
  val Resource = "/identity-rules-version.txt"

  lazy val codeVersion: String =
    Option(getClass.getResourceAsStream(Resource)).fold("unknown") { stream =>
      try new String(stream.readAllBytes(), StandardCharsets.UTF_8).trim finally stream.close()
    }
}
