package services.titlerules

import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.should.Matchers
import services.movies.TitleNormalizer.normalize

import java.nio.file.{Files, Paths}
import scala.jdk.CollectionConverters._

/**
 * Replays the REAL long-tail of production titles (a checked-in snapshot of the
 * prod `movies` collection, generated by `SnapshotProdTitlesToFixture`) through
 * the rule engine and asserts byte-identity with the frozen legacy
 * normalisation. This is the "tests generated from prod db" guarantee: it
 * catches any rule that drifts from the original behaviour on titles the curated
 * corpus doesn't cover.
 *
 * Hermetic: if the fixture is absent (no snapshot has been pulled), the test
 * cancels rather than failing, so CI stays green without a prod dependency.
 */
class ProdTitlesNormalizationSpec extends AnyFlatSpec with Matchers {

  private val rs       = TitleRuleDefaults.ruleSet
  private val fixture  = Paths.get("common/src/test/resources/fixtures/prod-movies/titles.txt")

  private def sanitize(t: String): String =
    tools.TextNormalization.deburr(rs.canonical(normalize(t)))
      .toLowerCase.replaceAll("[^\\p{L}\\p{N}]+", "")

  private def titles: Seq[String] =
    if (!Files.exists(fixture)) Seq.empty
    else Files.readAllLines(fixture).asScala.toSeq.filter(_.nonEmpty)

  "the default rules" should "match the frozen legacy normalisation for every prod title" in {
    val ts = titles
    if (ts.isEmpty) cancel("prod-movies fixture absent — run tools.SnapshotProdTitlesToFixture")
    ts.foreach { t =>
      withClue(s"searchTitle('$t'): ")(rs.structural(t) shouldBe FrozenLegacyNormalizer.searchTitle(t))
      withClue(s"apiQuery('$t'): ")(rs.search(t) shouldBe FrozenLegacyNormalizer.apiQuery(t))
      withClue(s"sanitize('$t'): ")(sanitize(t) shouldBe FrozenLegacyNormalizer.sanitize(t))
      withClue(s"programmePrefix('$t'): ")(rs.programmePrefix(t) shouldBe FrozenLegacyNormalizer.programmePrefix(t))
    }
  }
}
