package tools

import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.should.Matchers

import scala.jdk.CollectionConverters.*

/** The worker's AOT class list (`aot-classes.txt`, generated by scripts/aot-class-list.py from
 *  production heap dumps) is what the image's cache archives. A class it names that the code no
 *  longer has is simply not archived; a class the code gained since loads into metaspace instead.
 *  Both are harmless one at a time and costly in bulk, so this holds the list to the code: when
 *  too many of its application classes are gone, the list is stale — regenerate it from fresh dumps
 *  (the script's header says how). */
class AotClassListSpec extends AnyFlatSpec with Matchers {

  private val listed = {
    val stream = getClass.getResourceAsStream(ClassArchiveTraining.ClassListResource)
    withClue(s"the worker's classpath carries no ${ClassArchiveTraining.ClassListResource}: ")(stream should not be null)
    ClassArchiveTraining.classList(try new String(stream.readAllBytes(), "UTF-8") finally stream.close())
  }

  /** The packages the worker's own code lives in: what drifts with every change. */
  private val AppPackages = Seq("services.", "models.", "clients.", "tools.", "modules.", "controllers.", "settings.")

  /** How many of the list's application classes may be gone before it counts as stale. */
  val StaleShare = 0.05

  "the worker's AOT class list" should "name only real binary class names, sorted and distinct" in {
    listed should not be empty
    listed.filterNot(_.matches("""[\p{L}_$][\p{L}\p{N}_$]*(\.[\p{L}_$][\p{L}\p{N}_$]*)*""")) shouldBe empty
    listed shouldBe listed.distinct.sorted
  }

  it should s"still name classes the worker has, all but ${(StaleShare * 100).toInt}% of its own" in {
    val own     = listed.filter(name => AppPackages.exists(name.startsWith))
    val loaded  = ClassArchiveTraining.load(own, getClass.getClassLoader)
    val missing = own.filter(name => scala.util.Try(Class.forName(name, false, getClass.getClassLoader)).isFailure)
    info(s"${own.size} application classes listed, ${missing.size} gone: ${missing.take(10).mkString(", ")}")
    withClue(s"${loaded.failed} of ${own.size} listed application classes are gone — the list is stale; " +
      "regenerate it: scripts/aot-class-list.py <fresh heap dumps> > worker/src/main/resources/aot-classes.txt: ") {
      loaded.failed.toDouble should be <= own.size * StaleShare
    }
  }

  /** The other direction: code the list has not caught up with. Scrapers are where one country's
   *  classes differ from another's — and where no heap dump may have seen them yet — so every class
   *  the worker has under `services.cinemas` must be listed. One missing is a scraper added since
   *  the list was made: refresh it with `--keep` (scripts/aot-class-list.py says how), no dump needed. */
  it should "name every scraper class the worker has" in {
    val root = java.nio.file.Paths.get(classOf[services.cinemas.CinemaScraperCatalog].getProtectionDomain.getCodeSource.getLocation.toURI)
    val scrapers = root.resolve("services/cinemas")
    withClue(s"$root is not a class directory: ")(java.nio.file.Files.isDirectory(scrapers) shouldBe true)
    val classes = java.nio.file.Files.walk(scrapers).iterator.asScala.map(root.relativize(_).toString)
      .filter(_.endsWith(".class")).map(_.stripSuffix(".class").replace('/', '.').replace('\\', '.')).toSeq
    classes should not be empty
    val listedSet = listed.toSet
    val missing   = classes.filterNot(listedSet).sorted
    withClue(s"${missing.size} scraper class(es) the AOT class list lacks (${missing.take(5).mkString(", ")}) — refresh it: " +
      "scripts/aot-class-list.py --keep worker/src/main/resources/aot-classes.txt --package " +
      "worker/target/scala-3.9.0/worker_3-1.0-SNAPSHOT.jar:services.cinemas. > /tmp/aot-classes.txt && mv /tmp/aot-classes.txt worker/src/main/resources/aot-classes.txt: ") {
      missing shouldBe empty
    }
  }
}
