package tools

/**
 * The client reads that still swallow a failed read or parse into "no data" and have not
 * moved onto `tools.HttpRead` / `ReadOutcome` yet — the migration backlog for
 * [[NoSwallowedFailureSpec]]'s shape 3 (and Helios's `"[]"` fallback). Every entry is
 * `TODO-HttpRead`: no reason is claimed for it, it is simply not migrated. Migrating a site
 * removes its entry (the spec's stale-entry check insists); nothing new may be added here.
 */
object HttpReadBacklog {

  val Swallows: Map[(String, String, String), String] = Map(
    ("worker/src/main/scala/services/TmdbClient.scala", "details",
      "Try(httpGet(detailsUrl(tmdbId), auth))") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/TmdbClient.scala", "fullDetails",
      "Try(httpGet(fullDetailsUrl(tmdbId), auth))") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/common/GatsbyBoxOfficeParser.scala", "parseDetails",
      "Try(Json.parse(json)).toOption.flatMap(_.asOpt[Seq[JsValue]]).getOrElse(Nil).flatMap { n =>") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/common/WebediaShowtimesClient.scala", "fetchChunk",
      "Try(http.get(showtimesUrl(market.host, theaterId, date, p))).toOption.toSeq") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/common/WebediaShowtimesClient.scala", "parsePage",
      "val js = Try(Json.parse(json)).getOrElse(JsNull)") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/es/OcineParser.scala", "filmIds",
      "val root = Try(Json.parse(json)).getOrElse(JsNull)") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/pl/BiletynaClient.scala", "parseEvents",
      "Try(Json.parse(block)).toOption.toSeq.flatMap { json =>") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/pl/BiletynaClient.scala", "pageEventCount",
      "Try(Json.parse(block)).toOption.flatMap(json => (json \\ \"events\").asOpt[JsArray]).fold(0)(_.value.size)") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/pl/BokClient.scala", "fetch",
      "Try(http.get(url)).toOption") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/pl/CharlieClient.scala", "parseEvent",
      "Try(Json.parse(block)).toOption") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/pl/CharlieMonroeClient.scala", "fetchDetailFactsFor",
      "Try(http.get(detailUrl)).toOption") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/pl/CharlieMonroeClient.scala", "parseHtml",
      ".flatMap(element => Try(Json.parse(element.data())).toOption)") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/pl/Cinema1Client.scala", "fetch",
      "val roomByScreen = Try(http.get(screenHeadUrl(cinemaId))).toOption.map(parseScreenHeads).getOrElse(Map.empty)") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/pl/Cinema1Client.scala", "fetch",
      "Try(http.get(movieUrl(id))).toOption.flatMap(parseMovie)") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/pl/CinemaCityClient.scala", "parseDetails",
      "val js  = FilmDetailsRe.findFirstMatchIn(html).flatMap(m => Try(Json.parse(m.group(1))).toOption)") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/pl/FalenicaClient.scala", "fetch",
      "Try(http.get(url)).toOption.map(Jsoup.parse)") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/pl/FilmwebShowtimesClient.scala", "resolveSourceUrl",
      "Try(http.get(cinemaInfoUrl(cinemaId))).toOption.flatMap(parseCinemaInfo)") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/pl/FilmwebShowtimesClient.scala", "fetch",
      "Try(http.get(url)).toOption.flatMap(parseFilmInfo)") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/pl/FilmwebShowtimesClient.scala", "parseFilmInfo",
      "Try(Json.parse(json)).toOption.map { j =>") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/pl/FilmwebShowtimesClient.scala", "parseCinemaInfo",
      "Try(Json.parse(body)).toOption.flatMap { js =>") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/pl/HeliosClient.scala", "fetchRestData",
      "val regular         = screeningsUrls.map(u => parseApiScreenings(Try(http.get(u)).getOrElse(\"[]\"))).reduce(_ ++ _)") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/pl/HeliosClient.scala", "fetchRestData",
      "val eventScreenings = eventsUrls.map(u => parseEventScreenings(Try(http.get(u)).getOrElse(\"[]\"))).reduce(_ ++ _)") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/pl/HeliosClient.scala", "fetchRestData",
      "Try((Json.parse(body) \\ \"name\").asOpt[String]).toOption.flatten.map(id -> _)") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/pl/HeliosClient.scala", "parseApiMovieBody",
      "Try(Json.parse(body)).toOption.flatMap { js =>") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/pl/HeliosClient.scala", "fetchBodies",
      "Try(detailFetch.get(url)).toOption") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/pl/KinoAurumClient.scala", "parse",
      "val documents = (Try(Json.parse(json)).toOption.getOrElse(JsNull) \\ \"documents\")") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/pl/KinoBajkaClient.scala", "parseHtml",
      ".flatMap(s => Try(Json.parse(s)).toOption)") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/pl/KinoDianaClient.scala", "parseFeed",
      "val records = Try(Json.parse(body)).toOption.collect { case a: JsArray => a.value.toSeq }") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/pl/KinoIskraClient.scala", "fetch",
      "Try(record(http.get(url))).toOption).flatMap((id, r) => r.map(id -> _))") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/pl/KinoJednoscClient.scala", "fetch",
      "Try(http.get(url)).toOption.map(parseShowtimes)") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/pl/KinoKulturaClient.scala", "fetch",
      "Try(http.get(url)).toOption") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/pl/KinoMuzeumGdanskClient.scala", "fetchUnfiltered",
      "Try(http.get(url)).toOption") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/pl/KinoParczewClient.scala", "fetch",
      "Try(http.get(url)).toOption.flatMap(KinoParczewClient.parseFilm(_, url, cinema))") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/pl/KinoSfinksClient.scala", "fetch",
      "Try(Jsoup.parse(http.get(url))).toOption") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/pl/KinoSokolSokolkaClient.scala", "fetchUnfiltered",
      "Try(http.get(url)).toOption.flatMap(parseStartTime)") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/pl/KinoTatryClient.scala", "fetch",
      "Try(http.get(url)).toOption.flatMap(yearOf)") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/pl/KinoZakClient.scala", "fetch",
      "Try(http.get(url)).toOption.map(parseDetail).getOrElse(Detail.empty)") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/pl/NoveKinoClient.scala", "fetchBare",
      "Try(http.get(url)).toOption") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/pl/NoweHoryzontyClient.scala", "listaHtml",
      "Try((Json.parse(body) \\ \"lista\").asOpt[String]).toOption.flatten.filter(_.trim.nonEmpty)") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/pl/PromKepaClient.scala", "fetch",
      "Try(http.get(url)).toOption") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/pl/RialtoClient.scala", "fetchBare",
      "Try(http.get(url)).toOption.map(html => EventData(parseEventPage(html), parseGenres(html)))") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/pl/SdkClient.scala", "fetch",
      "Try(http.get(url)).toOption.map(Jsoup.parse)") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/pl/TeatrZiemiRybnickiejClient.scala", "fetch",
      "Try(http.get(url)).toOption.flatMap(html => parseDetail(html, url))") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/pl/UjazdowskiClient.scala", "slotsFor",
      "html <- Try(http.get(s\"$ListingUrl/week.ajax?ut=$ut\")).toOption") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/uk/CineworldParser.scala", "parseMovieDetail",
      "Try(Json.parse(json)).toOption") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/us/AlamoDrafthouseParser.scala", "parse",
      "val data          = (Try(Json.parse(json)).getOrElse(JsNull) \\ \"data\")") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/us/AmcParser.scala", "items",
      "val parsed = Try(Json.parse(json)).getOrElse(") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/cinemas/us/RegalParser.scala", "body",
      "Try(Json.parse(json)).getOrElse(") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/enrichment/scraping/JsonLdAggregateRating.scala", "of",
      "def of(html: String): JsonLd = JsonLd(scripts(html).flatMap(raw => Try(Json.parse(raw)).toOption))") -> "TODO-HttpRead",
    ("worker/src/main/scala/services/enrichment/scraping/RottenTomatoesScorecard.scala", "criticsScore",
      "Try(Json.parse(raw)).toOption.toSeq.flatMap { js =>") -> "TODO-HttpRead"
  )

  /** The client files that still call an `HttpFetch` directly — the migration backlog for
   *  [[ClientReadsThroughHttpReadSpec]]. Every entry is `TODO-HttpRead`. */
  val NotYetMigrated: Map[String, String] = Map(
    "worker/src/main/scala/services/TmdbClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/common/DayPickerProgramme.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/common/FlicksClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/common/GatsbyBoxOfficeClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/common/KinoprogrammClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/common/VueCinemasPlatformClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/common/WebediaShowtimesClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/es/OcineClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/AlternatywyClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/AmondoClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/ArtKinoKrosnoClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/Bilety24Client.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/Bilety24OrganizerClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/Bilety24SubdomainClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/BiletynaClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/BiletynaNationalFeed.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/BokClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/CharlieClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/CharlieMonroeClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/Cinema1Client.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/CinemaCityClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/CyfroweKinoClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/CytadelaClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/DcfClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/DomKulturyLapyClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/EkobiletClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/FalenicaClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/FilmwebCinemaIdResolver.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/FilmwebShowtimesClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/GdynskieCentrumFilmoweClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/HeliosClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/IksorisBookingClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/IksorisCalendarClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/IluzjonClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KdkKrapkowiceClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinematografLodzClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoAgrafkaClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoAmokClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoApolloClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoAurumClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoAwangarda2Client.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoBajkaBlonieClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoBajkaClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoBielskClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoBulgarskaClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoCentrum3DPrzemyslClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoCentrumCswClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoChatkaZakaClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoDKFRumcajsClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoDianaClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoEvaClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoFenomenClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoForumClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoGrajfkaClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoGramClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoGrunwaldClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoGwiazdaKetrzynClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoIkmClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoIskraClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoJOKClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoJednoscClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoKadrTomaszowLubelskiClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoKarolinkaClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoKijowClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoKikaClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoKreskaClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoKulturaChojnowClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoKulturaClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoLotSwidnikClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoLukowClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoMDKMyszkowClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoMarzenieClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoMetalowiecNowaDebaClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoMoskwaClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoMuzaClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoMuzeumGdanskClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoNarewClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoNowaFalaClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoOrzelClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoPalacoweClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoParadoxClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoParczewClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoPatriaClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoPodBaranamiClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoPortClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoPromienClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoRemusClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoRomaClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoRomaRawaClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoScenaKulturaClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoSfinksClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoSlezaClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoSokolBrzozowClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoSokolSokolkaClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoSokolStrzyzowClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoSpektrumClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoSpojniaClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoStudioClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoStylowyClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoSwiatowidElblagClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoTatryClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoTomiClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoWarsClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoZaRogiemCafeClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoZaRogiemSiedlecClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoZaciszeClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoZakClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoZamekClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoZbyszekClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinoZorzaClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinomuzeumClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/KinotekaClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/McswElektrowniaCinemaClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/ModernEventsCalendarClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/MsiClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/MultikinoClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/MuranowClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/NckfClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/NoveKinoClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/NoweHoryzontyClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/OkfIluzjaClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/PionierClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/PrahaClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/PromKepaClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/RialtoClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/SckStargardClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/SdkClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/SwitClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/SystemBiletowyClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/TeatrZiemiRybnickiejClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/UjazdowskiClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/pl/VisualTicketClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/uk/CineworldClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/uk/OdeonClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/uk/TheOldCourtClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/us/AlamoDrafthouseClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/us/AmcClient.scala" -> "TODO-HttpRead",
    "worker/src/main/scala/services/cinemas/us/RegalClient.scala" -> "TODO-HttpRead"
  )
}
