import Foundation

/// A city the app can show a repertoire for. The server hosts every page
/// and API under a `/{slug}/…` prefix, so the slug is what the networking
/// layer splices into the repertoire / details URLs; `name` is the display
/// label; `lat`/`lon` drive the nearest-city pick on first launch.
///
/// Pure Foundation — no SwiftUI / CoreLocation — so it lives in `KinowoCore`
/// and the haversine pick is unit-testable cross-platform (`swift test`
/// on Linux CI).
struct City: Codable, Hashable {
    let slug: String
    let name: String
    let lat: Double
    let lon: Double
    /// ISO country code (`"PL"`, `"GB"`) matching `Country.code`. The app is
    /// multi-country: every city picker, the nearest-city gate, and the default
    /// city are scoped to the SELECTED country's cities, so a UK user browses UK
    /// regions and a Polish user browses Polish cities — never a mix.
    let country: String
    /// The group this city is picked under, where its country groups them at all
    /// — a US state ("California"), a UK nation ("Scotland") — and `nil` in the
    /// countries that group nothing. Neither 468 US places nor 79 UK counties in
    /// one A-to-Z is a list anybody reads, so the picker asks for the group
    /// first; a country without regions keeps the single flat list.
    ///
    /// Carried by `/api/catalog` (and the bundled seed). A `var` with a default
    /// so the memberwise init stays usable by the hand-written `all` rows below,
    /// and so a catalog from an older server still decodes.
    var region: String? = nil

    /// The SECOND-level group `region` sits under a further split, where that
    /// split actually holds more than one city — the UK's West Midlands
    /// (Birmingham/Dudley/Sandwell), Glamorgan (Cardiff/Glamorgan) and Antrim
    /// (Antrim/Belfast). `nil` everywhere else: a county that collapsed onto its
    /// one place reads correctly through `region` alone (Cheshire needs no
    /// third tap to reach Cheshire), and Germany/the US never nest this deep.
    ///
    /// Carried by `/api/catalog` (and the bundled seed), same shape as `region`.
    var subregion: String? = nil

    /// This city's own IANA zone, where it differs from its country's; `nil`
    /// otherwise — which is every city of the four countries that keep one zone
    /// throughout, so the field costs nothing there.
    ///
    /// The US spans SIX zones and fifteen of its states straddle a boundary, so a
    /// single country zone is wrong for most of it: pruning a Knoxville showtime
    /// on the country's Pacific drops it three hours early. Resolve through
    /// [`zone(fallback:)`], never by reading this directly.
    ///
    /// Carried by `/api/catalog` (and the bundled seed), same shape as `region`:
    /// a `var` with a default so the memberwise init stays usable by the
    /// hand-written `all` rows below, and so a catalog from an older server —
    /// or any city of a single-zone country — still decodes.
    var timezone: String? = nil

    /// The wall-clock this city's showtimes are listed on: its own zone when the
    /// catalog gave it one, else the country's. Past-showtime pruning and the
    /// Dziś/Jutro buckets reason in this, so it has to be the CITY's — a country
    /// only has one to offer and the US needs six.
    func zone(fallback: TimeZone) -> TimeZone {
        timezone.flatMap { TimeZone(identifier: $0) } ?? fallback
    }

    /// Every city the app knows about across ALL countries, in the same order
    /// the web `City.all` lists them (Polish cities first, then the UK regions)
    /// so the pickers read identically across platforms. The data-driven rosters
    /// — Germany's 158 regions and the US's 55 states/territories — are NOT
    /// mirrored here: they arrive with the catalog (bundled seed, then the live
    /// `/api/catalog`), so there is one copy of them rather than two that drift. This is the GLOBAL
    /// union; the pickers and the nearest-city gate scope it to the selected
    /// country via `cities(in:)` / `matching(_:in:)` / `nearestWithin100km(...in:)`.
    /// Adding a row here (with its `country`) is the only model-side change a new
    /// city needs.
    static let all: [City] = [
        // ── Poland: GENERATED by data/pl/scripts/generate_polish_pages.py — do not edit by hand.
        City(slug: "poznan", name: "Poznań", lat: 52.4064, lon: 16.9252, country: "pl", region: "Wielkopolskie"),
        City(slug: "wroclaw", name: "Wrocław", lat: 51.1079, lon: 17.0385, country: "pl", region: "Dolnośląskie"),
        City(slug: "warszawa", name: "Warszawa", lat: 52.2297, lon: 21.0122, country: "pl", region: "Mazowieckie"),
        City(slug: "krakow", name: "Kraków", lat: 50.0647, lon: 19.9450, country: "pl", region: "Małopolskie"),
        City(slug: "lodz", name: "Łódź", lat: 51.7592, lon: 19.4560, country: "pl", region: "Łódzkie"),
        City(slug: "katowice", name: "Katowice", lat: 50.2649, lon: 19.0238, country: "pl", region: "Śląskie"),
        City(slug: "szczecin", name: "Szczecin", lat: 53.4285, lon: 14.5528, country: "pl", region: "Zachodniopomorskie"),
        City(slug: "bialystok", name: "Białystok", lat: 53.1325, lon: 23.1688, country: "pl", region: "Podlaskie"),
        City(slug: "trojmiasto", name: "Trójmiasto", lat: 54.4416, lon: 18.5601, country: "pl", region: "Pomorskie"),
        City(slug: "bydgoszcz", name: "Bydgoszcz", lat: 53.1235, lon: 18.0084, country: "pl", region: "Kujawsko-pomorskie"),
        City(slug: "lublin", name: "Lublin", lat: 51.2465, lon: 22.5684, country: "pl", region: "Lubelskie"),
        City(slug: "czestochowa", name: "Częstochowa", lat: 50.8118, lon: 19.1203, country: "pl", region: "Śląskie"),
        City(slug: "radom", name: "Radom", lat: 51.4027, lon: 21.1471, country: "pl", region: "Mazowieckie"),
        City(slug: "sosnowiec", name: "Sosnowiec", lat: 50.2863, lon: 19.1041, country: "pl", region: "Śląskie"),
        City(slug: "torun", name: "Toruń", lat: 53.0138, lon: 18.5984, country: "pl", region: "Kujawsko-pomorskie"),
        City(slug: "kielce", name: "Kielce", lat: 50.8661, lon: 20.6286, country: "pl", region: "Świętokrzyskie"),
        City(slug: "rzeszow", name: "Rzeszów", lat: 50.0413, lon: 21.9990, country: "pl", region: "Podkarpackie"),
        City(slug: "gliwice", name: "Gliwice", lat: 50.2945, lon: 18.6714, country: "pl", region: "Śląskie"),
        City(slug: "zabrze", name: "Zabrze", lat: 50.3249, lon: 18.7857, country: "pl", region: "Śląskie"),
        City(slug: "olsztyn", name: "Olsztyn", lat: 53.7784, lon: 20.4801, country: "pl", region: "Warmińsko-mazurskie"),
        City(slug: "bielsko-biala", name: "Bielsko-Biała", lat: 49.8224, lon: 19.0584, country: "pl", region: "Śląskie"),
        City(slug: "opole", name: "Opole", lat: 50.6751, lon: 17.9213, country: "pl", region: "Opolskie"),
        City(slug: "rybnik", name: "Rybnik", lat: 50.0971, lon: 18.5416, country: "pl", region: "Śląskie"),
        City(slug: "gorzow-wielkopolski", name: "Gorzów Wielkopolski", lat: 52.7368, lon: 15.2288, country: "pl", region: "Lubuskie"),
        City(slug: "elblag", name: "Elbląg", lat: 54.1522, lon: 19.4088, country: "pl", region: "Warmińsko-mazurskie"),
        City(slug: "koszalin", name: "Koszalin", lat: 54.1943, lon: 16.1722, country: "pl", region: "Zachodniopomorskie"),
        City(slug: "kalisz", name: "Kalisz", lat: 51.7611, lon: 18.0911, country: "pl", region: "Wielkopolskie"),
        City(slug: "zielona-gora", name: "Zielona Góra", lat: 51.9356, lon: 15.5062, country: "pl", region: "Lubuskie"),
        City(slug: "tychy", name: "Tychy", lat: 50.1357, lon: 18.9985, country: "pl", region: "Śląskie"),
        City(slug: "walbrzych", name: "Wałbrzych", lat: 50.7714, lon: 16.2845, country: "pl", region: "Dolnośląskie"),
        City(slug: "tarnow", name: "Tarnów", lat: 50.0121, lon: 20.9858, country: "pl", region: "Małopolskie"),
        City(slug: "wloclawek", name: "Włocławek", lat: 52.6483, lon: 19.0677, country: "pl", region: "Kujawsko-pomorskie"),
        City(slug: "legnica", name: "Legnica", lat: 51.2070, lon: 16.1619, country: "pl", region: "Dolnośląskie"),
        City(slug: "plock", name: "Płock", lat: 52.5468, lon: 19.7064, country: "pl", region: "Mazowieckie"),
        City(slug: "bytom", name: "Bytom", lat: 50.3483, lon: 18.9157, country: "pl", region: "Śląskie"),
        City(slug: "dabrowa-gornicza", name: "Dąbrowa Górnicza", lat: 50.3219, lon: 19.1876, country: "pl", region: "Śląskie"),
        City(slug: "nowy-sacz", name: "Nowy Sącz", lat: 49.6175, lon: 20.7154, country: "pl", region: "Małopolskie"),
        City(slug: "slupsk", name: "Słupsk", lat: 54.4641, lon: 17.0287, country: "pl", region: "Pomorskie"),
        City(slug: "jelenia-gora", name: "Jelenia Góra", lat: 50.9044, lon: 15.7197, country: "pl", region: "Dolnośląskie"),
        City(slug: "przemysl", name: "Przemyśl", lat: 49.7838, lon: 22.7677, country: "pl", region: "Podkarpackie"),
        City(slug: "konin", name: "Konin", lat: 52.2230, lon: 18.2511, country: "pl", region: "Wielkopolskie"),
        City(slug: "augustow", name: "Augustów", lat: 53.8432, lon: 22.9798, country: "pl", region: "Podlaskie"),
        City(slug: "belchatow", name: "Bełchatów", lat: 51.3688, lon: 19.3567, country: "pl", region: "Łódzkie"),
        City(slug: "biala-podlaska", name: "Biała Podlaska", lat: 52.0324, lon: 23.1165, country: "pl", region: "Lubelskie"),
        City(slug: "bielsk-podlaski", name: "Bielsk Podlaski", lat: 52.7651, lon: 23.1865, country: "pl", region: "Podlaskie"),
        City(slug: "bilgoraj", name: "Biłgoraj", lat: 50.5411, lon: 22.7220, country: "pl", region: "Lubelskie"),
        City(slug: "bochnia", name: "Bochnia i okolice", lat: 49.9691, lon: 20.4303, country: "pl", region: "Małopolskie"),
        City(slug: "boleslawiec", name: "Bolesławiec i okolice", lat: 51.2642, lon: 15.5697, country: "pl", region: "Dolnośląskie"),
        City(slug: "braniewo", name: "Braniewo", lat: 54.3797, lon: 19.8196, country: "pl", region: "Warmińsko-mazurskie"),
        City(slug: "brzeg", name: "Brzeg", lat: 50.8608, lon: 17.4674, country: "pl", region: "Opolskie"),
        City(slug: "brzeg-dolny", name: "Brzeg Dolny i okolice", lat: 51.2730, lon: 16.7081, country: "pl", region: "Dolnośląskie"),
        City(slug: "busko-zdroj", name: "Busko-Zdrój i okolice", lat: 50.4708, lon: 20.7188, country: "pl", region: "Świętokrzyskie"),
        City(slug: "chelm", name: "Chełm", lat: 51.1431, lon: 23.4716, country: "pl", region: "Lubelskie"),
        City(slug: "chojnice", name: "Chojnice i okolice", lat: 53.6955, lon: 17.5570, country: "pl", region: "Pomorskie"),
        City(slug: "choszczno", name: "Choszczno i okolice", lat: 53.1690, lon: 15.4205, country: "pl", region: "Zachodniopomorskie"),
        City(slug: "ciechanow", name: "Ciechanów i okolice", lat: 52.8814, lon: 20.6200, country: "pl", region: "Mazowieckie"),
        City(slug: "czechowice-dziedzice", name: "Czechowice-Dziedzice i okolice", lat: 49.9134, lon: 19.0048, country: "pl", region: "Śląskie"),
        City(slug: "dabrowa-tarnowska", name: "Dąbrowa Tarnowska i okolice", lat: 50.1746, lon: 20.9863, country: "pl", region: "Małopolskie"),
        City(slug: "elk", name: "Ełk", lat: 53.8282, lon: 22.3647, country: "pl", region: "Warmińsko-mazurskie"),
        City(slug: "gizycko", name: "Giżycko i okolice", lat: 54.0381, lon: 21.7644, country: "pl", region: "Warmińsko-mazurskie"),
        City(slug: "glogow", name: "Głogów", lat: 51.6636, lon: 16.0845, country: "pl", region: "Dolnośląskie"),
        City(slug: "gniezno", name: "Gniezno i okolice", lat: 52.5348, lon: 17.5826, country: "pl", region: "Wielkopolskie"),
        City(slug: "goldap", name: "Gołdap", lat: 54.3063, lon: 22.3036, country: "pl", region: "Warmińsko-mazurskie"),
        City(slug: "grajewo", name: "Grajewo", lat: 53.6473, lon: 22.4554, country: "pl", region: "Podlaskie"),
        City(slug: "grudziadz", name: "Grudziądz i okolice", lat: 53.4841, lon: 18.7537, country: "pl", region: "Kujawsko-pomorskie"),
        City(slug: "hrubieszow", name: "Hrubieszów", lat: 50.8050, lon: 23.8925, country: "pl", region: "Lubelskie"),
        City(slug: "ilawa", name: "Iława i okolice", lat: 53.5960, lon: 19.5685, country: "pl", region: "Warmińsko-mazurskie"),
        City(slug: "inowroclaw", name: "Inowrocław i okolice", lat: 52.7989, lon: 18.2639, country: "pl", region: "Kujawsko-pomorskie"),
        City(slug: "jaroslaw", name: "Jarosław", lat: 50.0162, lon: 22.6778, country: "pl", region: "Podkarpackie"),
        City(slug: "jaslo", name: "Jasło i okolice", lat: 49.7451, lon: 21.4725, country: "pl", region: "Podkarpackie"),
        City(slug: "jastrzebie-zdroj", name: "Jastrzębie-Zdrój i okolice", lat: 49.9554, lon: 18.5748, country: "pl", region: "Śląskie"),
        City(slug: "jaworzno", name: "Jaworzno i okolice", lat: 50.2053, lon: 19.2750, country: "pl", region: "Śląskie"),
        City(slug: "kedzierzyn-kozle", name: "Kędzierzyn-Koźle", lat: 50.3498, lon: 18.2261, country: "pl", region: "Opolskie"),
        City(slug: "kepno", name: "Kępno i okolice", lat: 51.2784, lon: 17.9891, country: "pl", region: "Wielkopolskie"),
        City(slug: "klodzko", name: "Kłodzko i okolice", lat: 50.4349, lon: 16.6614, country: "pl", region: "Dolnośląskie"),
        City(slug: "kluczbork", name: "Kluczbork", lat: 50.9728, lon: 18.2182, country: "pl", region: "Opolskie"),
        City(slug: "kolobrzeg", name: "Kołobrzeg i okolice", lat: 54.1756, lon: 15.5834, country: "pl", region: "Zachodniopomorskie"),
        City(slug: "koscierzyna", name: "Kościerzyna i okolice", lat: 54.1223, lon: 17.9812, country: "pl", region: "Pomorskie"),
        City(slug: "krapkowice", name: "Krapkowice", lat: 50.4751, lon: 17.9654, country: "pl", region: "Opolskie"),
        City(slug: "krasnik", name: "Kraśnik i okolice", lat: 50.9236, lon: 22.2271, country: "pl", region: "Lubelskie"),
        City(slug: "krasnystaw", name: "Krasnystaw", lat: 50.9846, lon: 23.1742, country: "pl", region: "Lubelskie"),
        City(slug: "krosno", name: "Krosno", lat: 49.6887, lon: 21.7706, country: "pl", region: "Podkarpackie"),
        City(slug: "krotoszyn", name: "Krotoszyn i okolice", lat: 51.6987, lon: 17.4374, country: "pl", region: "Wielkopolskie"),
        City(slug: "krynica-zdroj", name: "Krynica-Zdrój i okolice", lat: 49.4222, lon: 20.9594, country: "pl", region: "Małopolskie"),
        City(slug: "kutno", name: "Kutno i okolice", lat: 52.2306, lon: 19.3641, country: "pl", region: "Łódzkie"),
        City(slug: "lapy", name: "Łapy", lat: 52.9911, lon: 22.8842, country: "pl", region: "Podlaskie"),
        City(slug: "leba", name: "Łeba", lat: 54.7610, lon: 17.5555, country: "pl", region: "Pomorskie"),
        City(slug: "legionowo", name: "Legionowo i okolice", lat: 52.4015, lon: 20.9266, country: "pl", region: "Mazowieckie"),
        City(slug: "leszno", name: "Leszno", lat: 51.8403, lon: 16.5749, country: "pl", region: "Wielkopolskie"),
        City(slug: "lidzbark-warminski", name: "Lidzbark Warmiński", lat: 54.1259, lon: 20.5795, country: "pl", region: "Warmińsko-mazurskie"),
        City(slug: "lipno", name: "Lipno i okolice", lat: 52.8444, lon: 19.1785, country: "pl", region: "Kujawsko-pomorskie"),
        City(slug: "lomza", name: "Łomża i okolice", lat: 53.1781, lon: 22.0593, country: "pl", region: "Podlaskie"),
        City(slug: "lubin", name: "Lubin", lat: 51.4009, lon: 16.2015, country: "pl", region: "Dolnośląskie"),
        City(slug: "lubliniec", name: "Lubliniec", lat: 50.6690, lon: 18.6844, country: "pl", region: "Śląskie"),
        City(slug: "lukow", name: "Łuków", lat: 51.9290, lon: 22.3796, country: "pl", region: "Lubelskie"),
        City(slug: "miechow", name: "Miechów i okolice", lat: 50.3565, lon: 20.0279, country: "pl", region: "Małopolskie"),
        City(slug: "miedzyrzec-podlaski", name: "Międzyrzec Podlaski", lat: 51.9864, lon: 22.7825, country: "pl", region: "Lubelskie"),
        City(slug: "miedzyrzecz", name: "Międzyrzecz", lat: 52.4446, lon: 15.5780, country: "pl", region: "Lubuskie"),
        City(slug: "miedzyzdroje", name: "Międzyzdroje", lat: 53.9292, lon: 14.4510, country: "pl", region: "Zachodniopomorskie"),
        City(slug: "mielec", name: "Mielec i okolice", lat: 50.2871, lon: 21.4239, country: "pl", region: "Podkarpackie"),
        City(slug: "mlawa", name: "Mława i okolice", lat: 53.1128, lon: 20.3841, country: "pl", region: "Mazowieckie"),
        City(slug: "morag", name: "Morąg", lat: 53.9171, lon: 19.9260, country: "pl", region: "Warmińsko-mazurskie"),
        City(slug: "myszkow", name: "Myszków", lat: 50.5752, lon: 19.3246, country: "pl", region: "Śląskie"),
        City(slug: "naklo-nad-notecia", name: "Nakło nad Notecią i okolice", lat: 53.1421, lon: 17.6018, country: "pl", region: "Kujawsko-pomorskie"),
        City(slug: "nowa-sol", name: "Nowa Sól", lat: 51.8033, lon: 15.7170, country: "pl", region: "Lubuskie"),
        City(slug: "nowy-targ", name: "Nowy Targ i okolice", lat: 49.4778, lon: 20.0323, country: "pl", region: "Małopolskie"),
        City(slug: "nowy-tomysl", name: "Nowy Tomyśl i okolice", lat: 52.3195, lon: 16.1284, country: "pl", region: "Wielkopolskie"),
        City(slug: "nysa", name: "Nysa i okolice", lat: 50.4738, lon: 17.3344, country: "pl", region: "Opolskie"),
        City(slug: "olawa", name: "Oława", lat: 50.9466, lon: 17.2926, country: "pl", region: "Dolnośląskie"),
        City(slug: "olecko", name: "Olecko", lat: 54.0337, lon: 22.5070, country: "pl", region: "Warmińsko-mazurskie"),
        City(slug: "olesnica", name: "Oleśnica", lat: 51.2134, lon: 17.3899, country: "pl", region: "Dolnośląskie"),
        City(slug: "olsztynek", name: "Olsztynek", lat: 53.5837, lon: 20.2847, country: "pl", region: "Warmińsko-mazurskie"),
        City(slug: "opoczno", name: "Opoczno i okolice", lat: 51.3757, lon: 20.2783, country: "pl", region: "Łódzkie"),
        City(slug: "ostrow-mazowiecka", name: "Ostrów Mazowiecka", lat: 52.8025, lon: 21.8951, country: "pl", region: "Mazowieckie"),
        City(slug: "ostrow-wielkopolski", name: "Ostrów Wielkopolski", lat: 51.6550, lon: 17.8069, country: "pl", region: "Wielkopolskie"),
        City(slug: "ostrowiec-swietokrzyski", name: "Ostrowiec Świętokrzyski i okolice", lat: 50.9294, lon: 21.3852, country: "pl", region: "Świętokrzyskie"),
        City(slug: "oswiecim", name: "Oświęcim i okolice", lat: 50.0344, lon: 19.2104, country: "pl", region: "Małopolskie"),
        City(slug: "otwock", name: "Otwock i okolice", lat: 52.1058, lon: 21.2613, country: "pl", region: "Mazowieckie"),
        City(slug: "pabianice", name: "Pabianice", lat: 51.6645, lon: 19.3547, country: "pl", region: "Łódzkie"),
        City(slug: "parczew", name: "Parczew", lat: 51.6402, lon: 22.9006, country: "pl", region: "Lubelskie"),
        City(slug: "pila", name: "Piła i okolice", lat: 53.1514, lon: 16.7378, country: "pl", region: "Wielkopolskie"),
        City(slug: "piotrkow-trybunalski", name: "Piotrków Trybunalski", lat: 51.4055, lon: 19.7032, country: "pl", region: "Łódzkie"),
        City(slug: "police", name: "Police i okolice", lat: 53.5521, lon: 14.5718, country: "pl", region: "Zachodniopomorskie"),
        City(slug: "polkowice", name: "Polkowice", lat: 51.5039, lon: 16.0726, country: "pl", region: "Dolnośląskie"),
        City(slug: "pruszkow", name: "Pruszków i okolice", lat: 52.1707, lon: 20.8121, country: "pl", region: "Mazowieckie"),
        City(slug: "przeworsk", name: "Przeworsk i okolice", lat: 50.0591, lon: 22.4941, country: "pl", region: "Podkarpackie"),
        City(slug: "pulawy", name: "Puławy i okolice", lat: 51.4166, lon: 21.9694, country: "pl", region: "Lubelskie"),
        City(slug: "pultusk", name: "Pułtusk i okolice", lat: 52.7025, lon: 21.0828, country: "pl", region: "Mazowieckie"),
        City(slug: "radomsko", name: "Radomsko", lat: 51.0671, lon: 19.4448, country: "pl", region: "Łódzkie"),
        City(slug: "rawicz", name: "Rawicz i okolice", lat: 51.6095, lon: 16.8585, country: "pl", region: "Wielkopolskie"),
        City(slug: "ruda-slaska", name: "Ruda Śląska i okolice", lat: 50.2584, lon: 18.8563, country: "pl", region: "Śląskie"),
        City(slug: "rypin", name: "Rypin", lat: 53.0660, lon: 19.4094, country: "pl", region: "Kujawsko-pomorskie"),
        City(slug: "sanok", name: "Sanok i okolice", lat: 49.5557, lon: 22.2056, country: "pl", region: "Podkarpackie"),
        City(slug: "siedlce", name: "Siedlce", lat: 52.1677, lon: 22.2901, country: "pl", region: "Mazowieckie"),
        City(slug: "sierpc", name: "Sierpc", lat: 52.8568, lon: 19.6691, country: "pl", region: "Mazowieckie"),
        City(slug: "skierniewice", name: "Skierniewice", lat: 51.9549, lon: 20.1584, country: "pl", region: "Łódzkie"),
        City(slug: "slawno", name: "Sławno i okolice", lat: 54.3628, lon: 16.6789, country: "pl", region: "Zachodniopomorskie"),
        City(slug: "slubice", name: "Słubice", lat: 52.3509, lon: 14.5607, country: "pl", region: "Lubuskie"),
        City(slug: "slupca", name: "Słupca i okolice", lat: 52.2873, lon: 17.8719, country: "pl", region: "Wielkopolskie"),
        City(slug: "sokolka", name: "Sokółka", lat: 53.4072, lon: 23.5023, country: "pl", region: "Podlaskie"),
        City(slug: "sokolow-podlaski", name: "Sokołów Podlaski i okolice", lat: 52.4068, lon: 22.2531, country: "pl", region: "Mazowieckie"),
        City(slug: "srem", name: "Śrem i okolice", lat: 52.0887, lon: 17.0151, country: "pl", region: "Wielkopolskie"),
        City(slug: "stalowa-wola", name: "Stalowa Wola i okolice", lat: 50.5829, lon: 22.0533, country: "pl", region: "Podkarpackie"),
        City(slug: "stara-blotnica", name: "Stara Błotnica", lat: 51.5468, lon: 20.9748, country: "pl", region: "Mazowieckie"),
        City(slug: "starachowice", name: "Starachowice i okolice", lat: 51.0374, lon: 21.0713, country: "pl", region: "Świętokrzyskie"),
        City(slug: "stargard", name: "Stargard i okolice", lat: 53.3367, lon: 15.0499, country: "pl", region: "Zachodniopomorskie"),
        City(slug: "strzelin", name: "Strzelin", lat: 50.7816, lon: 17.0648, country: "pl", region: "Dolnośląskie"),
        City(slug: "suwalki", name: "Suwałki", lat: 54.1118, lon: 22.9309, country: "pl", region: "Podlaskie"),
        City(slug: "swidnica", name: "Świdnica i okolice", lat: 50.8438, lon: 16.4886, country: "pl", region: "Dolnośląskie"),
        City(slug: "swidnik", name: "Świdnik i okolice", lat: 51.2190, lon: 22.6962, country: "pl", region: "Lubelskie"),
        City(slug: "swiebodzin", name: "Świebodzin", lat: 52.2475, lon: 15.5335, country: "pl", region: "Lubuskie"),
        City(slug: "szamotuly", name: "Szamotuły i okolice", lat: 52.6120, lon: 16.5779, country: "pl", region: "Wielkopolskie"),
        City(slug: "szczecinek", name: "Szczecinek", lat: 53.7079, lon: 16.6994, country: "pl", region: "Zachodniopomorskie"),
        City(slug: "szczytno", name: "Szczytno", lat: 53.5626, lon: 20.9875, country: "pl", region: "Warmińsko-mazurskie"),
        City(slug: "tczew", name: "Tczew i okolice", lat: 54.0924, lon: 18.7779, country: "pl", region: "Pomorskie"),
        City(slug: "tomaszow-lubelski", name: "Tomaszów Lubelski", lat: 50.4477, lon: 23.4162, country: "pl", region: "Lubelskie"),
        City(slug: "tomaszow-mazowiecki", name: "Tomaszów Mazowiecki", lat: 51.5313, lon: 20.0085, country: "pl", region: "Łódzkie"),
        City(slug: "turek", name: "Turek i okolice", lat: 52.0155, lon: 18.5006, country: "pl", region: "Wielkopolskie"),
        City(slug: "wadowice", name: "Wadowice i okolice", lat: 49.8834, lon: 19.4929, country: "pl", region: "Małopolskie"),
        City(slug: "wagrowiec", name: "Wągrowiec i okolice", lat: 52.8084, lon: 17.1996, country: "pl", region: "Wielkopolskie"),
        City(slug: "wejherowo", name: "Wejherowo i okolice", lat: 54.6057, lon: 18.2356, country: "pl", region: "Pomorskie"),
        City(slug: "wielen", name: "Wieleń", lat: 52.8946, lon: 16.1714, country: "pl", region: "Wielkopolskie"),
        City(slug: "wieliczka", name: "Wieliczka i okolice", lat: 49.9874, lon: 20.0647, country: "pl", region: "Małopolskie"),
        City(slug: "wielun", name: "Wieluń", lat: 51.2210, lon: 18.5696, country: "pl", region: "Łódzkie"),
        City(slug: "wlodawa", name: "Włodawa", lat: 51.5500, lon: 23.5500, country: "pl", region: "Lubelskie"),
        City(slug: "wloszczowa", name: "Włoszczowa", lat: 50.8526, lon: 19.9659, country: "pl", region: "Świętokrzyskie"),
        City(slug: "wolomin", name: "Wołomin i okolice", lat: 52.3401, lon: 21.2421, country: "pl", region: "Mazowieckie"),
        City(slug: "wysokie-mazowieckie", name: "Wysokie Mazowieckie", lat: 52.9166, lon: 22.5171, country: "pl", region: "Podlaskie"),
        City(slug: "wyszkow", name: "Wyszków i okolice", lat: 52.5928, lon: 21.4584, country: "pl", region: "Mazowieckie"),
        City(slug: "zakopane", name: "Zakopane", lat: 49.2990, lon: 19.9489, country: "pl", region: "Małopolskie"),
        City(slug: "zamosc", name: "Zamość", lat: 50.7231, lon: 23.2520, country: "pl", region: "Lubelskie"),
        City(slug: "zary", name: "Żary", lat: 51.6420, lon: 15.1373, country: "pl", region: "Lubuskie"),
        City(slug: "zawiercie", name: "Zawiercie", lat: 50.4877, lon: 19.4168, country: "pl", region: "Śląskie"),
        City(slug: "zdunska-wola", name: "Zduńska Wola i okolice", lat: 51.5992, lon: 18.9397, country: "pl", region: "Łódzkie"),
        City(slug: "zgierz", name: "Zgierz i okolice", lat: 51.8556, lon: 19.4062, country: "pl", region: "Łódzkie"),
        City(slug: "zgorzelec", name: "Zgorzelec i okolice", lat: 51.1494, lon: 15.0084, country: "pl", region: "Dolnośląskie"),
        City(slug: "zlocieniec", name: "Złocieniec i okolice", lat: 53.5329, lon: 16.0113, country: "pl", region: "Zachodniopomorskie"),
        City(slug: "zlotow", name: "Złotów i okolice", lat: 53.3635, lon: 17.0408, country: "pl", region: "Wielkopolskie"),
        City(slug: "zory", name: "Żory", lat: 50.0452, lon: 18.7006, country: "pl", region: "Śląskie"),
        City(slug: "zyrardow", name: "Żyrardów i okolice", lat: 52.0488, lon: 20.4460, country: "pl", region: "Mazowieckie"),
        City(slug: "zywiec", name: "Żywiec i okolice", lat: 49.6853, lon: 19.1924, country: "pl", region: "Śląskie"),
        // ── end Poland (generated)
        // ── United Kingdom (79 Flicks regions; English labels). Each carries the
        //    NATION it is picked under, matching what `/api/catalog` sends for it
        //    — this list is the fallback that renders before the catalog arrives,
        //    and a fallback that groups differently is a picker that rearranges
        //    itself under the reader. ─────────────────────────────────────────
        City(slug: "london", name: "London", lat: 51.5074, lon: -0.1278, country: "uk", region: "England"),
        City(slug: "manchester", name: "Manchester", lat: 53.4808, lon: -2.2426, country: "uk", region: "England"),
        City(slug: "norwich", name: "Norwich", lat: 52.6309, lon: 1.2974, country: "uk", region: "England"),
        City(slug: "aberdeenshire", name: "Aberdeenshire", lat: 57.308, lon: -2.3393, country: "uk", region: "Scotland"),
        City(slug: "antrim", name: "Antrim", lat: 54.762, lon: -6.0127, country: "uk", region: "Northern Ireland", subregion: "Antrim"),
        City(slug: "armagh", name: "Armagh", lat: 54.4492, lon: -6.398, country: "uk", region: "Northern Ireland"),
        City(slug: "ayrshire-and-arran", name: "Ayrshire and Arran", lat: 55.5093, lon: -4.581, country: "uk", region: "Scotland"),
        City(slug: "bedfordshire", name: "Bedfordshire", lat: 52.0082, lon: -0.4435, country: "uk", region: "England"),
        City(slug: "belfast", name: "Belfast", lat: 54.5857, lon: -5.9428, country: "uk", region: "Northern Ireland", subregion: "Antrim"),
        City(slug: "berkshire", name: "Berkshire", lat: 51.4268, lon: -0.9169, country: "uk", region: "England"),
        City(slug: "birmingham", name: "Birmingham", lat: 52.4581, lon: -1.9041, country: "uk", region: "England", subregion: "West Midlands"),
        City(slug: "bristol", name: "Bristol", lat: 51.4659, lon: -2.5805, country: "uk", region: "England"),
        City(slug: "buckinghamshire", name: "Buckinghamshire", lat: 51.7582, lon: -0.7609, country: "uk", region: "England"),
        City(slug: "cambridgeshire", name: "Cambridgeshire", lat: 52.4301, lon: -0.0137, country: "uk", region: "England"),
        City(slug: "cardiff", name: "Cardiff", lat: 51.4892, lon: -3.1939, country: "uk", region: "Wales", subregion: "Glamorgan"),
        City(slug: "central-scotland", name: "Central Scotland", lat: 56.08, lon: -3.8066, country: "uk", region: "Scotland"),
        City(slug: "cheshire", name: "Cheshire", lat: 53.2917, lon: -2.4966, country: "uk", region: "England"),
        City(slug: "clwyd", name: "Clwyd", lat: 53.3083, lon: -3.6072, country: "uk", region: "Wales"),
        City(slug: "cornwall", name: "Cornwall", lat: 50.317, lon: -4.9211, country: "uk", region: "England"),
        City(slug: "county-durham", name: "County Durham", lat: 54.7289, lon: -1.5139, country: "uk", region: "England"),
        City(slug: "cumbria", name: "Cumbria", lat: 54.4593, lon: -3.1119, country: "uk", region: "England"),
        City(slug: "derbyshire", name: "Derbyshire", lat: 52.9886, lon: -1.5219, country: "uk", region: "England"),
        City(slug: "devon", name: "Devon", lat: 50.6651, lon: -3.687, country: "uk", region: "England"),
        City(slug: "dorset", name: "Dorset", lat: 50.7664, lon: -2.1122, country: "uk", region: "England"),
        City(slug: "down", name: "Down", lat: 54.4293, lon: -5.9704, country: "uk", region: "Northern Ireland"),
        City(slug: "dudley", name: "Dudley", lat: 52.497, lon: -2.0918, country: "uk", region: "England", subregion: "West Midlands"),
        City(slug: "dumfries-and-galloway", name: "Dumfries and Galloway", lat: 54.9881, lon: -3.8232, country: "uk", region: "Scotland"),
        City(slug: "dunbartonshire-argyll-bute", name: "Dunbartonshire and Argyll & Bute", lat: 55.7795, lon: -4.9973, country: "uk", region: "Scotland"),
        City(slug: "dyfed", name: "Dyfed", lat: 51.9892, lon: -4.3329, country: "uk", region: "Wales"),
        City(slug: "east-sussex", name: "East Sussex", lat: 50.8499, lon: 0.2215, country: "uk", region: "England"),
        City(slug: "east-yorkshire", name: "East Yorkshire", lat: 53.8685, lon: -0.3985, country: "uk", region: "England"),
        City(slug: "edinburgh-and-lothians", name: "Edinburgh & Lothians", lat: 55.9404, lon: -3.2039, country: "uk", region: "Scotland"),
        City(slug: "essex", name: "Essex", lat: 51.7621, lon: 0.5901, country: "uk", region: "England"),
        City(slug: "fermanagh", name: "Fermanagh", lat: 54.3499, lon: -7.6316, country: "uk", region: "Northern Ireland"),
        City(slug: "fife", name: "Fife", lat: 56.1287, lon: -3.2424, country: "uk", region: "Scotland"),
        City(slug: "glamorgan", name: "Glamorgan", lat: 51.6388, lon: -3.7535, country: "uk", region: "Wales", subregion: "Glamorgan"),
        City(slug: "glasgow", name: "Glasgow", lat: 55.8682, lon: -4.2316, country: "uk", region: "Scotland"),
        City(slug: "gloucestershire", name: "Gloucestershire", lat: 51.8387, lon: -2.2712, country: "uk", region: "England"),
        City(slug: "guernsey", name: "Guernsey", lat: 49.4446, lon: -2.5695, country: "uk", region: "Crown Dependencies"),
        City(slug: "gwent", name: "Gwent", lat: 51.6882, lon: -3.0066, country: "uk", region: "Wales"),
        City(slug: "gwynedd", name: "Gwynedd", lat: 53.0098, lon: -4.153, country: "uk", region: "Wales"),
        City(slug: "hampshire", name: "Hampshire", lat: 50.9234, lon: -1.165, country: "uk", region: "England"),
        City(slug: "herefordshire", name: "Herefordshire", lat: 52.031, lon: -2.7825, country: "uk", region: "England"),
        City(slug: "hertfordshire", name: "Hertfordshire", lat: 51.7791, lon: -0.3102, country: "uk", region: "England"),
        City(slug: "highlands-and-islands", name: "Highlands and Islands", lat: 58.086, lon: -4.0855, country: "uk", region: "Scotland"),
        City(slug: "isle-of-man", name: "Isle of Man", lat: 54.1578, lon: -4.4775, country: "uk", region: "Crown Dependencies"),
        City(slug: "isle-of-wight", name: "Isle of Wight", lat: 50.7118, lon: -1.2248, country: "uk", region: "England"),
        City(slug: "jersey", name: "Jersey", lat: 49.1839, lon: -2.1144, country: "uk", region: "Crown Dependencies"),
        City(slug: "kent", name: "Kent", lat: 51.2682, lon: 0.8631, country: "uk", region: "England"),
        City(slug: "lanarkshire", name: "Lanarkshire", lat: 55.7953, lon: -4.0904, country: "uk", region: "Scotland"),
        City(slug: "lancashire", name: "Lancashire", lat: 53.7367, lon: -2.6625, country: "uk", region: "England"),
        City(slug: "leicestershire", name: "Leicestershire", lat: 52.6656, lon: -1.1514, country: "uk", region: "England"),
        City(slug: "lincolnshire", name: "Lincolnshire", lat: 53.2194, lon: -0.2916, country: "uk", region: "England"),
        City(slug: "londonderry", name: "Londonderry", lat: 54.9949, lon: -7.0636, country: "uk", region: "Northern Ireland"),
        City(slug: "liverpool", name: "Liverpool", lat: 53.4084, lon: -2.9916, country: "uk", region: "England"),
        City(slug: "north-yorkshire", name: "North Yorkshire", lat: 54.2402, lon: -1.156, country: "uk", region: "England"),
        City(slug: "northamptonshire", name: "Northamptonshire", lat: 52.288, lon: -0.8653, country: "uk", region: "England"),
        City(slug: "northumberland", name: "Northumberland", lat: 55.2158, lon: -1.7422, country: "uk", region: "England"),
        City(slug: "nottinghamshire", name: "Nottinghamshire", lat: 53.0236, lon: -1.15, country: "uk", region: "England"),
        City(slug: "oxfordshire", name: "Oxfordshire", lat: 51.7572, lon: -1.2545, country: "uk", region: "England"),
        City(slug: "powys", name: "Powys", lat: 52.3806, lon: -3.26, country: "uk", region: "Wales"),
        City(slug: "renfrewshire", name: "Renfrewshire", lat: 55.9204, lon: -4.5838, country: "uk", region: "Scotland"),
        City(slug: "roxburgh-ettrick-and-lauderdale", name: "Roxburgh, Ettrick and Lauderdale", lat: 55.5183, lon: -2.7969, country: "uk", region: "Scotland"),
        City(slug: "sandwell", name: "Sandwell", lat: 52.5175, lon: -1.9932, country: "uk", region: "England", subregion: "West Midlands"),
        City(slug: "shropshire", name: "Shropshire", lat: 52.6813, lon: -2.6215, country: "uk", region: "England"),
        City(slug: "somerset", name: "Somerset", lat: 51.2159, lon: -2.824, country: "uk", region: "England"),
        City(slug: "south-yorkshire", name: "South Yorkshire", lat: 53.5141, lon: -1.3109, country: "uk", region: "England"),
        City(slug: "staffordshire", name: "Staffordshire", lat: 52.7942, lon: -1.9887, country: "uk", region: "England"),
        City(slug: "suffolk", name: "Suffolk", lat: 52.1492, lon: 1.0262, country: "uk", region: "England"),
        City(slug: "surrey", name: "Surrey", lat: 51.2269, lon: -0.5354, country: "uk", region: "England"),
        City(slug: "tayside", name: "Tayside", lat: 56.5061, lon: -3.0128, country: "uk", region: "Scotland"),
        City(slug: "tyne-and-wear", name: "Tyne and Wear", lat: 54.9749, lon: -1.5397, country: "uk", region: "England"),
        City(slug: "tyrone", name: "Tyrone", lat: 54.5255, lon: -6.8664, country: "uk", region: "Northern Ireland"),
        City(slug: "warwickshire", name: "Warwickshire", lat: 52.3602, lon: -1.5034, country: "uk", region: "England"),
        City(slug: "west-sussex", name: "West Sussex", lat: 50.9492, lon: -0.3262, country: "uk", region: "England"),
        City(slug: "west-yorkshire", name: "West Yorkshire", lat: 53.7878, lon: -1.665, country: "uk", region: "England"),
        City(slug: "wiltshire", name: "Wiltshire", lat: 51.2955, lon: -1.8505, country: "uk", region: "England"),
        City(slug: "worcestershire", name: "Worcestershire", lat: 52.1923, lon: -2.2079, country: "uk", region: "England"),
        City(slug: "yorkshire", name: "Yorkshire", lat: 53.4082, lon: -1.4756, country: "uk", region: "England"),
    ]

    /// The collation locale for a country's city names: Polish for `pl` (so the
    /// diacritic letters sort in their alphabet positions), English elsewhere.
    static func collationLocale(for countryCode: String) -> Locale {
        Locale(identifier: countryCode == "pl" ? "pl_PL" : "en_GB")
    }

    /// Ultimate fallback city — the first bundled city overall (Poznań). Only the
    /// compile-time default for the networking stores before the gate sets a real
    /// city; live flows pick a country-scoped default from the catalog instead.
    static let `default` = all[0]

    /// A "you're nearer another city — switch?" prompt the app should
    /// surface: the city to offer (`target`) and a stable de-dupe `key`
    /// for the `chosen → nearest` pair so the prompt fires at most once
    /// per pair.
    struct CitySwitchSuggestion: Equatable {
        let target: City
        let key: String
    }

    /// The stable de-dupe key for a `chosen → nearest` pair. Built in one place
    /// so the value `switchSuggestion` compares against is the same one the
    /// first-launch gate pre-records via `initialChoiceSuppressKey`.
    static func switchPromptKey(chosenSlug: String, nearestSlug: String) -> String {
        chosenSlug + "→" + nearestSlug
    }

    /// The prompt key to pre-record when the user *deliberately* picks
    /// `chosenSlug` at the first-launch gate while location placed them nearest
    /// `nearestSlug`. Seeding it means `switchSuggestion` won't immediately turn
    /// around and offer to switch back to the city they just chose against —
    /// the choice was intentional. Returns `nil` when there's nothing to
    /// suppress: no location fix (`nearestSlug == nil`), or the chosen city *is*
    /// the nearest. Only this one pair is suppressed, so travelling to a
    /// different city later still re-arms the prompt.
    static func initialChoiceSuppressKey(chosenSlug: String, nearestSlug: String?) -> String? {
        guard let nearestSlug, nearestSlug != chosenSlug else { return nil }
        return switchPromptKey(chosenSlug: chosenSlug, nearestSlug: nearestSlug)
    }

    /// What `CityChoiceView.choose(_:)` should do about the "nearer city"
    /// prompt when adopting `chosenSlug`, given `nearestSlug` — the
    /// location-detected nearest on the true first-launch flow, or `nil` when
    /// this pick has none (Filtry's "Choose another city", or a country
    /// switch, neither of which resolved a location fix before landing here).
    enum SwitchPromptSuppression: Equatable {
        /// A real, DIFFERENT detected nearest: seed the precise
        /// `chosen→nearest` pair, so `switchSuggestion` recognises and stays
        /// quiet for exactly it.
        case seedKey(String)
        /// No detected nearest to build a pair from — there's nothing precise
        /// to key on, so skip the ONE check `ContentView.onAppear` fires right
        /// after this pick instead (`CitySwitchSuppressor`, the same
        /// mechanism a web sign-in's Custom Tab resume uses).
        case suppressNextCheck
        /// Nothing to do: the chosen city already equals the detected
        /// nearest, so `switchSuggestion` will stay quiet on its own.
        case none
    }

    static func switchPromptSuppression(chosenSlug: String, nearestSlug: String?) -> SwitchPromptSuppression {
        if let key = initialChoiceSuppressKey(chosenSlug: chosenSlug, nearestSlug: nearestSlug) {
            return .seedKey(key)
        }
        return nearestSlug == nil ? .suppressNextCheck : .none
    }

    /// The city-prefixed API URL for `endpoint` (`"repertoire"` /
    /// `"details"`) against `base` — e.g. `…/poznan/api/repertoire`. The
    /// repertoire/details stores build their fetch URL through this so the
    /// `/{slug}/api/…` shape lives in one tested place. Auth endpoints stay
    /// unprefixed and never call this.
    static func apiURL(base: URL, slug: String, endpoint: String) -> URL {
        base
            .appendingPathComponent(slug)
            .appendingPathComponent("api")
            .appendingPathComponent(endpoint)
    }

    /// Fold a Polish string to its diacritic-free, lower-case form for search
    /// matching, so a query typed without Polish letters still finds the city
    /// ("lodz" → "Łódź", "krakow" → "Kraków"). `.diacriticInsensitive` folding
    /// doesn't map ł/ą/ę/ń and isn't identical on Linux swift-corelibs, so map
    /// the Polish letters explicitly for cross-platform-stable results.
    static func searchFold(_ s: String) -> String {
        let map: [Character: Character] = [
            "ą": "a", "ć": "c", "ę": "e", "ł": "l", "ń": "n",
            "ó": "o", "ś": "s", "ź": "z", "ż": "z"
        ]
        return String(s.lowercased().map { map[$0] ?? $0 })
    }

    /// Whether this city matches `query` under case- and diacritic-insensitive
    /// substring matching. A blank query matches every city (an empty search
    /// box shows the whole list).
    func matches(_ query: String) -> Bool {
        let q = City.searchFold(query.trimmingCharacters(in: .whitespaces))
        return q.isEmpty || City.searchFold(name).contains(q)
    }

    /// Great-circle distance in kilometres between two coordinates.
    static func haversineKm(latitude1: Double, longitude1: Double, latitude2: Double, longitude2: Double) -> Double {
        let earthRadiusKm = 6_371.0
        let deltaLatitude = (latitude2 - latitude1) * .pi / 180
        let deltaLongitude = (longitude2 - longitude1) * .pi / 180
        let latitude1Radians = latitude1 * .pi / 180
        let latitude2Radians = latitude2 * .pi / 180
        let squareHalfChord = sin(deltaLatitude / 2) * sin(deltaLatitude / 2)
            + sin(deltaLongitude / 2) * sin(deltaLongitude / 2) * cos(latitude1Radians) * cos(latitude2Radians)
        let angularDistance = 2 * atan2(sqrt(squareHalfChord), sqrt(1 - squareHalfChord))
        return earthRadiusKm * angularDistance
    }
}

extension City {
    /// The RAW localization key(s) for the group level(s) a search box's
    /// prompt should name from a country that groups its cities — the UK's
    /// nation/county, the US's/Germany's single state level. Not
    /// `LocalizedStringKey` itself: this file is pure Foundation (see the
    /// struct's own doc comment) so `swift test` still runs it on Linux CI;
    /// `CityGate.searchPrompt` is what turns a key into `Text`. Mirrors
    /// `PICKER_GROUP_LABELS` in landing.scala.html.
    static let groupSearchLevelKeys: [String: (region: String, subregion: String?)] = [
        "uk": ("citygate.level.uk.region", "citygate.level.uk.subregion"),
        "us": ("citygate.level.us.region", nil),
        "de": ("citygate.level.de.region", nil),
    ]

    /// The localization key(s) a search from THIS level can still reach,
    /// deepest first — mirrors `pickerSearchLevels()` in landing.scala.html
    /// exactly, so web and the app phrase the search box's prompt
    /// identically: two at the root of a country that nests two deep (the
    /// UK), one once a region is picked or for a country with only one level
    /// (US/Germany), none once fully drilled into a subregion or for a flat
    /// country (Poland, Spain).
    static func searchLevelKeys(country: String, region: String?, subregion: String?) -> [String] {
        guard let levels = groupSearchLevelKeys[country] else { return [] }
        if region == nil {
            if let sub = levels.subregion { return [levels.region, sub] }
            return [levels.region]
        }
        if subregion == nil, let sub = levels.subregion { return [sub] }
        return []
    }

    /// One row of a grouped picker level: a group heading (drills further) or
    /// a city that carries no group at this level, either because its top
    /// group collapsed onto it alone (`CityGroup.soleCity` — Berlin, Hamburg,
    /// Delaware, Vermont) or because the country/region simply isn't split
    /// any further here.
    enum PickerRow: Hashable {
        case heading(String)
        case city(City)
    }

    /// One row of a FLATTENED, whole-country search result — see
    /// `Array<City>.searchRows(matching:inCountry:)`. Unlike `PickerRow`, a
    /// subregion here carries its parent `region`: picking it from a flat
    /// list has to land two drill-steps deep at once, not just one, so the
    /// caller can't recover the region from its own current state the way
    /// `PickerRow`'s single-level callers can.
    enum SearchRow: Hashable {
        case region(String)
        case subregion(String, region: String)
        case city(City)

        var label: String {
            switch self {
            case .region(let name): return name
            case .subregion(let name, _): return name
            case .city(let city): return city.name
            }
        }
    }

    /// One pass over `cities` — ALREADY in the catalog's own canonical picker
    /// order (`Catalog.scala` emits each country's cities in its picker
    /// tree's own traversal order; never re-sorted here) — interleaving each
    /// group's heading, emitted at its FIRST occurrence, with every city that
    /// carries no group at this level. Listing every heading before every
    /// direct city (the old shape) stranded a heading like "West Midlands"
    /// ahead of every direct city in its region, instead of beside "West
    /// Sussex" where it alphabetically belongs.
    fileprivate static func mergedRows(_ cities: [City], groupField: (City) -> String?, query: String) -> [PickerRow] {
        let q = City.searchFold(query.trimmingCharacters(in: .whitespaces))
        var seen = Set<String>()
        var rows: [PickerRow] = []
        for city in cities {
            if let group = groupField(city) {
                guard seen.insert(group).inserted else { continue }
                if q.isEmpty || City.searchFold(group).contains(q) { rows.append(.heading(group)) }
            } else if q.isEmpty || City.searchFold(city.name).contains(q) {
                rows.append(.city(city))
            }
        }
        return rows
    }
}

/// Per-country queries over a catalog's city list. `self` is the live catalog's
/// cities — the server-fetched list, the bundled seed, or (as a fallback) the
/// compile-time `City.all`. Kept pure (no I/O) so they're unit-tested in
/// `KinowoCore` by passing a fixed list; the app's `CatalogStore` calls them
/// with its current `cities`.
extension Array where Element == City {

    /// The subset belonging to `countryCode` (`"pl"`, `"uk"`), in this list's order.
    func inCountry(_ countryCode: String) -> [City] { filter { $0.country == countryCode } }

    /// The country code of the city with `slug`, or `nil` when no such city.
    /// Lets a deep link that lands on another country's city (a
    /// `showtimes-uk` / `showtimes-de` link) switch the app to the right
    /// deployment before the repertoire loads.
    func country(ofSlug slug: String) -> String? { first { $0.slug == slug }?.country }

    /// The zone to reason about `slug`'s showtimes in — that city's own where the
    /// catalog gave it one, else `fallback` (its country's). Also the answer for a
    /// slug this catalog does not know, which is what a stale saved selection or a
    /// deep link into another deployment looks like.
    func zone(ofSlug slug: String?, fallback: TimeZone) -> TimeZone {
        guard let slug else { return fallback }
        return first { $0.slug == slug }?.zone(fallback: fallback) ?? fallback
    }

    /// [inCountry] ordered alphabetically under that country's collation (Polish
    /// for `pl`, so `Ł` sorts after `L`; English elsewhere) — what the pickers show.
    func sortedForPicker(inCountry countryCode: String) -> [City] {
        let locale = City.collationLocale(for: countryCode)
        return inCountry(countryCode).sorted {
            $0.name.compare($1.name, options: .caseInsensitive, range: nil, locale: locale) == .orderedAscending
        }
    }

    /// [sortedForPicker] narrowed to the cities matching `query` (case- and
    /// diacritic-insensitive substring). A blank query yields the whole country list.
    func matching(_ query: String, inCountry countryCode: String) -> [City] {
        sortedForPicker(inCountry: countryCode).filter { $0.matches(query) }
    }

    /// The regions this country's cities are grouped under — US states, German
    /// Bundesländer, UK nations — in the catalog's own order, which is the order
    /// the web picker lists them in, so the two read alike. Empty for a country
    /// that does not group its cities (Poland, Spain), and that emptiness is what
    /// the picker reads as "show one flat list".
    ///
    /// The TOP level, even where a region nests a `subregion` below it (see
    /// `secondLevelRows(matching:inCountry:region:)`): the UK's nation names every one of its
    /// cities' `region`, whether or not the county underneath went on to earn a
    /// third step of its own.
    func regions(inCountry countryCode: String) -> [String] {
        var seen = Set<String>()
        return inCountry(countryCode).compactMap(\.region).filter { seen.insert($0).inserted }
    }

    /// `matching(_:inCountry:)` confined to one `region` — used by
    /// `matching(_:inCountry:region:subregion:)` below. A `nil` region leaves
    /// the country-wide list alone, so the same call serves both a grouped
    /// country's third screen and an ungrouped country's only one.
    func matching(_ query: String, inCountry countryCode: String, region: String?) -> [City] {
        let cities = matching(query, inCountry: countryCode)
        guard let region else { return cities }
        return cities.filter { $0.region == region }
    }

    /// The FIRST picker step for a grouped country: each region's heading,
    /// interleaved with any city whose top group collapsed onto it alone
    /// (Berlin, Hamburg; Delaware, Vermont) — narrowed to `query`. Empty for a
    /// country that does not group its cities (Poland, Spain).
    func topLevelRows(matching query: String, inCountry countryCode: String) -> [City.PickerRow] {
        City.mergedRows(inCountry(countryCode), groupField: { $0.region }, query: query)
    }

    /// The SECOND picker step, within one `region`: each subregion's heading
    /// (reached only for the UK's West Midlands / Glamorgan / Antrim today)
    /// interleaved with that region's own directly-listed cities — narrowed
    /// to `query`.
    func secondLevelRows(matching query: String, inCountry countryCode: String, region: String) -> [City.PickerRow] {
        City.mergedRows(inCountry(countryCode).filter { $0.region == region }, groupField: { $0.subregion }, query: query)
    }

    /// Every region, subregion and city in `countryCode` matching `query`,
    /// merged into ONE alphabetical list — a query for "kent" must surface the
    /// Kent COUNTY heading even from the UK's top level, not only once
    /// England is already open. Empty for a blank query: the per-level
    /// `topLevelRows`/`secondLevelRows` above handle that case, and a country
    /// with no grouping (Poland, Spain) has nothing to flatten in the first
    /// place — its own `matching(_:inCountry:)` already reaches every city.
    func searchRows(matching query: String, inCountry countryCode: String) -> [City.SearchRow] {
        let q = City.searchFold(query.trimmingCharacters(in: .whitespaces))
        guard !q.isEmpty else { return [] }
        var seenRegion = Set<String>()
        var seenSubregion = Set<String>()
        var rows: [City.SearchRow] = []
        for city in inCountry(countryCode) {
            if let region = city.region, seenRegion.insert(region).inserted, City.searchFold(region).contains(q) {
                rows.append(.region(region))
            }
            if let region = city.region, let subregion = city.subregion, seenSubregion.insert("\(region)\u{0}\(subregion)").inserted,
               City.searchFold(subregion).contains(q) {
                rows.append(.subregion(subregion, region: region))
            }
            if City.searchFold(city.name).contains(q) {
                rows.append(.city(city))
            }
        }
        let locale = City.collationLocale(for: countryCode)
        return rows.sorted { $0.label.compare($1.label, options: .caseInsensitive, range: nil, locale: locale) == .orderedAscending }
    }

    /// `matching(_:inCountry:region:)` narrowed to one `subregion` — the THIRD
    /// step, reached only where `secondLevelRows(matching:inCountry:region:)`
    /// holds a heading for it.
    func matching(_ query: String, inCountry countryCode: String, region: String, subregion: String) -> [City] {
        matching(query, inCountry: countryCode, region: region).filter { $0.subregion == subregion }
    }

    /// The default city for `countryCode` — its first entry in this list, or `nil`.
    func defaultCity(inCountry countryCode: String) -> City? { inCountry(countryCode).first }

    /// The city IN `countryCode` nearest the coordinate, or `nil` beyond 100 km.
    /// Scoped so a Polish fix never resolves to a UK region, or vice versa.
    func nearestWithin100km(lat: Double, lon: Double, inCountry countryCode: String) -> City? {
        inCountry(countryCode).nearestWithin100km(lat: lat, lon: lon)
    }

    /// The city nearest the coordinate across EVERY country this list carries,
    /// or `nil` beyond 100 km. Unlike the country-scoped overload above, this
    /// is deliberately unscoped — the manual picker's "use my location" button
    /// uses it to find the right city even when the country tab currently open
    /// isn't the one the device is actually in (a UK visitor who hasn't
    /// switched off the default Poland tab yet).
    func nearestWithin100km(lat: Double, lon: Double) -> City? {
        let ranked = map { (city: $0, km: City.haversineKm(latitude1: lat, longitude1: lon, latitude2: $0.lat, longitude2: $0.lon)) }
            .min { $0.km < $1.km }
        guard let nearest = ranked, nearest.km <= 100 else { return nil }
        return nearest.city
    }

    /// The "you're nearer another city — switch?" suggestion for a device at the
    /// coordinate, scoped to `countryCode`; `nil` when already nearest, out of
    /// range, or this pair was the `lastPromptKey`.
    func switchSuggestion(chosenSlug: String, lat: Double, lon: Double, lastPromptKey: String?, inCountry countryCode: String) -> City.CitySwitchSuggestion? {
        guard let nearest = nearestWithin100km(lat: lat, lon: lon, inCountry: countryCode),
              nearest.slug != chosenSlug else { return nil }
        let key = City.switchPromptKey(chosenSlug: chosenSlug, nearestSlug: nearest.slug)
        guard key != lastPromptKey else { return nil }
        return City.CitySwitchSuggestion(target: nearest, key: key)
    }
}
