package services.cinemas.us

/**
 * Regal's US estate: each venue's `data/us/venues.json` slug — the same slug
 * [[models.UsRoster.flicksSlugByCinema]] carries, and therefore the stable key a
 * `Cinema` is found by — paired with its Regal `TheatreCode`.
 *
 * GENERATED from `docs/venue-maps/REGAL-VENUE-MAP.tsv`, which was built by
 * matching Regal's own roster (`GET /api/theatres`) to our venue rows by
 * coordinates + name tokens and then cross-checking every pairing against the
 * theatre slug in `regmovies.com/sitemap.xml` (`/theatres/<slug>-<code>`).
 * Keyed by SLUG rather than display name because a display name is qualified on
 * collision (`UsRoster` appends the state), while the slug never moves.
 *
 * 401 of our 408 Regal venues appear here. The other seven are locations Regal's
 * own roster no longer lists (closed sites); they keep flicks.us as their only
 * source, which is what the catalogue does with any venue absent from this map.
 */
object RegalVenues {

  /** Venue slug -> Regal `TheatreCode`. */
  val theatreCodeBySlug: Map[String, String] = Map(
    "regal-aiken-mall" -> "0252",
    "regal-alamo-quarry-san-antonio" -> "0939",
    "regal-albany" -> "0833",
    "regal-alderwood-lynnwood" -> "0909",
    "regal-aliante" -> "1933",
    "regal-american-mall-lima" -> "0680",
    "regal-arbor-place-douglasville" -> "0392",
    "regal-arnot-mall-horseheads" -> "1730",
    "regal-arroyo-grande" -> "1812",
    "regal-atlantic-station" -> "1346",
    "regal-atlas-park-glendale" -> "0688",
    "regal-auburn-california" -> "1823",
    "regal-auburn-washington" -> "0877",
    "regal-augusta" -> "1704",
    "regal-augusta-exchange" -> "0724",
    "regal-avalon-alpharetta" -> "1694",
    "regal-avenues-jacksonville" -> "0241",
    "regal-aviation-mall-queensbury" -> "1731",
    "regal-azalea-square-summerville" -> "1850",
    "regal-ballston-quarter-arlington" -> "0296",
    "regal-barkley-village-bellingham" -> "1671",
    "regal-battery-park" -> "1335",
    "regal-bella-bottega-redmond" -> "0904",
    "regal-bellingham" -> "1713",
    "regal-belltower-fort-myers" -> "0432",
    "regal-benders-landing" -> "1469",
    "regal-big-newport-beach" -> "1024",
    "regal-biltmore-grande-stadium-asheville" -> "1892",
    "regal-binghamton" -> "1732",
    "regal-birkdale-huntersville" -> "1842",
    "regal-bistro-at-the-falls" -> "1149",
    "regal-bolingbrook" -> "1787",
    "regal-boone" -> "0217",
    "regal-boulder-las-vegas" -> "0837",
    "regal-bowling-green" -> "1525",
    "regal-brandywine-town-center" -> "0509",
    "regal-brea-east" -> "1028",
    "regal-bricktown-charleston" -> "1419",
    "regal-bridgeport-village-tigard" -> "0652",
    "regal-brier-creek-raleigh" -> "1843",
    "regal-broward-plantation" -> "1762",
    "regal-burlington" -> "0198",
    "regal-butler-town-center-gainesville" -> "0219",
    "regal-canyon-view-grand-junction" -> "0698",
    "regal-carlsbad" -> "1778",
    "regal-carrollton" -> "1420",
    "regal-cascade-vancouver" -> "0845",
    "regal-celebration-pointe" -> "1416",
    "regal-champlain-cinemas-plattsburgh" -> "1734",
    "regal-cherokee-woodstock" -> "1423",
    "regal-cherrydale-grand-greenville" -> "1885",
    "regal-cielo-vista-san-antonio" -> "0765",
    "regal-cinebarre-mountlake" -> "1958",
    "regal-cinebarre-palace-station" -> "1463",
    "regal-cinebarre-west-town-mall-knoxville" -> "1462",
    "regal-cinema-99-vancouver" -> "0846",
    "regal-cinema-tullahoma" -> "0120",
    "regal-citrus-cinemas-inverness" -> "0206",
    "regal-city-center-vancouver" -> "0847",
    "regal-city-north" -> "1789",
    "regal-clarksville" -> "1534",
    "regal-clifton-park" -> "1769",
    "regal-cobblestone-square-elyria" -> "0755",
    "regal-coldwater-crossing-fort-wayne" -> "0169",
    "regal-colonie-center-albany" -> "1923",
    "regal-columbia-stadium" -> "1621",
    "regal-columbiana-grande" -> "1887",
    "regal-columbus-virginia-beach" -> "0718",
    "regal-commerce-center-north-brunswick" -> "0705",
    "regal-commonwealth" -> "1864",
    "regal-concourse" -> "1486",
    "regal-cortlandt-mohegan-lake" -> "1318",
    "regal-crocker-park" -> "0155",
    "regal-crossgates" -> "1737",
    "regal-crossroads-bellevue" -> "0905",
    "regal-crossroads-cary" -> "1874",
    "regal-crossroads-taylorsville" -> "1426",
    "regal-crystal-lake-showplace" -> "0621",
    "regal-culpeper-movies" -> "1913",
    "regal-cumberland-mall-vineland" -> "0244",
    "regal-dania-pointe" -> "1474",
    "regal-davis-holiday" -> "1814",
    "regal-dawsonville" -> "1422",
    "regal-deer-park" -> "0692",
    "regal-deerfield-towne-center-mason" -> "1901",
    "regal-delta-shores-sacramento" -> "1413",
    "regal-denver-pavilions" -> "1315",
    "regal-destiny-mall-syracuse" -> "1733",
    "regal-dickson-city" -> "1515",
    "regal-dimond-center" -> "0922",
    "regal-dole-cannery" -> "1828",
    "regal-downingtown-cinema" -> "0385",
    "regal-downtown-summerlin-las-vegas" -> "0575",
    "regal-downtown-west-knoxville" -> "0103",
    "regal-dulles-town-center" -> "1672",
    "regal-eagle-ridge-mall" -> "0466",
    "regal-east-greenbush-rensselaer" -> "1738",
    "regal-east-hampton" -> "1138",
    "regal-eastview-victor" -> "0501",
    "regal-edgmont-square" -> "0232",
    "regal-edwards-alhambra-renaissance" -> "1053",
    "regal-edwards-aliso-viejo" -> "1032",
    "regal-edwards-bakersfield" -> "1031",
    "regal-edwards-boise" -> "1027",
    "regal-edwards-camarillo" -> "1009",
    "regal-edwards-canyon-country" -> "1047",
    "regal-edwards-cerritos" -> "1018",
    "regal-edwards-corona-crossings" -> "0665",
    "regal-edwards-eastvale-gateway" -> "1916",
    "regal-edwards-fairfield" -> "1046",
    "regal-edwards-grand-teton" -> "1040",
    "regal-edwards-houston-marqe" -> "1052",
    "regal-edwards-kaleidoscope" -> "1035",
    "regal-edwards-long-beach" -> "1042",
    "regal-edwards-nampa-spectrum" -> "1039",
    "regal-edwards-ontario-palace" -> "1026",
    "regal-edwards-rancho-san-diego" -> "1049",
    "regal-edwards-west-covina" -> "1030",
    "regal-el-dorado-hills" -> "1807",
    "regal-elmwood-center-buffalo" -> "0341",
    "regal-escondido" -> "1805",
    "regal-essex-crossing-new-york" -> "1412",
    "regal-everett" -> "0663",
    "regal-evergreen-hillsboro" -> "0850",
    "regal-fairfax-towne-center" -> "1275",
    "regal-fairfield-commons-beavercreek" -> "0389",
    "regal-farmingdale" -> "1319",
    "regal-flintridge-la-canada" -> "1270",
    "regal-forum-rolla" -> "1653",
    "regal-fossil-creek-fort-worth" -> "1317",
    "regal-fox-ashburn" -> "1869",
    "regal-fox-laramie" -> "1655",
    "regal-fox-run-newington" -> "1728",
    "regal-fox-tower-portland" -> "0633",
    "regal-franklin-square-gastonia" -> "1845",
    "regal-fredericksburg" -> "0712",
    "regal-fresno-riverpark" -> "1033",
    "regal-galaxy-indianapolis" -> "1299",
    "regal-gallatin-valley" -> "1625",
    "regal-galleria-mall-poughkeepsie" -> "1740",
    "regal-gallery-place-washington" -> "1551",
    "regal-garden-grove" -> "0364",
    "regal-gateway-austin" -> "0949",
    "regal-georgian" -> "1891",
    "regal-gilbert" -> "1606",
    "regal-goldstream" -> "0601",
    "regal-grand-central-mall" -> "0115",
    "regal-grande-esplanade" -> "1480",
    "regal-green-hills-nashville" -> "0513",
    "regal-greensboro-grande" -> "1875",
    "regal-greenway-grand-palace-houston" -> "1051",
    "regal-greenwood" -> "1794",
    "regal-greenwood-mall" -> "1581",
    "regal-griffin" -> "1424",
    "regal-guam" -> "1645",
    "regal-gulf-coast-fort-myer" -> "0684",
    "regal-hacienda-crossings-dublin" -> "0347",
    "regal-hadley-south-plainfield" -> "0370",
    "regal-hamburg-pavilion-lexington" -> "0728",
    "regal-hamilton-commons" -> "1729",
    "regal-hamilton-mill-dacula" -> "1535",
    "regal-hamilton-place-chattanooga" -> "0117",
    "regal-harbour-view-grande-suffolk" -> "1866",
    "regal-harrisburg" -> "1748",
    "regal-harrisonburg" -> "0735",
    "regal-hazleton" -> "1749",
    "regal-heartland-early" -> "1643",
    "regal-hilltop-oregon-city" -> "0853",
    "regal-holiday-stockton" -> "1816",
    "regal-hollywood-gainesville" -> "1421",
    "regal-hollywood-greenville" -> "0488",
    "regal-hollywood-merced" -> "1607",
    "regal-hollywood-naples" -> "0465",
    "regal-hollywood-nashville" -> "0489",
    "regal-hollywood-ocala" -> "0483",
    "regal-hollywood-port-richey" -> "0418",
    "regal-hollywood-sarasota" -> "0467",
    "regal-hollywood-st-joseph" -> "1624",
    "regal-hudson" -> "0164",
    "regal-huebner-oaks-san-antonio" -> "0581",
    "regal-hunt-valley" -> "1711",
    "regal-hyattsville-royale" -> "1863",
    "regal-independence-mall-kingston" -> "1717",
    "regal-independence-plaza-hamilton" -> "1417",
    "regal-interquest-colorado-springs" -> "1609",
    "regal-irvine-spectrum" -> "1010",
    "regal-issaquah-highland" -> "1942",
    "regal-ithaca-mall-stadium" -> "0677",
    "regal-jack-london-oakland" -> "1808",
    "regal-janss-marketplace" -> "1418",
    "regal-kapolei-commons" -> "1951",
    "regal-keauhou" -> "1830",
    "regal-kendall-village-miami" -> "0996",
    "regal-key-west" -> "0412",
    "regal-killeen-stadium" -> "1636",
    "regal-king-of-prussia" -> "1329",
    "regal-kingstowne" -> "1865",
    "regal-la-habra" -> "0704",
    "regal-la-live" -> "1484",
    "regal-la-verne" -> "1012",
    "regal-laguna-village-sacramento" -> "1286",
    "regal-lakewood" -> "0887",
    "regal-lansing-mall" -> "0596",
    "regal-largo-mall" -> "0446",
    "regal-laurel-town-center" -> "0563",
    "regal-lee-hills-leesville" -> "1200",
    "regal-live-oak-san-antonio" -> "0795",
    "regal-lloyd-center-portland" -> "0807",
    "regal-lone-star-tomball" -> "1441",
    "regal-longston-place-puyallup" -> "0355",
    "regal-louisiana-boardwalk-bossier-city" -> "0664",
    "regal-lynbrook" -> "1348",
    "regal-magnolia-place-coral-springs" -> "0339",
    "regal-majestic-silver-spring" -> "1862",
    "regal-mall-of-georgia" -> "0701",
    "regal-manahawkin-cinemas" -> "1754",
    "regal-manchester-fresno" -> "1820",
    "regal-manchester-rock-hill" -> "1886",
    "regal-manor-cinema-lancaster" -> "0754",
    "regal-market-place-irvine" -> "1048",
    "regal-marketplace-at-el-paseo" -> "1433",
    "regal-martin-village-lacey" -> "0673",
    "regal-marysville" -> "0298",
    "regal-mashpee-commons" -> "1718",
    "regal-massillon-great-escape" -> "1512",
    "regal-maui-mall-kahului" -> "1614",
    "regal-mayfaire-wilmington" -> "1873",
    "regal-mccain-mall-little-rock" -> "0541",
    "regal-mcdonough" -> "1519",
    "regal-medina-stadium" -> "0707",
    "regal-medlock-crossing-duluth" -> "0354",
    "regal-meridian-seattle" -> "1931",
    "regal-metro-pointe-stadium-costa-mesa" -> "1007",
    "regal-metro-san-jacinto" -> "1804",
    "regal-metropolitan-austin" -> "0950",
    "regal-mgm-springfield" -> "1467",
    "regal-midway-stadium-forest-hills" -> "1143",
    "regal-mira-mesa-stadium-san-diego" -> "1043",
    "regal-mission-marketplace-oceanside" -> "1470",
    "regal-modesto" -> "1818",
    "regal-moorestown" -> "1917",
    "regal-mountain-village-ontario" -> "1037",
    "regal-movies-on-tv-hillsboro" -> "0855",
    "regal-nanuet" -> "0558",
    "regal-natomas-marketplace-sacramento" -> "0774",
    "regal-new-river-valley-christiansburg" -> "0671",
    "regal-new-roc-city" -> "0297",
    "regal-new-town-williamsburg" -> "1868",
    "regal-nitro" -> "1518",
    "regal-noblesville" -> "1523",
    "regal-north-hills-raleigh" -> "1846",
    "regal-north-hollywood" -> "1438",
    "regal-northampton-easton" -> "0371",
    "regal-northlake-village-lexington" -> "1889",
    "regal-northstar-joplin" -> "1622",
    "regal-northtown-mall-spokane" -> "0883",
    "regal-northwoods-san-antonio" -> "0940",
    "regal-nuuuli-place-twin" -> "1647",
    "regal-oakmont-bradenton" -> "0444",
    "regal-oceanside" -> "0708",
    "regal-old-mill-bend" -> "0758",
    "regal-opry-mills-nashville" -> "0615",
    "regal-oviedo-mall" -> "0380",
    "regal-oxford-valley-langhorne" -> "1269",
    "regal-palladium-high-point" -> "1870",
    "regal-palmetto-grand-mt-pleasant" -> "1884",
    "regal-park-place-pinellas-park" -> "1914",
    "regal-parkway-plaza-el-cajon" -> "0388",
    "regal-paseo-pasadena" -> "1485",
    "regal-pavilion-port-orange" -> "1613",
    "regal-pearl-highlands" -> "1827",
    "regal-peoples-plaza" -> "0133",
    "regal-perimeter-pointe-atlanta" -> "1309",
    "regal-pinnacle-knoxville" -> "0682",
    "regal-pioneer-place-portland" -> "0656",
    "regal-plymouth-meeting" -> "0234",
    "regal-pointe-orlando" -> "1938",
    "regal-poulsbo" -> "0880",
    "regal-prince-kuhio" -> "1652",
    "regal-promenade-rolling-hills-estates" -> "0748",
    "regal-providence-mt-juliet" -> "1890",
    "regal-quaker-crossing" -> "0700",
    "regal-ranch-green-valley-henderson" -> "0637",
    "regal-rancho-del-rey-chula-vista" -> "0361",
    "regal-rancho-mirage" -> "1801",
    "regal-red-rock-stadium-las-vegas" -> "0659",
    "regal-regency-panama-city" -> "1859",
    "regal-river-point-sheridan" -> "1943",
    "regal-river-ridge-lynchburg" -> "1995",
    "regal-riverside-plaza" -> "1806",
    "regal-riverstone" -> "0654",
    "regal-riviera-knoxville" -> "0690",
    "regal-rockville-center" -> "0336",
    "regal-ronkonkoma" -> "0632",
    "regal-royal-park-gainesville" -> "1860",
    "regal-royal-royal-palm-beach" -> "0351",
    "regal-salisbury" -> "0674",
    "regal-salmon-run-watertown" -> "1946",
    "regal-san-bernardino" -> "1799",
    "regal-san-marcos" -> "1034",
    "regal-sandhill-columbia" -> "1855",
    "regal-santa-fe" -> "1465",
    "regal-santa-maria-town-center" -> "1681",
    "regal-santa-rosa-mary-esther" -> "1195",
    "regal-santiam-salem" -> "0863",
    "regal-sawgrass-sunrise" -> "0442",
    "regal-secaucus-showplace" -> "1665",
    "regal-sherman-oaks" -> "1483",
    "regal-shiloh-crossing-avon" -> "0190",
    "regal-short-pump" -> "0730",
    "regal-simi-valley-civic-center" -> "0391",
    "regal-simpsonville" -> "1517",
    "regal-solomon-pond" -> "1721",
    "regal-south-gate" -> "1044",
    "regal-south-hill-puyallup" -> "0885",
    "regal-south-youngstown" -> "0175",
    "regal-southglenn-centennial" -> "1610",
    "regal-southland-mall-miami" -> "0683",
    "regal-southpark-mall-colonial-heights" -> "1902",
    "regal-southwind-lawrence" -> "1618",
    "regal-spartan-spartanburg" -> "1888",
    "regal-spokane-valley" -> "0895",
    "regal-spotlight-norman" -> "1628",
    "regal-springfield-town-center" -> "0595",
    "regal-star-beaumont" -> "1639",
    "regal-stark-st-gresham" -> "0856",
    "regal-starlight-charlotte" -> "1848",
    "regal-starlight-stdm-anderson" -> "1853",
    "regal-stockton-city-centre" -> "1817",
    "regal-stonecrest-at-piper-glen-charlotte" -> "0384",
    "regal-stonefield" -> "1969",
    "regal-stonestown-galleria" -> "1464",
    "regal-strawbridge-virginia-beach" -> "0235",
    "regal-streets-of-indian-lake" -> "1926",
    "regal-sunset-station-henderson" -> "0838",
    "regal-swamp-fox" -> "1854",
    "regal-tall-firs-bonney-lake" -> "0330",
    "regal-tangram" -> "1472",
    "regal-temecula" -> "1045",
    "regal-the-landing-renton" -> "1935",
    "regal-the-loop-kissimmee" -> "0687",
    "regal-thornton-place-seattle" -> "1937",
    "regal-three-rivers-kelso" -> "0599",
    "regal-tikahtnu" -> "1994",
    "regal-times-square-new-york" -> "1929",
    "regal-town-center-port-charlotte" -> "0723",
    "regal-transit-center-cinema" -> "0294",
    "regal-treasure-coast-jensen-beach" -> "0731",
    "regal-trussville" -> "0760",
    "regal-turlock" -> "1819",
    "regal-ua-90-lake-city" -> "1214",
    "regal-ua-colorado-center-denver" -> "1308",
    "regal-ua-colorado-mills-lakewood" -> "1550",
    "regal-ua-cottonwood" -> "1307",
    "regal-ua-galaxy-dallas" -> "1306",
    "regal-ua-grant-plaza" -> "1290",
    "regal-ua-kaufman-astoria" -> "1333",
    "regal-ua-main-street-cinema" -> "1314",
    "regal-ua-sheepshead-bay" -> "1159",
    "regal-ukiah" -> "1813",
    "regal-union-square-new-york" -> "1320",
    "regal-university-town-center" -> "1025",
    "regal-valencia-stadium" -> "1038",
    "regal-valley-mall-hagerstown" -> "1908",
    "regal-valley-river-eugene" -> "0670",
    "regal-valley-view-grande-roanoke" -> "1867",
    "regal-village-at-the-peaks-longmont" -> "1673",
    "regal-village-park-carmel" -> "0147",
    "regal-virginia-center-glen-allen" -> "0165",
    "regal-virginia-gateway-gainesville" -> "1675",
    "regal-visalia" -> "1821",
    "regal-walden-galleria-stadium" -> "0675",
    "regal-warren-broken-arrow" -> "1448",
    "regal-warren-east" -> "1444",
    "regal-warren-midwest-city" -> "1482",
    "regal-warren-moore" -> "1447",
    "regal-warren-west" -> "1443",
    "regal-warrington-crossing" -> "0379",
    "regal-washington-park-bartlesville" -> "1630",
    "regal-washington-township" -> "1281",
    "regal-waterford" -> "1703",
    "regal-waterford-lakes-orlando" -> "0734",
    "regal-waugh-chapel" -> "0542",
    "regal-webster-place-chicago" -> "1793",
    "regal-wekiva-apopka" -> "1258",
    "regal-west-manchester-york" -> "0395",
    "regal-west-tower-cinema-richmond" -> "1226",
    "regal-westbrook-brookhaven" -> "1204",
    "regal-westbury-stadium" -> "1273",
    "regal-westchester-commons-midlothian" -> "1936",
    "regal-westfork-plaza-pembroke-pines" -> "0709",
    "regal-westgate-austin" -> "0953",
    "regal-westview-frederick" -> "1910",
    "regal-white-oak-garner" -> "1876",
    "regal-wilder" -> "1526",
    "regal-willamette-town-center-salem" -> "0679",
    "regal-willoughby-commons" -> "0381",
    "regal-windward-kaneohe" -> "1829",
    "regal-winrock-albuquerque" -> "1992",
    "regal-winter-park-village" -> "0721",
    "regal-yorba-linda" -> "1430",
  )

  /** The chain's theatre codes, ascending — the order the request batches below
   *  are cut from, so a batch's membership (and therefore its URL, and therefore
   *  its cache key) is stable across processes and restarts. */
  val allCodes: Seq[String] = theatreCodeBySlug.values.toSeq.sorted

  /** Upper bound on how many theatre codes ride in one `getShowtimes` request.
   *
   *  The endpoint takes a COMMA-SEPARATED `theatres=` list and answers one
   *  `shows[]` entry per theatre, so one request can serve many venues. Measured
   *  2026-08-30: the whole 396-code estate in a single request answers in 3.4s
   *  with a 2.5MB body, and a venue's slice of that response is IDENTICAL to the
   *  response its own single-theatre request returns — batching is lossless, not
   *  a summary.
   *
   *  100 rather than "all of them" because the response body is the unit the
   *  shared cache stores and every venue in a batch re-reads: at ~80 codes a
   *  batch answers in 1.8s with a ~510KB body, where the full estate is 2.5MB.
   *  Since each of the ~400 venues reads its batch's body once per date, the
   *  bigger batch would push ~5x more bytes through Mongo's (256MB-pinned)
   *  WiredTiger cache for a saving of 444 requests per sweep against a total
   *  that is already ~2% of the unbatched shape. */
  val BatchSize = 100

  /** The codes cut into balanced batches — `ceil(n / BatchSize)` groups of as
   *  near-equal size as possible, rather than `grouped(BatchSize)`, which would
   *  leave a 1-code remainder batch spending a whole request on one venue. */
  val batches: Seq[Seq[String]] = {
    val codes = allCodes
    val count = math.ceil(codes.size.toDouble / BatchSize).toInt.max(1)
    (0 until count).map(i => codes.slice(i * codes.size / count, (i + 1) * codes.size / count))
  }

  private val batchByCode: Map[String, Seq[String]] =
    batches.flatMap(batch => batch.map(_ -> batch)).toMap

  /** The batch `code` rides in — the set of theatre codes its requests name, so
   *  every venue in the batch issues the byte-identical URL and the shared cache
   *  collapses them to one upstream fetch. A code outside the map batches alone
   *  (it still works, it just shares nothing). */
  def batchFor(code: String): Seq[String] = batchByCode.getOrElse(code, Seq(code))
}
