#!/usr/bin/env python3
"""The worker's AOT class list (worker/src/main/resources/aot-classes.txt) from production heap dumps.

Usage: scripts/aot-class-list.py [--keep LIST] [--package JAR:PREFIX ...] [DUMP.hprof[.gz] ...] > NEW_LIST

The list this repo checks in is regenerated with (sbt worker/package first):
  scripts/aot-class-list.py --package worker/target/scala-3.9.0/worker_3-1.0-SNAPSHOT.jar:services.cinemas. \
    <PL dumps> <UK dumps> ... > worker/src/main/resources/aot-classes.txt
and, to add scraper classes without new dumps (what AotClassListSpec asks for when one is missing):
  scripts/aot-class-list.py --keep worker/src/main/resources/aot-classes.txt \
    --package worker/target/scala-3.9.0/worker_3-1.0-SNAPSHOT.jar:services.cinemas. > /tmp/aot-classes.txt \
    && mv /tmp/aot-classes.txt worker/src/main/resources/aot-classes.txt

Reads each dump's LOAD_CLASS records -- every class the JVM had loaded -- and prints the union, sorted,
as binary names. Hidden classes (lambdas, LambdaForms, string-concat shapes, anything named with an
address) are left out: the AOT cache cannot archive Scala's, and they are spun at run time anyway.
Take dumps from several countries' workers; `--package` adds every class a jar holds under a
package prefix -- the scrapers, which is where one country's classes differ from another's, so a
country with no dump still gets its own. A class the list lacks still loads normally, into metaspace
(the `jvm_classes_archived_loaded` gauge against `jvm_classes_currently_loaded` shows how many). Dumps: POST /heapdump, or an OOM's in
/data/heapdumps (docs/heap-dumps.md).
"""
import gzip, re, struct, sys, zipfile

HIDDEN = re.compile(r'\$\$Lambda|LambdaForm\$|/0x[0-9a-f]+|\+0x|\$Proxy\d|jdk/internal/reflect/Generated|HiddenClass')

def loaded_classes(path):
    opener = gzip.open if path.endswith('.gz') else open
    with opener(path, 'rb') as f:
        header = b''
        while not header.endswith(b'\0'):
            byte = f.read(1)
            if not byte:                                      # EOF inside the header: read(1) is b'' for ever
                sys.exit(f"{path}: truncated heap dump (ends inside its header)")
            header += byte
        id_bytes = f.read(4)
        if len(id_bytes) < 4:
            sys.exit(f"{path}: truncated heap dump (ends inside its header)")
        id_size = struct.unpack('>I', id_bytes)[0]
        f.read(8)
        read_id = (lambda b: struct.unpack('>I', b)[0]) if id_size == 4 else (lambda b: struct.unpack('>Q', b)[0])
        strings, name_ids = {}, []
        while True:
            try:
                head = f.read(9)
            except EOFError:                                  # a truncated .gz: its class records came first
                break
            if len(head) < 9:
                break
            tag, _, length = struct.unpack('>BII', head)
            if tag == 0x01:                                   # STRING: id, utf8
                body = f.read(length)
                strings[read_id(body[:id_size])] = body[id_size:].decode('utf-8', 'replace')
            elif tag == 0x02:                                 # LOAD_CLASS: serial, class id, stack serial, name id
                body = f.read(length)
                name_ids.append(read_id(body[8 + id_size:8 + 2 * id_size]))
            elif tag in (0x0c, 0x1c) and name_ids:           # the heap itself: every class is named by now
                break
            else:
                f.seek(length, 1) if not path.endswith('.gz') else f.read(length)
    return {strings[i] for i in name_ids if i in strings}

def packaged_classes(jar, prefix):
    path_prefix = prefix.replace('.', '/')
    with zipfile.ZipFile(jar) as z:
        return {n[:-len('.class')] for n in z.namelist()
                if n.endswith('.class') and n.startswith(path_prefix) and not n.startswith('META-INF/')}

arguments, names = sys.argv[1:], set()
if arguments[:1] == ['--keep']:
    with open(arguments[1]) as kept:
        names |= {line.strip().replace('.', '/') for line in kept if line.strip() and not line.startswith('#')}
    arguments = arguments[2:]
while arguments[:1] == ['--package']:
    jar, prefix = arguments[1].rsplit(':', 1)
    names |= packaged_classes(jar, prefix)
    arguments = arguments[2:]
for dump in arguments:
    names |= {n for n in loaded_classes(dump) if not n.startswith('[') and not HIDDEN.search(n)}
print('# Classes the worker loads in production, for the image\'s AOT cache (tools.ClassArchiveTraining).')
print('# Generated by scripts/aot-class-list.py from heap dumps; regenerate, do not edit by hand.')
for name in sorted(n.replace('/', '.') for n in names):
    print(name)
