#!/usr/bin/env python3
"""Rebuild the identity resolver's table of stage works — every opera and ballet Wikidata knows with five or more
sitelinks, with its names (labels and aliases) in the languages our venues bill in — as
common/src/main/resources/identity-stage-works.tsv: one work per line, `<wikidata id>\t<English name>\t<name>|<name>…`.

Cinemas show the same season broadcast under each country's name for the work ("Dziadek do orzechów", "Der
Nussknacker", "El cascanueces" for "Royal Ballet & Opera 2026/27: The Nutcracker"), so the resolver reads a season
production's work through this table. Names a venue spells that Wikidata lacks go in identity-stage-works-extra.tsv,
which this script never touches. One query, run by hand when the table should grow: `scripts/identity-stage-works.py`."""
import json, os, sys, urllib.parse, urllib.request

LANGUAGES = ("en", "pl", "de", "es", "fr", "it", "cs")
QUERY = """
SELECT ?work ?name (LANG(?name) AS ?lang) ?kind WHERE {
  VALUES ?class { wd:Q58483083 wd:Q58483088 }
  ?work wdt:P31 ?class ; wikibase:sitelinks ?sitelinks .
  FILTER(?sitelinks >= 5)
  { ?work rdfs:label ?name BIND("label" AS ?kind) } UNION { ?work skos:altLabel ?name BIND("alias" AS ?kind) }
  FILTER(LANG(?name) IN (%s))
}""" % ",".join(f'"{lang}"' for lang in LANGUAGES)
OUT = os.path.join(os.path.dirname(__file__), "..", "common", "src", "main", "resources", "identity-stage-works.tsv")


def main() -> None:
    url = "https://query.wikidata.org/sparql?" + urllib.parse.urlencode({"query": QUERY})
    request = urllib.request.Request(url, headers={"Accept": "application/sparql-results+json",
                                                   "User-Agent": "kinowo-identity-stage-works/1.0 (https://kinowo.net)"})
    rows = json.load(urllib.request.urlopen(request, timeout=300))["results"]["bindings"]
    works: dict[str, dict[str, set[str]]] = {}
    labels: dict[str, dict[str, str]] = {}
    for row in rows:
        work = row["work"]["value"].rsplit("/", 1)[-1]
        name = " ".join(row["name"]["value"].split())
        if not name: continue
        works.setdefault(work, {}).setdefault(row["lang"]["value"], set()).add(name)
        if row["kind"]["value"] == "label": labels.setdefault(work, {})[row["lang"]["value"]] = name
    lines = []
    for work, names in sorted(works.items(), key=lambda kv: int(kv[0][1:])):
        # its English label, else its label in the first language that has one (the name a search asks for)
        own = labels.get(work, {})
        english = next((own[lang] for lang in LANGUAGES if lang in own), sorted({n for ns in names.values() for n in ns})[0])
        everything = sorted({n for ns in names.values() for n in ns})
        lines.append(f"{work}\t{english}\t{'|'.join(everything)}")
    with open(OUT, "w", encoding="utf-8") as out:
        out.write("# Generated by scripts/identity-stage-works.py from Wikidata — do not edit; add to identity-stage-works-extra.tsv\n")
        out.write("\n".join(lines) + "\n")
    print(f"{len(lines)} works, {sum(len(l.split(chr(9))[2].split('|')) for l in lines)} names → {os.path.normpath(OUT)}", file=sys.stderr)


if __name__ == "__main__":
    main()
