package services.cinemas.pl

import tools.{HttpFetch, TextNormalization}
import models._
import org.jsoup.Jsoup
import services.cinemas.common.{CinemaScraper, ScrapeHorizon}

import java.time.{LocalDate, YearMonth, ZoneId}
import scala.jdk.CollectionConverters._
import scala.util.{Failure, Success, Try}

/**
 * Kino Zamek — the cinema screen of the Zamek Książąt Pomorskich (Castle of
 * the Pomeranian Dukes) in Szczecin.  The castle's programme page at
 * `https://zamek.szczecin.pl/wydarzenia/kino/` is the canonical list of
 * films currently on the programme; it contains only films, unlike the MSI
 * ticketing portal which mixes films with concerts, workshops and other
 * cultural events.
 *
 * === Strategy ===
 * 1. Fetch the kino listing page to extract the set of film slugs
 *    (`/wydarzenie/kino/<slug>/`).  This is the film allow-list.
 * 2. Walk the MSI month pages for showtime data, for as long as the portal
 *    still has a programme.
 * 3. For each MSI film-block, derive a slug from the title and check if it
 *    (or any prefix of it) appears in the allow-list.  Blocks that don't match
 *    — concerts, workshops, other non-film events — are silently dropped.
 * 4. Merge matching blocks across months, decode HTML entities, and apply
 *    sentence-case to the Polish title part.
 *
 * === Slug matching ===
 * The listing slug is generated by the WordPress site from the Polish title via
 * the standard NFD-deburr + lowercase + non-alphanumeric → `-` chain.  We
 * approximate the same transformation and look for a slug prefix match: e.g.
 * MSI title `CASABLANCA – AMERYKAŃSKA KLASYKA` → slug `casablanca` matches
 * listing slug `casablanca`.
 *
 * @parameter http   HTTP client (swap for `FakeHttpFetch` in tests).
 * @parameter cinema The [[Cinema]] source tag attached to every [[CinemaMovie]]
 *               produced by this client.
 * @parameter today  Calendar anchor the month walk starts from; defaults to the
 *               current Warsaw clock date.
 */
class KinoZamekClient(
  http:             HttpFetch,
  override val cinema: Cinema,
  today:            LocalDate = LocalDate.now(ZoneId.of("Europe/Warsaw"))
) extends CinemaScraper {

  import KinoZamekClient._

  def scrapeHosts: Set[String] = CinemaScraper.hostsOf(ListingBaseUrl, MsiBaseUrl)
  // The castle's own kino listing page — films only, unlike the MSI portal.
  override def sourceUrl: Option[String] = Some(ListingUrl)

  def fetch(): Seq[CinemaMovie] = {
    val filmSlugs = fetchFilmSlugs()

    // Walk the months instead of assuming two of them. The portal held nothing
    // past September when measured on 2026-08-05, so this loses nothing today —
    // but two months is still a horizon cap, and the day the castle programmes a
    // retrospective into the autumn we would silently not see it.
    val byMonth  = scala.collection.mutable.LinkedHashMap.empty[YearMonth, Seq[MsiScraper.RawSlot]]
    val failures = scala.collection.mutable.LinkedHashMap.empty[YearMonth, Throwable]

    val live = ScrapeHorizon.liveMonths(YearMonth.from(today)) { ym =>
      Try(http.get(monthUrl(ym))) match {
        case Failure(why)  => failures(ym) = why; false
        case Success(html) =>
          byMonth(ym) =
            if (html.isEmpty) Seq.empty
            else MsiScraper.parseMonthWithYear(html, ym, MsiBaseUrl, cleanTitle)
                   .filter(s => isFilm(s.title, filmSlugs))
          byMonth(ym).nonEmpty
      }
    }

    // Don't swallow a fetch failure INSIDE the programme's span. A timeout / 5xx
    // from the MSI host must propagate so `RetryingCinemaScraper` retries and a
    // persistent failure surfaces as a red uptime error — not a silent, swallowed
    // zero recorded as a successful "0 showtimes" scrape (white on the uptime
    // bar), which scrape-prune would then read as the films having stopped.
    //
    // A failure PAST the last month that carried a programme is different: those
    // are the probes that end the walk, and a blip on one of them must not fail an
    // otherwise complete scrape. When no month yielded anything at all, every
    // failure counts — a portal that is down must never read as a quiet venue.
    val lastLive = live.lastOption
    failures.collectFirst { case (ym, why) if lastLive.forall(!ym.isAfter(_)) => why }
      .foreach(throw _)

    MsiScraper.toMovies(byMonth.values.toSeq.flatten, cinema)
  }

  /** Fetch the kino listing page and return the set of film slugs. */
  private def fetchFilmSlugs(): Set[String] = {
    val html = Try(http.get(ListingUrl)).getOrElse("")
    if (html.isEmpty) return Set.empty
    val document = Jsoup.parse(html)
    document.select("a[href*='/wydarzenie/kino/']").asScala.toSeq
      .flatMap(a => SlugPat.findFirstMatchIn(a.attr("href")).map(_.group(1)))
      .toSet
  }
}

object KinoZamekClient {

  val ListingBaseUrl = "https://zamek.szczecin.pl"
  val ListingUrl     = s"$ListingBaseUrl/wydarzenia/kino/"
  val MsiBaseUrl     = "https://bilety.zamek.szczecin.pl"

  /**
   * Date-scoped MSI month page.  We hit `/MSI/mvc/pl` directly rather than the
   * bare `/MSI` path: `/MSI?…` 301-redirects to `/MSI/?…` which then 302-redirects
   * to a bare `/MSI/mvc/pl` — dropping the `date` query parameter in the process, so
   * the redirect-following client always landed on the unscoped default page and
   * never actually fetched the requested month (next-month showtimes were silently
   * lost).  The direct `/MSI/mvc/pl?…&date=…` URL — the same shape every other MSI
   * cinema uses — returns the correct month in a single hop.
   */
  def monthUrl(ym: YearMonth): String =
    s"$MsiBaseUrl/MSI/mvc/pl?sort=Name&date=${ym.getYear}-${"%02d".format(ym.getMonthValue)}"

  private val SlugPat = """/wydarzenie/kino/([^/]+)/""".r

  /**
   * Decode HTML entities and apply sentence case to the title.  For Zamek we
   * keep the full title (including original-language subtitle in parens) because
   * those subtitles are part of the film identity, not format codes — so it
   * never carries a buried format tag and emits no `Showtime.format` tokens.
   */
  private[cinemas] def cleanTitle(raw: String): (String, List[String]) = {
    // Jsoup already decodes HTML entities in attribute values.
    (ScraperParse.sentenceCase(raw.trim), Nil)
  }

  /**
   * Derive the WordPress slug that the listing site would generate for `title`
   * and check whether it appears (as a prefix match) in `filmSlugs`.
   *
   * The slug is generated by:
   *   1. Keep only the part before the first em-dash `–`, en-dash `—`, or colon
   *      (those are programme-series suffixes, not slug components).
   *   2. Apply NFD deburr (diacritics + `ł`→`l`).
   *   3. Lowercase; replace non-alphanumeric runs with `-`; strip leading/trailing `-`.
   *
   * Matching uses a prefix: listing slug `casablanca` matches derived slug
   * `casablanca-amerykanska-klasyka`.  If no film slug from the listing is a
   * prefix of (or equal to) the derived slug, the event is considered non-film.
   *
   * Edge cases:
   *   - When `filmSlugs` is empty (fetch failed), ALL MSI events pass through
   *     rather than returning nothing.
   */
  private[cinemas] def isFilm(title: String, filmSlugs: Set[String]): Boolean = {
    if (filmSlugs.isEmpty) return true
    val derived = toSlug(title)
    filmSlugs.exists(s => derived == s || derived.startsWith(s + "-") || s.startsWith(derived + "-"))
  }

  /** Best-effort approximation of the WordPress slug derivation. */
  private[cinemas] def toSlug(title: String): String = {
    // Strip original-language subtitle in parens at the end
    val withoutSubtitle = title.replaceFirst("""\s*\([^)]+\)\s*$""", "").trim
    // Take only the part before an em-dash, en-dash, colon, or slash (series suffix)
    val base = withoutSubtitle.split("""[–—:/]""").head.trim
    // Deburr (NFD + strip combining + ł→l)
    val deburred = TextNormalization.deburr(base)
    // Lowercase, replace non-alphanumeric sequences with -
    deburred.toLowerCase
      .replaceAll("[^a-z0-9]+", "-")
      .stripPrefix("-").stripSuffix("-")
  }
}
